### ISSUE TITLE
[Feature] Add login functionality from firebase

### ISSUE THREAD

**Issue by Satyam1923** [Satyam1923/Spring-Music-Player#10]
By implementing Firebase authentication, we can enhance the security of our application while providing users with a seamless and familiar login experience. Additionally, Firebase provides features like user management, authentication state persistence, and customizable authentication flows, which can significantly streamline the development process. It will help user to have their own data whenever the visit the page.

**Comment by Satyam1923** [comment]
If you are not confortable with firebase feel free to use any OAuth platform. Like Supabase, Pocketbase.

**Comment by WYGIN** [comment]
Hi I would like to take this issue

**Comment by sadvika05** [comment]
Hi @Satyam1923,

I've reviewed the issue and I believe implementing Firebase authentication would indeed be a valuable addition to our application. It not only enhances security but also offers a seamless login experience for our users. Firebase's user management features and authentication state persistence could greatly benefit our development process by providing a robust framework to handle user authentication.

Given my familiarity with Firebase and previous experience with similar implementations, I'd like to take on this task. Could you please assign the issue to me? I'm eager to contribute and ensure that our users have a smooth and secure login experience.

Looking forward to your response!

**Comment by Satyam1923** [comment]
@sadvika05 Fine go on!

**Comment by sadvika05** [comment]
I have added please check it!

**Comment by lovelyANSH2410** [comment]
Hey there! I have previously worked on signUp/signIn and forgot password user authentications methods in multiple projects of mine if you could give me the opportunity to contribute for this feature.

**Comment by AmrutaZagade** [comment]
Hi @Satyam1923 I would like to contribute to this project.

**Comment by sadvika05** [comment]
@Satyam1923 please check
I have raised a pull request

**Comment by WYGIN** [comment]
> @Satyam1923 please check I have raised a pull request
add `#10` in PR description

**Comment by harsh6045** [comment]
It would be great if you could assign me this issue..!
