### ISSUE TITLE
BUG: Search and Shuffle button is not responsive .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Satyam1923/Spring-Music-Player#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

At screen size 990 x 695 the search and shuffle button is overflowing from the main container .

![Screenshot 2024-05-14 164550](https://github.com/Satyam1923/Spring-Music-Player/assets/118350936/ac163661-688f-4fce-b87e-531795c33967)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@Ayushmaanagarwal1211 go for it.

**Comment by Ahamad-Tanzeel-Khan** [comment]
Hey @saurabhsingh720 I have read the issue and wanted to contribute in it. 
would love assign this issue to me under GSSOC'24
