### ISSUE TITLE
Feat: Implementation of React Router Dom for Multi-Page Navigation

### ISSUE THREAD

**Issue by CoderSwarup** [Satyam1923/Spring-Music-Player#105]
### Describe the feature

The website lacks routing functionality, preventing users from navigating to multiple pages. Given that the application is built using the React framework, which primarily caters to single-page applications (SPAs), the integration of React Router Dom is essential. This library facilitates multi-page navigation within React applications and enables seamless transitions between different sections of the website.

please assign me this issue i want to work on this 

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/128630311/e470ef6b-92ad-457c-8424-c5ed786dcb31)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mohit-bhandari45** [comment]
I want to work on this issue under gssoc24

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
