### ISSUE TITLE
Add Signup and Login backend server

### ISSUE THREAD

**Issue by piyush-gangrade** [Satyam1923/Spring-Music-Player#109]
### Describe the feature

Create routes for user signup and login to handle data storage in MongoDB and user authentication. The signup route will validate input, hash passwords, and store user data. The login route will validate input, verify credentials, and return a JWT token for authenticated users

### Add ScreenShots

No user authentication is currently implemented.

![Screenshot 2024-05-15 002738](https://github.com/Satyam1923/Spring-Music-Player/assets/133166222/93362819-df8e-4ccf-b2a7-5ad30acf80cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by SaranshKhandelwal977** [comment]
Hi, please assign this issue to me under GSSOC'24, I have a good command of backend services like this

**Comment by Satyam1923** [comment]
@piyush-gangrade you wants to do it with firebase>?

**Comment by piyush-gangrade** [comment]
@Satyam1923 I recommend using Node.js, Express.js, and MongoDB for this. However, if you prefer an implementation with Firebase, I can handle that as well

**Comment by Satyam1923** [comment]
@piyush-gangrade then how do you plan to host MongoDb server for free?

**Comment by piyush-gangrade** [comment]
@Satyam1923, we can use the MongoDB Atlas M0 Sandbox server for testing and initial stages, as it is free.
