### ISSUE TITLE
[Enhancement] Change frontend to React

### ISSUE THREAD

**Issue by Satyam1923** [Satyam1923/Spring-Music-Player#11]
Currently, our application utilizes EJS for rendering dynamic pages. However, to achieve real-time interactivity and enhance user experience, we aim to migrate from EJS to React, a powerful JavaScript library for building interactive user interfaces.

**Comment by sadvika05** [comment]
@Satyam1923 
I've been following the discussions regarding our application's development closely, and I fully agree with the decision to migrate from EJS to React. React's capabilities in building dynamic and interactive user interfaces align perfectly with our goal of enhancing user experience.

Given my expertise in React and experience with similar migrations in the past, I believe I can contribute effectively to this migration process. Could you please assign this issue to me? I'm eager to be part of this transition and ensure a smooth and successful migration.

Looking forward to your response!

**Comment by Satyam1923** [comment]
@sadvika05, since you will be working on React, it would be helpful for both of us if you work according to the Figma design that I have provided. I'll also give you the link for it. Currently, it's only for widescreen, but by the time everything works, I'll create a UI for mobile as well. Since you are also implementing a login page, you can design the UI with a background blur just for the login part of the main page.

figma link: https://www.figma.com/file/mrTzLDEAtHPOsDl99R3kOY/Spring-Music-Player?type=design&node-id=0%3A1&mode=design&t=M0XrFomli5ApTypl-1

**Comment by suraj-9849** [comment]
I want to work on this issue. I can improve it by adding the framer Motion to it and make the website better and animated with the help of react so Can u please assign this to me @Satyam1923 sir.

**Comment by sadvika05** [comment]
@Satyam1923 
yes, I'll do that

**Comment by Satyam1923** [comment]
> I want to work on this issue. I can improve it by adding the framer Motion to it and make the website better and animated with the help of react so Can u please assign this to me @Satyam1923 sir.

So as @sadvika05 is going to port the application from EJS to React after she is done with you can go ahead with it

**Comment by anushkapal28** [comment]
I hope you're doing well. I'm interested in working on the issue of improving website animation by integrating Framer Motion with React. I believe this enhancement can significantly elevate the user experience.

Could you please assign this issue to me?

**Comment by Vivek-yadav01** [comment]
Sir im frontend developer with good hand in reactjs,tailwind CSS , diff animation library like acertinity can I work with you?

**Comment by atharvmalve** [comment]
@Satyam1923 
Hi there! I've been involved in the design process of our application and have a solid understanding of React.js, making me well-equipped to tackle this migration task. Additionally, I'd like to emphasize that we can make design changes if needed during the development stage, ensuring optimal user experience. I'd love to take ownership of this issue and ensure a smooth transition from EJS to React. Looking forward to contributing!

**Comment by amishah1110** [comment]
Hey I have a solid understanding of ReactJS, please assign this issue to me. Thank you!

**Comment by Satyam1923** [comment]
@atharvmalve help @sadvika05 as she is already assigned for this issue

**Comment by atharvmalve** [comment]
@Satyam1923 Thank you for the oppourtunity!

**Comment by rahulpoonia29** [comment]
@Satyam1923 Hi, I have a good understanding of React JS and have myself made some projects. I would like to work on this issue with fellow contributors to gain knowledge of working on a real-life project. It would provide learning to me.

**Comment by Satyam1923** [comment]
@rahulpoonia29 you can go with it just collaborate with other till what they have reached.

**Comment by rahulpoonia29** [comment]
@Satyam1923 Thanks

**Comment by atharvmalve** [comment]
@sadvika05  @rahulpoonia29  can we connect on discord, to discuss the distribution of the work??

**Comment by sadvika05** [comment]
@Satyam1923 should i separate client-side and server-side before migrating ?

**Comment by rahulpoonia29** [comment]
@atharvmalve @sadvika05 https://discord.com/invite/duNfJ9fb

**Comment by Satyam1923** [comment]
@sadvika05 yes that would be very helpful.

**Comment by yujit2003** [comment]
@Satyam1923 I would be happy to work on this issue

**Comment by Muskansahuincredible** [comment]
PLEASE ASSIGN ME AS I KNOWN FULL STACK SO I CAN DO IT BETTER PLEASE ASSIGN ITS A REQUEST

**Comment by TomLucasakaTGeek** [comment]
Assign this issue to me, I have built a lot of personal and client projects on React.
