### ISSUE TITLE
Homepage Required 

### ISSUE THREAD

**Issue by aanchalpahuja18** [Satyam1923/Spring-Music-Player#110]
### Describe the feature

A homepage would give a better UX for users to use it. 

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/136963878/6852c187-7885-4b62-855b-0af22b879102)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aanchalpahuja18** [comment]
@Satyam1923 Kindly assign me this issue. I want to work on it to improve the UI & UX for your website

**Comment by riyasachdeva04** [comment]
> @Satyam1923 Kindly assign me this issue. I want to work on it to improve the UI & UX for your website

I have assigned you the issue. Keep us posted on your progress.

**Comment by aanchalpahuja18** [comment]
@riyasachdeva04 I am Done with the homepage, Just left with the Router feature so that the components can be connected with each other, could you please suggest that should I also add clickable links in the navbar
