### ISSUE TITLE
Create a Footer component

### ISSUE THREAD

**Issue by Riddhi162** [Satyam1923/Spring-Music-Player#111]
### Describe the feature

Since the footer is missing we can subdivide the footer into three parts
1.Company name and logo
2.Links to Current top artists,top songs,language,company as lists
3.Link to socials.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/135015856/88cc2315-9d64-4d83-987e-713753e6c9fa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by niteshbca** [comment]
@Riddhi162  please assign to me task and experience in the IT industry.

**Comment by saurabhsingh720** [comment]
@Riddhi162  do it.
Keep in mind that UI and footer combination must bhe good.

**Comment by harsh6045** [comment]
It would be great if you could assign me this issue..!

**Comment by Riddhi162** [comment]
> @Riddhi162 do it. Keep in mind that UI and footer combination must bhe good.

yes sure ill make it look appealing!

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
