### ISSUE TITLE
Add a language dropdown list

### ISSUE THREAD

**Issue by Riddhi162** [Satyam1923/Spring-Music-Player#112]
### Describe the feature

The user can listen to songs of the language he likes so we can add a dropdown functionality regarding this.
So when user selects a particular language he/she will be recommended that particular language songs

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/135015856/8c6165db-1463-4ce4-a649-f3fe8f024783)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by riyasachdeva04** [comment]
Before we proceed, could you please provide some specifics on how you plan to tackle this task?

Backend Implementation: How do you plan to integrate language selection functionality into our backend?

Frontend Integration: What approach do you propose for integrating the language selection dropdown into our frontend interface? Will this involve any significant UI changes or additions?

**Comment by saurabhsingh720** [comment]
@Riddhi162  clarify your task and if u are able to do asap then it is good to assign u.

**Comment by Riddhi162** [comment]
So in your provided api link there is a global search option wherein there is a language parameter 
![Screenshot 2024-05-16 082610](https://github.com/Satyam1923/Spring-Music-Player/assets/135015856/a5c0047c-aa2d-49b0-aabf-bb42432fdf2f)
And in the index.js file the way we are calling year and name of the artist we can also call its language and then filter the music array based on the selected language I'm willing to work on this. I'll make sure that I'll complete this issue.
![Screenshot 2024-03-08 214826](https://github.com/Satyam1923/Spring-Music-Player/assets/135015856/eee09d86-6d31-416f-8a31-be7406229de2)

**Comment by Riddhi162** [comment]
> Before we proceed, could you please provide some specifics on how you plan to tackle this task?
> 
> Backend Implementation: How do you plan to integrate language selection functionality into our backend?
> 
> Frontend Integration: What approach do you propose for integrating the language selection dropdown into our frontend interface? Will this involve any significant UI changes or additions?

We can include the language icon on the bar where there is search option and that will simply create a dropdown list and as we select the language top songs in that language will be available. So no such significant ui changes

**Comment by saurabhsingh720** [comment]
@Riddhi162  do it.

**Comment by madhurajituri** [comment]
Please assign this to me! I will filter the songs according to the language selected.

**Comment by riyasachdeva04** [comment]
@Riddhi162 Please update your status on this issue. If you won't be taking it forward, it would be assigned to someone else.

**Comment by Riddhi162** [comment]
@riyasachdeva04 I created the pull request please check.
