### ISSUE TITLE
Feat: Add favorites

### ISSUE THREAD

**Issue by skshrinaya** [Satyam1923/Spring-Music-Player#114]
### Describe the feature

Hi , I am a GSSOC'24 contributor . Your Figma design really looks nice . It would be better if you add liked songs in the playlist and favorite icon in the songs list . I would like to contribute to this project. Please assign me this issue.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/125351066/4c48d932-5f21-485f-aba5-a591586530f3)
like this you can add a favorite icon in the songs menu.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by skshrinaya** [comment]
@Satyam1923 Can I start working on this issue?

**Comment by Subhajit098** [comment]
Hey @skshrinaya can you share your approach like how you will develop this kind of functionality
