### ISSUE TITLE
Feat:Add Loading Animation

### ISSUE THREAD

**Issue by razerbotog** [Satyam1923/Spring-Music-Player#118]
### Describe the feature

Loading animation while fetching data will enhanced the User Experience.
**It's an most important feature **

Here is the steps:

- [ ] Make a reusable loading component.
- [ ] A new useState Hook name [loading, setLoading] will manage the component to display or not.

### Add ScreenShots

![Untitled](https://github.com/Satyam1923/Spring-Music-Player/assets/123809151/cca78629-2f78-4833-8dbc-796eebb203c9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@razerbotog  can u give the demo of that.

**Comment by dhruv389** [comment]
Hello @saurabhsingh720 ,
Please checkout this solution in this issue no: #78  .

**Comment by razerbotog** [comment]
https://github.com/Satyam1923/Spring-Music-Player/assets/123809151/a3f220d0-f74d-4928-947a-bcfca9caf979

Here is the demo @saurabhsingh720 . Please checkout.

- [ ] User Experience is improved.

If there is any other requirements regarding this issue. Please let me know.

**_Changes made_**

- [ ] Made a reusable component.
- [ ] Declared a state using useState.

**Comment by razerbotog** [comment]
hey, @saurabhsingh720 Have you reviewed the above comment  ?
