### ISSUE TITLE
ADD BACKGROUND GRADIENT

### ISSUE THREAD

**Issue by Gauranshgoel123** [Satyam1923/Spring-Music-Player#119]
### Describe the feature

As you described in the figma design, I could add the background gradient to the website

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/121503835/81b76aed-80e0-46f6-bd42-956064c86985)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kashi-verma** [comment]
I am willingly want to work on this issue so i request to  @Satyam1923 assign me this issue

**Comment by Satyam1923** [comment]
@Gauranshgoel123 you can work on it but please don't use photo make it with css.

**Comment by Gauranshgoel123** [comment]
yes i'll use css 👍
thanks for assigning

**Comment by Gauranshgoel123** [comment]
@Satyam1923 pls refer PR #184
