### ISSUE TITLE
[Feature] Add top 10 songs and top 10 Artitst

### ISSUE THREAD

**Issue by Satyam1923** [Satyam1923/Spring-Music-Player#12]
In order to enrich the user experience and provide valuable content upfront, we propose integrating the Billboard API from RapidAPI into our application. This integration will allow us to showcase the top 10 songs and top 10 artists directly on the front page, offering users immediate access to trending music content.

You can find this free api on : https://rapidapi.com/apimaker/api/billboard2

**Comment by SandhyaGiribabu** [comment]
I will be glad to work on this.Can you assign this issue to me?

**Comment by mehakkgoel** [comment]
hey i would like to workk on this issue. gssoc24

**Comment by sadvika05** [comment]
would like to work on this issue previously I have made a spotify clone, I can integrate  Billboard API from RapidAPI into our application and I'm a GSSOC'24 contributor.

**Comment by Satyam1923** [comment]
@SandhyaGiribabu and @mehakkgoel you both can work on this feature.

**Comment by SandhyaGiribabu** [comment]
@mehakkgoel contact me... my discord username sandhyag

**Comment by yujit2003** [comment]
@Satyam1923 Please assign this to me, I will be happy to work on this issue

**Comment by TomLucasakaTGeek** [comment]
Assign this issue to me, I would like to work on this.

**Comment by Tanu2205** [comment]
Can you please assign me this issue?

**Comment by Satyam1923** [comment]
inactivity.
