### ISSUE TITLE
SIDE NAVBAR FEATURE

### ISSUE THREAD

**Issue by Gauranshgoel123** [Satyam1923/Spring-Music-Player#121]
### Describe the feature

As you described in the figma design, I could add these featues

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/121503835/046024f0-f16b-4584-8c6f-e4f1598f0e0c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dhruv389** [comment]
Hello @Gauranshgoel123 ,
Please checkout this issue #78 
this is already taken , please close your this issue.

**Comment by Gauranshgoel123** [comment]
okay
