### ISSUE TITLE
Feat: Improving the UI elements

### ISSUE THREAD

**Issue by Sumitshvr** [Satyam1923/Spring-Music-Player#123]
### Describe the feature

Being a designer and a web developer improving the UI elements is very necessary. So, in your project i can improve the UI for your project.  I can upgrade the alignments and the UI components. Even i can provide you the react code for your figma design

### Add ScreenShots

![Screenshot 2024-05-16 213555](https://github.com/Satyam1923/Spring-Music-Player/assets/118909272/0a130d53-0766-4ad5-9945-74371fbb5bfb)

![Screenshot 2024-05-16 213539](https://github.com/Satyam1923/Spring-Music-Player/assets/118909272/6af1a61b-9717-4854-befd-d36a13a6f4fd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sumitshvr** [comment]
Assign me the work!

**Comment by saurabhsingh720** [comment]
@Sumitshvr Go for it.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
