### ISSUE TITLE
[Enchacement] Add layout for adding top 10 songs and artists

### ISSUE THREAD

**Issue by Satyam1923** [Satyam1923/Spring-Music-Player#13]
Incorporate a dedicated division into our EJS templates to facilitate the rendering of the top 10 songs and artists, which will be dynamically fetched from the backend upon completion of Issue #12. This division will serve as the UI component for showcasing trending music content directly within our application.

**Comment by SandhyaGiribabu** [comment]
Hi I would like to take this issue.

**Comment by sadvika05** [comment]
Hey @Satyam1923,

I suggest incorporating a dedicated division into our EJS templates to display the top 10 songs and artists dynamically fetched from the backend upon completion of Issue #12. As a GSSoC'24 contributor, I believe this addition will enhance our application's user experience by showcasing trending music content directly within our interface.

What are your thoughts on this proposal?

**Comment by Satyam1923** [comment]
@sadvika05
Fine go on! 
Make different React components for all the layout.

**Comment by anushkapal28** [comment]
As a GSSoC'24 contributor, I'm eager to enhance our application's user experience. I propose adding trending music content directly within our interface. Could you please assign me to work on this?

**Comment by Satyam1923** [comment]
@anushkapal28 ya same thing I have purposed you can take a look in figma design for it.

**Comment by TomLucasakaTGeek** [comment]
Hey @Satyam1923 I would like to work on this issue.
