### ISSUE TITLE
BUG: Change in the overall ui(margins & paddings and search bar and many more]

### ISSUE THREAD

**Issue by mohit-bhandari45** [Satyam1923/Spring-Music-Player#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Description:-**
The ui is good but lack alignment and many more. I can work upon it and change the margins and paddings and many more.

**Screenshots:-**
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/151373021/978410e6-0109-4945-a9f0-d077096b0c9c)

**Steps to reproduce:-**
Step1 :- Run the app
Step2:- See the home page

Assign it to me under gsooc24 and add two labelsto it
"gsooc2" and "level2"

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@mohit-bhandari45 do it as soon as possible

**Comment by saurabhsingh720** [comment]
Maintain the responsiveness in all screen view

**Comment by mohit-bhandari45** [comment]
Is it looking good?
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/151373021/314760db-506a-4e9d-abe9-c0241e08b34e)

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by Satyam1923** [comment]
fixed.
