### ISSUE TITLE
Feat: Integrate API for Latest Music in Main Section

### ISSUE THREAD

**Issue by ShivamGupta1802** [Satyam1923/Spring-Music-Player#131]
### Describe the feature

This feature request aims to enhance the application by integrating an API that provides the latest music. The latest music will be displayed prominently in the main section, ensuring that users have access to the newest and trending songs. And also adding the Trending Artist in the right Corner.. 

Please assign this Task to me Under GSSOC'24 with desired label

## Demo for image Showcasing After Fetching the latest Music
![image1](https://github.com/Satyam1923/Spring-Music-Player/assets/120817773/2599cc67-12ab-4608-9865-d5d8297552c6)

## Demo for Tending artist list
![image2](https://github.com/Satyam1923/Spring-Music-Player/assets/120817773/d4bd0ba4-85b2-4282-8984-d0a2eb55b5a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harsh6045** [comment]
It would be great if you could assign me this issue..!

**Comment by Satyam1923** [comment]
@ShivamGupta1802 you can work on it.
