### ISSUE TITLE
BUG: NavBar and Search field UI Bugs

### ISSUE THREAD

**Issue by The-Phoenics** [Satyam1923/Spring-Music-Player#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The nav items are not in the center of the nav section.
![nav](https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/764bb72c-918e-440a-9fe1-e4665720d4ef)

Search icons is not properly aligned with the search input field, it is supposed to be on left side inside the search
![sbar](https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/3a7ab0f4-0208-4d6a-93f0-89e4425121b0)
![searchbar](https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/6f4aa591-6698-45ad-b38a-1c02c1949485)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by The-Phoenics** [comment]
Hey @Satyam1923, @saurabhsingh720
I would like to work on this for GSSoC'24. Can you assign this to me?

**Comment by Satyam1923** [comment]
@The-Phoenics you can modify it.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by Reenakumaridowlapalli** [comment]
Hi @Satyam1923 ,
                   I would like work on this issue. Can you please assign this task to me?
