### ISSUE TITLE
Feat: Add Signup and Login pages (React Components)

### ISSUE THREAD

**Issue by The-Phoenics** [Satyam1923/Spring-Music-Player#136]
### Describe the feature

Currently there are not SignIn and SignUp features. I would like to work on implementing the UI for Signup and Login as in provided `Spring Music Player` figma design file.

### Add ScreenShots

![feature](https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/a716f794-09cd-40e2-a4e9-c256fe9858c2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@The-Phoenics you can work on this issue.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by Annu117** [comment]
@Satyam1923 can u plz assign this task to me under gssoc'24. I would like to work on this. And will make it interactive too.

**Comment by The-Phoenics** [comment]
Hey @Annu117, @Mahimatestgithub
This issue is already assigned to me and I'm half way through my solution to this issue. So, kindly explore other issues.
