### ISSUE TITLE
Improve the UI of the Home-Page

### ISSUE THREAD

**Issue by suraj-9849** [Satyam1923/Spring-Music-Player#139]
### Describe the feature

As you can see I will keep the best structure to the cards and improve this part of section and even make it responsive

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/146669517/d673ffdc-7e04-4009-9d9f-a14413cd51ef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GauriGA** [comment]
@Satyam1923 Could you please assign this issue to me under the GSSOC'24 label?
