### ISSUE TITLE
Feat: Add footer to the page  and  title to the navbar

### ISSUE THREAD

**Issue by jayanththalla** [Satyam1923/Spring-Music-Player#140]
### Describe the feature

Like Spotify it should have the footer and title  to the navbar.
please assign @pa

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/121346142/83bb7dac-5570-4273-af20-ee1d2c34802a)
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/121346142/7c8ad384-a810-478c-8b65-a24e18b5f079)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harsh6045** [comment]
It would be great if you could assign me this issue..!

**Comment by Satyam1923** [comment]
@jayanththalla you can help me with the design so it could be better .

**Comment by jayanththalla** [comment]
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/121346142/6fcc3efc-c169-4bbf-8aa0-4b5734ba502f)
@Satyam1923  i want to make footer like this
