### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by AbhiSharma1511** [Satyam1923/Spring-Music-Player#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

UI element are unordered and unresponsive for small screens.
![Screenshot (127)](https://github.com/Satyam1923/Spring-Music-Player/assets/99421033/b146bb8e-3304-4a1e-a509-f3c02251b976)

 I want to work on responsiveness and also want to chane some UI. Please assign me this issue,

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AbhiSharma1511** [comment]
Thanks bro, i will complete it as soon as possible and send you the PR

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
