### ISSUE TITLE
Feat: Preloader

### ISSUE THREAD

**Issue by Jagpreet153** [Satyam1923/Spring-Music-Player#143]
### Describe the feature

Addition of engaging preloader for enhancing UI of website

### Add ScreenShots

![Screenshot 2024-05-21 180939](https://github.com/Satyam1923/Spring-Music-Player/assets/119691733/3c3bfcef-808c-46fd-96ce-4bdecb90c804)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@Jagpreet153 
Can u give short video for preloading

**Comment by Jagpreet153** [comment]
Sure @saurabhsingh720 

The below preloader was applied in a site for space theme for music theme I can SVG of music UI and convert to preloader using useEffect. 

https://github.com/Satyam1923/Spring-Music-Player/assets/119691733/1a06510e-e222-413a-9b4e-13a3e2ee2552

For your music website

![undraw_Compose_music_re_wpiw](https://github.com/Satyam1923/Spring-Music-Player/assets/119691733/4f5c54fc-d7e2-42ee-820b-681f5e76d916)

**Comment by Jagpreet153** [comment]
@Satyam1923 @saurabhsingh720 any updates on the issue??

**Comment by saurabhsingh720** [comment]
@Satyam1923 
I think it is good if its size is smaller and when the colour get changed slightly that matches the UI

**Comment by Jagpreet153** [comment]
> @Satyam1923 I think it is good if its size is smaller and when the colour get changed slightly that matches the UI

Sure It would be matching the UI of the site . Have a look on some other loaders . The size and colors can be changes accordingly .

https://github.com/Satyam1923/Spring-Music-Player/assets/119691733/3898d599-4041-4f35-99b1-a522f5fc2ba1


https://github.com/Satyam1923/Spring-Music-Player/assets/119691733/ddc42021-010e-4e0d-892d-ae16ad23be9a

**Comment by Jagpreet153** [comment]
@Satyam1923 @saurabhsingh720 Kindly give response to this issue

**Comment by Satyam1923** [comment]
@Jagpreet153 looks fine.

**Comment by Jagpreet153** [comment]
> @Jagpreet153 looks fine.

So , Kindly assign this issue to me...

**Comment by saurabhsingh720** [comment]
@Jagpreet153 
I think the last preloaded is better.
What do u think @Satyam1923

**Comment by Jagpreet153** [comment]
No problem I will add a preloader matching to the theme of this site
