### ISSUE TITLE
BUG: Bell icon is not functional

### ISSUE THREAD

**Issue by DownOnCoffee** [Satyam1923/Spring-Music-Player#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I click the bell icon , nothing happens Thus it is not functional which makes the user experience bad.
![Screenshot (1269)](https://github.com/Satyam1923/Spring-Music-Player/assets/94672955/7e27b4ff-8822-411c-8323-2ef1e75c8994)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@DownOnCoffee 
Notification section

**Comment by DownOnCoffee** [comment]
@saurabhsingh720 has the notification system been developed on the backend?

**Comment by Satyam1923** [comment]
@DownOnCoffee no yet.
