### ISSUE TITLE
Feat: Adding song cards 

### ISSUE THREAD

**Issue by HardCoder404** [Satyam1923/Spring-Music-Player#145]
### Describe the feature

As we know when the users come on the any music website, they first see the UI and then the newly songs , popular songs, and many more, and all this are shown in the cards container. So for better User Interfaces and more attractive, we should add a cards of particular section. 

### Add ScreenShots

![Screenshot 2024-05-22 012303](https://github.com/Satyam1923/Spring-Music-Player/assets/127084297/ec61b021-db97-4152-b5a6-b76c5108f49f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
hey i can fix this issue please assign it to me
