### ISSUE TITLE
BUG: Alignment not proper

### ISSUE THREAD

**Issue by HK853** [Satyam1923/Spring-Music-Player#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![chrome_MKNuDh4ts9](https://github.com/Satyam1923/Spring-Music-Player/assets/113816862/f2b5f683-6981-4071-8841-138abdfd5a39)

you can see there are many issue in spacing padding alignment and all.

**Can you assign me this issue under GSSOC'24.**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@
