### ISSUE TITLE
BUG: Readme file frontend mistake

### ISSUE THREAD

**Issue by vanisharma2003** [Satyam1923/Spring-Music-Player#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

for frontend portion there is mistake in navigating directory. It should be cd frontend.  Contributors will see these guidelines, it should be correct so that even newbie can contribute to the project and not face any errors.
I am also attaching the screenshot of the error. I have recently make a contribution in this project and also I am active contributor in GSSOC. Please assign this issue to me.
![WhatsApp Image 2024-05-22 at 14 39 16_e9e03cf5](https://github.com/Satyam1923/Spring-Music-Player/assets/137780818/1d7958b7-88d5-4210-af51-de7e63857519)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
i'll fix it no need for an issue to be created
