### ISSUE TITLE
BUG: UI Fixing the UI of the home screen

### ISSUE THREAD

**Issue by Ratangulati** [Satyam1923/Spring-Music-Player#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="743" alt="Screenshot 2024-05-22 at 5 23 43 PM" src="https://github.com/Satyam1923/Spring-Music-Player/assets/116749593/7b05f905-3353-4dcd-9195-b378e43de372">

I would like to change the alignment on the home screen as it is showing text and the mockups and there is no space between them.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Ratangulati spaces you can work allignment someone else is also handling.
