### ISSUE TITLE
[Feature] Implement User Database with Firebase

### ISSUE THREAD

**Issue by Satyam1923** [Satyam1923/Spring-Music-Player#15]
Implementing Firebase would provide:
1. Data collection
2. User authentication
3. User Registration 
4. User Profile Management
It would be grateful to have these features in order to make the appealing user experience. By adding Firebase as the user database for our application, we aim to streamline user management, enhance data security, and provide a seamless authentication and data storage experience for our users.

**Comment by WYGIN** [comment]
Hi I would like to take this issue

**Comment by sadvika05** [comment]
Hi @Satyam1923,

I've been exploring the benefits of integrating Firebase into our application, and it's clear that it offers a range of powerful features. From seamless user authentication to efficient data management, Firebase can significantly elevate our app's functionality and user experience.

As a GSSoC'24 contributor, I'm particularly excited about leveraging Firebase's capabilities to enhance our app's performance and user engagement.

Assigning me this task would bring several advantages:

Streamlined User Management: Firebase simplifies user authentication and profile management, ensuring a smoother experience for both users and admins.
Enhanced Security: With Firebase's robust security measures, we can trust that our users' data remains safe and protected.
Scalability: Firebase scales effortlessly with our app's growth, ensuring that we can accommodate increasing user numbers without sacrificing performance.
Given my familiarity with Firebase and enthusiasm for this project, I'm confident I can deliver excellent results. Could you please assign this task to me?

Looking forward to contributing to our app's success!

**Comment by Satyam1923** [comment]
@WYGIN  Go on!

**Comment by lakshyajn** [comment]
Hey @Satyam1923 
I would like to work upon this issue,
I'm familiar with firebase and integrating it with apps/websites.
So, I would be good to solve this issue.

Please Assign This Issue To Me :)

I'll work on my own branch

**Comment by Satyam1923** [comment]
@lakshyajn ya you can work!
