### ISSUE TITLE
BUG: Modularizing the project

### ISSUE THREAD

**Issue by Ratangulati** [Satyam1923/Spring-Music-Player#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am planning to use react-router to make the code more accessible by making a pages folder under src where all the pages will be stored and creating UI for the search screen from the Figma uploaded.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Ratangulati nice idea but how will you contribute since everyone is working on something else.

**Comment by Ratangulati** [comment]
I can do it but everyone has to sync to the clone, they have to copy & paste their code to the new clone and start working on it as all the code remains same but the code of App.jsx will be moved under home page.
I think it is better to do it now before it becomes cluttered.

OR 
we can create pages for other routes and let home page code remain in APP.jsx and when we are done with APP.jsx we can just shift it to the new folder as no one or a few will be working on it at that time.

**Comment by Ratangulati** [comment]
Should I create the search page?
