### ISSUE TITLE
BUG : The Hero page is not responsive as per different screen view.

### ISSUE THREAD

**Issue by alok2424** [Satyam1923/Spring-Music-Player#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The content in the hero page is not responsive for different devices. This creates bad user experience ,so it is necessary to improves the responsiveness of hero page.

https://github.com/Satyam1923/Spring-Music-Player/assets/130597958/09fb6c52-2bf6-4dce-a37b-561a3e789888

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
already being handled.
