### ISSUE TITLE
Add "About Us" and "Contact Us" PagesFeat:

### ISSUE THREAD

**Issue by srivastav2006** [Satyam1923/Spring-Music-Player#152]
### Describe the feature

We need to add two new pages to the project: "About Us" and "Contact Us". These pages are essential for providing information about our organization and for users to get in touch with us.

About Us Page:

Provide a brief history of the organization.
Include the mission statement and vision.
List the team members with their roles and a short bio.
Add any relevant images or media.

Contact Us Page:

Include a contact form for users to send messages directly.
Provide an email address for direct contact.
List the physical address and a map if applicable.
Add phone numbers and office hours.

Benefits

Enhances user engagement by providing more information about our organization.
Facilitates better communication with users and stakeholders.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/143505484/f3bac0ae-469c-407b-8bf7-3b0359958582)

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/143505484/0d31d58b-2978-42d4-8250-29627e6e8f02)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@srivastav2006 nice idea you can work on it. But first show me sample design.
