### ISSUE TITLE
BUG: Alignment issue

### ISSUE THREAD

**Issue by Aanyaa26** [Satyam1923/Spring-Music-Player#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/128315909/7b2498a4-45cd-4c26-b8c9-33010a8cb848)
the buttons must have proper space and alignment which will make it look professional and at the same time effective!

Please assign me this task!
This will be my first contribution in GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@Aanyaa26 can u give preview of that

**Comment by Aanyaa26** [comment]
@saurabhsingh720 
![WhatsApp Image 2024-05-26 at 21 03 54_41ad0437](https://github.com/Satyam1923/Spring-Music-Player/assets/128315909/1f413889-dde3-44f1-a5fa-4501d8c38dec)
Somewhat like this (the CSS will be according to the theme)
As if now it is looking quite clustered which should be aligned properly!!

**Comment by saurabhsingh720** [comment]
@Aanyaa26 do it but u have to maintain the color that is matching the ui

**Comment by Aanyaa26** [comment]
Sure @saurabhsingh720
