### ISSUE TITLE
Feat: Dockerfile

### ISSUE THREAD

**Issue by Ratangulati** [Satyam1923/Spring-Music-Player#157]
### Describe the feature

I would like to create a Dockerfile for the project. Using docker it will be easy to gain access to the project and it can be done in fewer commands.
I would also be creating the documentation for it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Ratangulati fine but elaborate it more because i  have no expertise in docker.

**Comment by agarwalhimanshugaya** [comment]
sir  i want to work on this issue i have done lot of works in devops field and also i implemented docker in mern project kindly give me update regarding this issue i will complete this issue surely on less time 

kindly assign me this issue under Gssoc '24
