### ISSUE TITLE
issue in search bar css

### ISSUE THREAD

**Issue by kartikmehta18** [Satyam1923/Spring-Music-Player#163]
i want to change css of search button and search songs color not visible
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/125860170/45b0db2d-89b8-4338-a26c-560ecc8549e6)

**Comment by GauriGA** [comment]
@Satyam1923 Can you please assign this issue to me under the GSSOC'24 label?

**Comment by GauriGA** [comment]
@Satyam1923 Can you assign me an issue?
