### ISSUE TITLE
Improving the UI of the right Menu

### ISSUE THREAD

**Issue by Dhruv-Gaba** [Satyam1923/Spring-Music-Player#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
The Right menu is highly unorganized with several components overlapping and improper spacing between the elements. i would like to resolve the issue and would beautify the section.

### Currently
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/141745373/61089e07-611e-45d3-a34a-b5c5647de26c)

### Expected 
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/141745373/a90da053-4e48-4ce6-8413-60a604eb4b97)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@Dhruv-Gaba Go on
But don't remove the gif.
