### ISSUE TITLE
Designing A Logo For Spring Music Player

### ISSUE THREAD

**Issue by MehtabAsHellic** [Satyam1923/Spring-Music-Player#167]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by Satyam1923** [comment]
@MehtabAsHellic to be honest I am still in a process of designing the ui and I don't find current theme scheme good . So if you could suggest some good ideas we can make a logo.

**Comment by Anushaedubilli** [comment]
Hii  @Satyam1923 
 Iam interested in contributing to your project as a part of my GSSOC 24', I have been following your work and I'm also interested to learn react and Java script . I would like to do this project can you please assign this task to me.

**Comment by Satyam1923** [comment]
@MehtabAsHellic just design the logo i'll design the main theme than we can make login page setting page etc.

**Comment by Anushaedubilli** [comment]
Okay thank you for assigning this project

**Comment by MehtabAsHellic** [comment]
> @MehtabAsHellic just design the logo i'll design the main theme than we can make login page setting page etc.

ok

**Comment by Satyam1923** [comment]
Any progress

**Comment by MehtabAsHellic** [comment]
> Any progress

really sorry for being delayed as my university is going on, I will share a sample by tomorrow for sure 
@Satyam1923 hope you understand

**Comment by MehtabAsHellic** [comment]
![Logo2](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/88ab8d81-de19-4a65-9748-ea0d40001968)
![Logo1](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/a483dc59-15dc-4873-ab40-4cf99f20255f)

@Satyam1923  Please provide you suggestion if any because we can iterate design and make more toward your requirement too.

**Comment by Satyam1923** [comment]
@MehtabAsHellic I was thinking the logo could contain a flower which would relate to spring. If you could implement this.

**Comment by MehtabAsHellic** [comment]
> ![Screenshot 2024-05-30 121053](https://private-user-images.githubusercontent.com/104068640/335068894-44fbc5e8-2209-4c6a-bc10-357c2b9eaa2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTE3NTIsIm5iZiI6MTcxNzA1MTQ1MiwicGF0aCI6Ii8xMDQwNjg2NDAvMzM1MDY4ODk0LTQ0ZmJjNWU4LTIyMDktNGM2YS1iYzEwLTM1N2MyYjllYWEyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwNjQ0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2U1MjkxNmFjNzJjODM0MWFmMjMwMDNiZGUwNzJjMzFkODIxZjBkOGM4YjJmZTI2ZDFiNjBlMTZkZTk2ZTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sUJ74paFz4oZ0OFSMGVucJnCaiHejsP1VAWcg6wmCPU) @MehtabAsHellic I was thinking the logo could contain a flower which would relate to spring. If you could implement this.

ok

**Comment by MehtabAsHellic** [comment]
![Logo](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/430ad7bb-71ff-4399-82c1-12c9492e6445)

**@Satyam1923  Let me know your thought here.**

**Comment by Satyam1923** [comment]
Something like 2 3 6 8 9 flower style would be fine.

**Comment by MehtabAsHellic** [comment]
![Design4](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/0f61a993-438e-4f12-902e-87a4ca914141)
![Design3](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/fb992f8c-7364-4d7c-be77-fc9bebee8cbf)
![Design2](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/025f3cc1-f724-4c5e-9619-f79906f97301)
![Design1](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/92328bca-4621-41a7-97b4-b81ab79505ad)

**@Satyam1923  Let me know your thought here.**

**Comment by Satyam1923** [comment]
@MehtabAsHellic didn't like it.

**Comment by me-shweta** [comment]
@Satyam1923 Should I give it a try? I have some good ideas in my mind. I'll wait for 3 days until @MehtabAsHellic is doing this, otherwise, give me a chance for this task.

**Comment by MehtabAsHellic** [comment]
> @MehtabAsHellic didn't like it seems like a billboard of any company. Leave this flower design go with something S or Music related logo but don't use that basic logo.

ok

**Comment by lovelymahor** [comment]
@Satyam1923, can I try the logo? I also have some ideas.

**Comment by MehtabAsHellic** [comment]
@Satyam1923 

![spring](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/29fd5c75-498d-40f9-9609-b6122b8af8b2)

just a approach with play with colors and all later let me know your thoughts

**Comment by Satyam1923** [comment]
@lovelymahor ya you can. points will be given to person who creates the issue.

**Comment by Satyam1923** [comment]
@MehtabAsHellic Don't write whole name Spring. This one seems good.

**Comment by MehtabAsHellic** [comment]
![Screenshot 2024-06-03 192814](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/e09f62d2-8c31-401e-bae1-c49a71f3117a)

any your need of color or shade as i cam thinking to keep it simple solid colors

**Comment by MehtabAsHellic** [comment]
![Screenshot 2024-06-03 194157](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/940fcaf8-3cff-4b90-8e8a-f7e6e76a0890)
![Screenshot 2024-06-03 194111](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/f6423615-a4eb-4dc3-a910-94f0835272e8)

**Comment by MehtabAsHellic** [comment]
ok

**Comment by MehtabAsHellic** [comment]
![Screenshot 2024-06-03 195547](https://github.com/Satyam1923/Spring-Music-Player/assets/101495398/96aa5e50-c665-4aa5-8bda-5ac0574a3819)

some last color combinations related to music colors @Satyam1923

**Comment by Satyam1923** [comment]
@MehtabAsHellic start something fresh.

**Comment by me-shweta** [comment]
@Satyam1923 Can I also create some designs?

**Comment by MehtabAsHellic** [comment]
> @MehtabAsHellic start something fresh.

sorry do you mean by color of this logo or completely new design ? @Satyam1923

**Comment by Satyam1923** [comment]
@MehtabAsHellic complete new design.

**Comment by Satyam1923** [comment]
> @Satyam1923 Can I also create some designs?

You can.

**Comment by me-shweta** [comment]
**@Satyam1923 I have created some designs. Here they are.**
![1](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/e85b2ae9-3582-4e73-ae8b-ee7803d8407a)
![2](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/14362ec2-630f-42c0-bf2d-f5438db67bb0)
**Let me know which design suits you best and if there are any changes you would like to make.
Is there any tagline for Spring?**

**Comment by me-shweta** [comment]
@Satyam1923 any update??

**Comment by Satyam1923** [comment]
@me-shweta No didn't liked it.

**Comment by me-shweta** [comment]
**@Satyam1923 I have created some designs. Here they are.**
![logo18](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/d1b757b1-b696-41a1-a4ec-e02c7c65d6ae)
![logo22](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/b21e29fe-5038-43cb-be2c-00d42f0b7778)
![logo23](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/01ff3336-023d-4b4d-9bbb-db66a54cad7b)
![logo24](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/2a5882b6-8c54-4341-90ec-62f123709d30)
![logo16](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/5bf2be77-9a47-4ebf-9dd1-5a2d3d158759)
![logo17](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/b0f31d4b-98eb-403e-a24c-962029b6551a)
![logo19](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/44e63fd2-5c5f-4b41-9e37-75d24df8e2ea)
![logo20](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/ba8ce4e3-9563-4de0-8f0c-d36842c01106)
![logo21](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/150469f5-78c4-4f9e-a289-c1f1df6e7f23)
![logo5](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/885e8002-7004-469d-adef-39775312c980)
![logo6](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/115f942d-f234-4e50-b5ae-0321611bd6a3)
![logo26](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/f3867278-3611-4e6e-8554-e76ad72498b3)
![logo10](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/968be7a8-ef61-4791-a36c-cd92aec9feb9)
![logo9](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/ebd9eb14-729c-4b80-aa3e-17324be4f3f2)
![logo11](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/264cfb27-8e07-44cc-b277-a10c2fa1f5c3)
![logo1](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/7ef70130-524d-4a60-be0e-bf1a375a1829)
![logo2](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/6648870c-4f94-4a7e-a394-514dc7a35e9b)
![logo3](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/1f6027f7-adf1-417f-8553-58e029eb0efa)
![logo4](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/7333a03c-ae3c-437c-8460-bc56a9ac7ed6)
![logo8](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/cf1d6072-fea6-4510-8491-1bc1e6ab74c9)
![logo25](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/46f47137-44f9-46cb-b472-22655b6a1378)
![logo12](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/520b28c4-e10d-4f5b-9cd4-6ca82706050b)
![logo13](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/810c757c-8825-4555-a632-8a52f4f1f76d)
![logo14](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/467f7069-3a0b-4e0a-a623-ee0abf4e958d)
![logo27](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/7e137944-818f-4b74-b5bb-ba8f2621dfd9)
![logo15](https://github.com/Satyam1923/Spring-Music-Player/assets/119609866/bf56a2d7-a2d5-4c83-bb21-e0c8f84b7207)

**Comment by me-shweta** [comment]
@Satyam1923 Let me know which design suits you best.

**Comment by Satyam1923** [comment]
![337367364-46f47137-44f9-46cb-b472-22655b6a1378](https://github.com/Satyam1923/Spring-Music-Player/assets/104068640/10310618-08f9-45ef-8890-6e32df776ca4)
![337367285-ebd9eb14-729c-4b80-aa3e-17324be4f3f2](https://github.com/Satyam1923/Spring-Music-Player/assets/104068640/ac56965a-de4b-4242-a2a1-3293616f0d87)
these two I guess.

**Comment by Satyam1923** [comment]
if possible provide the vector file for this logo.

**Comment by me-shweta** [comment]
@Satyam1923 What changes do you need to make to this design?

**Comment by Satyam1923** [comment]
@me-shweta Changes are not need just provide the vectorise figma design file. I'll check with different color combinations.

**Comment by me-shweta** [comment]
@Satyam1923 Okay... will send you in some time.
Also, Assign me this task first, otherwise this contribution won't be counted.

**Comment by me-shweta** [comment]
@Satyam1923 Actually, I created this design using AI, so it can't be changed further. I can try changing the prompt, but I'm not sure it will produce the same result.

**Comment by Satyam1923** [comment]
@me-shweta don't change the design vectorize the design in figma? google about it

**Comment by me-shweta** [comment]
@Satyam1923 I have made the vector file. Please send your email so I can share the link.

**Comment by Satyam1923** [comment]
@me-shweta fine

**Comment by me-shweta** [comment]
@Satyam1923 
[https://www.figma.com/design/vqS4ia2uZvQmd3gUUJKlvA/SPRING-ICON?t=SznRZmREXw0Nq4So-1](url)

**Comment by me-shweta** [comment]
@Satyam1923 Are you able to access the file?

**Comment by Satyam1923** [comment]
@me-shweta not able to access.

**Comment by me-shweta** [comment]
@Satyam1923 this is the updated link 
[https://www.figma.com/design/vqS4ia2uZvQmd3gUUJKlvA/SPRING-ICON?node-id=0-1&t=XQ83D9WnshPJrpIm-1](url)

When you get access, please inform me so that I won't allow anyone other than you to edit this file.

**Comment by me-shweta** [comment]
@Satyam1923 reply ?

**Comment by Satyam1923** [comment]
@me-shweta I'll fix wait.

**Comment by me-shweta** [comment]
@Satyam1923 there is an image from scratch which you can edit, adjusting elements and their colors as needed.

**Comment by me-shweta** [comment]
@Satyam1923 any update?
