### ISSUE TITLE
SONG STARTS PLAYING AUTOMATICALLY

### ISSUE THREAD

**Issue by AYUSHMAN777** [Satyam1923/Spring-Music-Player#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot (268)](https://github.com/Satyam1923/Spring-Music-Player/assets/110350591/48276a18-6b6d-4c92-b363-5492ed3c6285)
When I search for a song, it automatically starts playing without my selection or click, leading to a subpar user interface. I can enhance this feature, please assign me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@AYUSHMAN777  do it asap

**Comment by Anushaedubilli** [comment]
Hii @Satyam1923 
Iam interested to do this project Could you please assign this task to me.
