### ISSUE TITLE
Search Logo

### ISSUE THREAD

**Issue by AYUSHMAN777** [Satyam1923/Spring-Music-Player#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot (269)](https://github.com/Satyam1923/Spring-Music-Player/assets/110350591/3ca139a9-aba8-4da2-8764-7a4ec430f9dd)
Sir, the search logo is located outside and the background color does not match the expected design. There are also other issues in the UI, such as the top artist padding and much more . Please assign me to improve your UI.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@AYUSHMAN777 
Give me the preview of inhanced UI
