### ISSUE TITLE
BUG: Playlist ui delete icon

### ISSUE THREAD

**Issue by dhruv8433** [Satyam1923/Spring-Music-Player#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Satyam1923 

check this out
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/40546bde-bc95-4105-b67b-f0b4eae974bf)

the delete icons shown in center insted we can display it at the end of hover effect (right side)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khushi0204** [comment]
I want to work on this issue please assign this to me under gssoc
