### ISSUE TITLE
Feat: Make it responsive

### ISSUE THREAD

**Issue by dhruv8433** [Satyam1923/Spring-Music-Player#186]
### Describe the feature

@Satyam1923 

when i  try to open this web in responsive screen, the design of whole page is changed
we can make it responsive with the help of grid layoyt

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/4373a50b-357e-4bcb-948d-7b8a702e1706)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.
