### ISSUE TITLE
Feat: Redux toolkit

### ISSUE THREAD

**Issue by Sid-80** [Satyam1923/Spring-Music-Player#187]
### Describe the feature

I am willing to add the redux toolkit for state management in the application.

### Add ScreenShots

No screenshots needed

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
fine.
