### ISSUE TITLE
Search song input and search song icon not properly aligned

### ISSUE THREAD

**Issue by vanisharma2003** [Satyam1923/Spring-Music-Player#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![WhatsApp Image 2024-05-26 at 14 35 03_b919cb3d](https://github.com/Satyam1923/Spring-Music-Player/assets/137780818/061c2003-9f6f-4c5c-a492-35ba00afc45f)
see here search icon and search input not properly aligned. This does not give a clean look at all. To enhance the look of the website it should be changed.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@vanisharma2003 do this asap.

**Comment by vanisharma2003** [comment]
> @vanisharma2003 do this asap.

Okiee will raise a PR very soon

**Comment by vverma022** [comment]
Could I work on this ? I have the project setup locally already
