### ISSUE TITLE
BUG: Not Able to add songs in the for creating a customise playlist.

### ISSUE THREAD

**Issue by Bhagat-Nidhi** [Satyam1923/Spring-Music-Player#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While trying adding songs for a playlist , there is no option to add songs in the playlist.
I have tried restarting the website but the issue persist.

Please assign the issue to me I would like to contribute in this.
I've read the code of conduxt and I'm a GSSOC'24 contibutor.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
You can work on it.

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
