### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Priti9075** [Satyam1923/Spring-Music-Player#203]
### What's wrong with the existing documentation

The website currently lacks artist and song information. I'd be thrilled to add this functionality and enrich the user experience. please assign me this issue under Gsoc'24

### Add ScreenShots

![Screenshot (266)](https://github.com/Satyam1923/Spring-Music-Player/assets/113301439/49f66233-8277-4e3b-bc2d-f42adef32bc5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
