### ISSUE TITLE
DOC:

### ISSUE THREAD

**Issue by Priti9075** [Satyam1923/Spring-Music-Player#204]
### What's wrong with the existing documentation

There appears to be a misalignment between the search icon and search box. Additionally, the search icon's size seems larger than optimal. please assign me this issue under Gsoc'2024

### Add ScreenShots

![Screenshot (266)](https://github.com/Satyam1923/Spring-Music-Player/assets/113301439/33c0b7b8-9a27-4cb6-8b25-a305eb93450d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
