### ISSUE TITLE
Feat: Redesigning the whole website according to the figma template given

### ISSUE THREAD

**Issue by Yash-Ainapure** [Satyam1923/Spring-Music-Player#205]
### Describe the feature

I will Redesign the whole website as per the Figma template given in Readme file

also would fix some small bugs ,validations, and overall User experience of the website

please assign me this issue so that i could get an assurance from the owner to start the work.

### Add ScreenShots

the figma link:
https://www.figma.com/design/WQnt0qRFSdaV3jW5XF8NSc/Spring-Music-player-new-design

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
You can work on it.

**Comment by Yash-Ainapure** [comment]
@Satyam1923 ,the website isn't working ,is something problem/bug or it wasn't working from previous ?


https://github.com/Satyam1923/Spring-Music-Player/assets/136250383/780ea441-ea75-43e7-ac2d-b8d997bb9d07

**Comment by Satyam1923** [comment]
@Yash-Ainapure currently it's not working

**Comment by Yash-Ainapure** [comment]
@Satyam1923 
I have made it working and changed some styling of it.
Should i make a pr now so it would be better for further contributions?
if i made a pr of whole with all changes there are some chances of getting merge conflicts

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/136250383/371fe002-e803-4b75-bc15-423c5c65b69e)

**Comment by Satyam1923** [comment]
Change the background of the center part also. If possible

**Comment by Yash-Ainapure** [comment]
> Change the background of the center part also. If possible

Yup,will be making it like a spotify clone.
my question was:
Should i make a pr now so it would be better for further contributions?
if i made a pr of whole with all changes there are some chances of getting merge conflicts

**Comment by Yash-Ainapure** [comment]
@Satyam1923 
Thanks for merging this PR.
I have a doubt ,should i raise a new PR for Redesing the whole website according to figma template
Actually i was gonna do it in this issue,the the problem i got was the website wasn't working properly so that's why I had to solve it before coming to UI part
