### ISSUE TITLE
Feat: Adding the Login and Sign-Up functionality

### ISSUE THREAD

**Issue by ParthNakum21** [Satyam1923/Spring-Music-Player#207]
### Describe the feature

I'm interested in contributing to the project by adding the login and sign-up functionality. 

Could you please assign this task to me under GSSoC with appropriate level?

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/134558990/ff1ba1df-8974-41c6-9895-2d5b05736751)
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/134558990/e8dfba17-d558-46c6-b06e-61b8634ec8ec)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@ParthNakum21 you can work on it . 
fix the current login pages and use firebase for login functionality.

**Comment by Annu117** [comment]
Why the signup page is designed differently from the rest of the pages? The black theme will suit, with similar effects.

**Comment by Satyam1923** [comment]
@Annu117 we i'll be having both dark and light mode.

**Comment by Annu117** [comment]
The theme isn't matching. Even if it is in light mode. It is designed way too differently.

**Comment by Annu117** [comment]
Yes, surely.

**Comment by Annu117** [comment]
And can develop it, too; the other person can do Firebase backend linking.
It might happen that the same design is not developed so directly develop it.
As for now, I have been assigned other issue in the same project, so the @ParthNakum21 can keep the element doing the backend for now. once I am done can design this page.

Or can work on this alone too. Just said as this issue wasn't raised by me.

**Comment by ParthNakum21** [comment]
I am designing and developing the login and signup pages to maintain a consistent theme across all pages, handling both the design and Firebase backend integration. I have considered your points and will ensure they are met. Once I'm done, @Annu117 can raise an issue and enhance the UI if needed.

**Comment by Gokilp** [comment]
Any one issue working now

**Comment by ParthNakum21** [comment]
> Any one issue working now

I am working on this issue; I will open it once I'm done with the changes.
