### ISSUE TITLE
BUG: Misaligned Search Icon in Song Search UI

### ISSUE THREAD

**Issue by HarsikaKumari** [Satyam1923/Spring-Music-Player#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The search icon in the Song Search UI is misaligned with the input field, causing a visual inconsistency that could potentially affect the user experience. I propose to investigate and resolve this issue by adjusting the relevant CSS styles or positioning of the icon element, leveraging my experience in front-end development, and addressing UI/UX concerns.

![Screenshot 2024-05-29 121407](https://github.com/Satyam1923/Spring-Music-Player/assets/147150204/08c542d1-5589-47f5-9321-70ce44123425)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarsikaKumari** [comment]
@Satyam1923 Please assign me this issue under GSSoC'24.

**Comment by Satyam1923** [comment]
duplicate
