### ISSUE TITLE
Designing Login, Signup page and User Profile page in Figma

### ISSUE THREAD

**Issue by Prithwi32** [Satyam1923/Spring-Music-Player#21]
**Is your feature request related to a problem? Please describe.**
As Developer need Figma file to achieve rapid development, It's necessary to design Figma Prototype

**Describe the solution you'd like**
I would like to add corresponding page designs in Figma

**Comment by Prithwi32** [comment]
@Satyam1923 Please could you assign me this issue under GSSoC'24

**Comment by atharvmalve** [comment]
Hello! @Satyam1923,  I noticed there's an open issue for designing the login page in Figma, and I'd like to collaborate on it. With my past experience in designing components for our application, I believe I can contribute effectively to this task. I'm ready to collaborate with @Prithwi32 who has initiated the issue to ensure that we create a login page that aligns perfectly with our application's design principles and user experience goals. Please consider assigning this task to me. Thank you!

**Comment by Satyam1923** [comment]
@Prithwi32 Some part of figma design I have already designed you can start working on it. 
Don't change the initial look of it. 
You can work with @atharvmalve  he already has the edit access I'll add you to it .

**Comment by Prithwi32** [comment]
> @Prithwi32 Some part of figma design I have already designed you can start working on it. Don't change the initial look of it. You can work with @atharvmalve he already has the edit access I'll add you to it .

okay

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Thank you! 🚀

**Comment by Satyam1923** [comment]
@IP80808080 two people are enough for now!

**Comment by Muskansahuincredible** [comment]
PLEASE ASSIGN ME THIS ISSUE I WILL REALLY WORK HARD ON IT

**Comment by Gsha36** [comment]
Hello! I have experience with Figma and user experience. You can assign me this issue.

**Comment by Satyam1923** [comment]
@Prithwi32 make a pr with this issue sending design link and explaining your work then I'll close this issue.
