### ISSUE TITLE
BUG: Buttons not functional

### ISSUE THREAD

**Issue by karishmaaa101** [Satyam1923/Spring-Music-Player#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The buttons on the navbar are not working.

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/104766763/e3257006-1d86-4143-884c-bee2552ba6c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@karishmaaa101 
Now some are working.
U can check the present changes done in the project then request your issue.

**Comment by karishmaaa101** [comment]
Yes the setting icon works,but the remaining two are still not working.
