### ISSUE TITLE
BUG: Bug: Alignment issue of the search bar and the search button

### ISSUE THREAD

**Issue by theeayushkumar** [Satyam1923/Spring-Music-Player#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The search bar is very close and is touching the search button.

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/128235540/2cf28954-0000-4a5c-8f59-ce7ddc847e3c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@theeayushkumar
