### ISSUE TITLE
BUG: Unable to Delete Playlist

### ISSUE THREAD

**Issue by suryapratapsingh26** [Satyam1923/Spring-Music-Player#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After clicking the  (delete) button next to a playlist , the playlist is not actually being deleted. Despite clicking the delete button, the playlist remains unchanged, indicating a malfunction in the delete functionality.

https://github.com/Satyam1923/Spring-Music-Player/assets/146753809/7edfec9e-6848-46d0-9005-9b96a659f4fc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
firstly we need to implement playlist.

**Comment by suryapratapsingh26** [comment]
1 want to work on the implementation of playlist. Assign me @Satyam1923
