### ISSUE TITLE
some songs are not playing

### ISSUE THREAD

**Issue by u-s-h-a** [Satyam1923/Spring-Music-Player#22]

**Comment by Satyam1923** [comment]
can you please elaborated this issue with some kind of reference video etc.

**Comment by u-s-h-a** [comment]
Ya sure

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by Satyam1923** [comment]
@u-s-h-a I dont see any response from your side could you please clear it otherwise I'll assign it to someone else.
