### ISSUE TITLE
Feat: Redesigning Whole website according to figma template given

### ISSUE THREAD

**Issue by Yash-Ainapure** [Satyam1923/Spring-Music-Player#222]
### Describe the feature

I will Redesign the whole website as per the Figma template given in Readme file

also would fix some small bugs ,validations, and overall User experience of the website
Also I would add react-router for all pages present in sidebar

please assign me this issue so that i could get an assurance from the owner to start the work.

### Add ScreenShots

the figma link:
https://www.figma.com/design/WQnt0qRFSdaV3jW5XF8NSc/Spring-Music-player-new-design

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Yash-Ainapure you can work on it.

**Comment by Yash-Ainapure** [comment]
@Satyam1923 
## I have made it till here now 
- Any Suggestions?
 Many more things has to be done yet

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/136250383/0f8f9084-36f9-4444-bd14-a056f7517250)

**Comment by Satyam1923** [comment]
ya seems fine just need more changes.

**Comment by Annu117** [comment]
@Yash-Ainapure, do not make changes in the sidebar. There will be merging conflicts

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure, do not make changes in the sidebar. There will be merging conflicts

Sorry ,but as you can see in the screenshot I have already made it 🥲
Are you working on it?

**Comment by Annu117** [comment]
yes, I am working on it. Ok but don't do further changes.

**Comment by Yash-Ainapure** [comment]
@Satyam1923 ,please review it
