### ISSUE TITLE
[FEAT] Implement the Notification Box

### ISSUE THREAD

**Issue by yashmandi** [Satyam1923/Spring-Music-Player#226]
### Describe the feature

On clicking or hoverin on notification icon, a small notification block should appear which should display all the notifications to the user.
I would like to work on this feature under GSSoC, request you to assign this task to me

### Add ScreenShots

similar to this: 
![notification](https://github.com/Satyam1923/Spring-Music-Player/assets/132436131/06d0fdf4-cee1-43cf-908f-fa5f69255372)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@yashmandi 
U have to complete asap.

**Comment by lovelymahor** [comment]
I would like to work on this issue Can u please assign me this issue?
