### ISSUE TITLE
Adding Volume regulator 

### ISSUE THREAD

**Issue by Jagpreet153** [Satyam1923/Spring-Music-Player#23]
**Is your feature request related to a problem? Please describe.**
Yes it fixes the problem of user they have to face while listening to songs

**Describe the solution you'd like**
I would like to add volume regulator button to adjust the volume of songs according to users' choice

Please assign this task to me under GSSoc'24

**Comment by Satyam1923** [comment]
@Jagpreet153 you want to currently work on it. Since current fronted is based on ejs or after it is shifted to reactjs

**Comment by Jagpreet153** [comment]
Ok @Satyam1923 Kindly assign this to me after the frontend is switched to Reactjs

**Comment by Satyam1923** [comment]
fine~

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me?  Thank you! 🚀

**Comment by abhiperfect** [comment]
Subject: Request to Add Volume Regulator in EJS

Dear @Satyam1923  ,

I hope you're doing well. I'm writing to request permission to add a volume regulator feature to our EJS-based application. This addition will enhance user experience by allowing them to control the volume of audio or video content directly from the interface.

The volume regulator will be implemented using HTML5 `<input type="range">` element, and its functionality will be integrated with JavaScript to adjust the volume dynamically.

I will ensure that the volume regulator is seamlessly integrated into the existing EJS templates and that it maintains compatibility across different browsers and devices.

Please let me know if you approve this request or if there are any specific guidelines or considerations I should adhere to while implementing the volume regulator feature.


Best regards,
Abhishek

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.
