### ISSUE TITLE
BUG: Signin and signup page linking

### ISSUE THREAD

**Issue by Annu117** [Satyam1923/Spring-Music-Player#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Signin and signup pages are already built but are not linked on the home screen. 
The UI looks good but needs to be modified to match the current theme.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@Annu117 
Can u give the overview about UI that u have modified.

**Comment by Annu117** [comment]
I have not modified but I want to modify it.
 #195 In this PR, sign-in and signup pages are built. I want to work on this instead of creating new as the design looks good. But not it's matching the theme.

**Comment by Satyam1923** [comment]
@Annu117 problem is the backend for firebase if you can handle that it will be linked rest is no use.

**Comment by Annu117** [comment]
Also, #207 seems to be not completed. I would like to design and link both.

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
