### ISSUE TITLE
Design top artists and  top charts section

### ISSUE THREAD

**Issue by paulkrishanu4** [Satyam1923/Spring-Music-Player#231]
### Describe the feature

want to design the top chart section accortding to figma design

### Add ScreenShots

![Screenshot_1-6-2024_225529_private-user-images githubusercontent com](https://github.com/Satyam1923/Spring-Music-Player/assets/169196836/ceef89a7-9038-4259-95cf-aedc04c99612)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@paulkrishanu4  do it
After completing the task  add a screenshot that u have made in the project or a short video.

**Comment by Yash-Ainapure** [comment]
@saurabhsingh720 @paulkrishanu4 , I am already doing this task in #232 
and already completed most of the things
