### ISSUE TITLE
Playback Controls

### ISSUE THREAD

**Issue by lovelymahor** [Satyam1923/Spring-Music-Player#233]
### Is there an existing issue for this?

[X] I have searched for existing issues

### What happened?

Playback Controls like Play, pause, skip, rewind, and Repeat have functionality.
Please assign this issue to me. I want to work on it

### Record

- [X] I agree to follow this project's Code of Conduct
-  [X] I have checked the existing issues. (https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@lovelymahor 
Do it asap.

**Comment by saurabhsingh720** [comment]
@lovelymahor 
Have u done the task??

**Comment by lovelymahor** [comment]
yes, working
