### ISSUE TITLE
Feature : Adding Slider to Top Artist and enhancing it

### ISSUE THREAD

**Issue by richab246** [Satyam1923/Spring-Music-Player#236]
### Describe the feature

We need to add a slider to the "Top Artist" component to enhance its functionality and user experience. The slider will allow users to smoothly navigate through a list of top artists, making the component more interactive and user-friendly.

### Add ScreenShots

![Screenshot 2024-06-02 112224](https://github.com/Satyam1923/Spring-Music-Player/assets/79681567/050dfbab-cdc8-43b6-a02c-05d0ad54189f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@richab246 you can work on it. But after @The-Phoenics completes his part.
