### ISSUE TITLE
Feature : Working on Genres as per the figma design

### ISSUE THREAD

**Issue by richab246** [Satyam1923/Spring-Music-Player#237]
### Describe the feature

Develop the Genres component according to the design specified in the Figma file. Ensure it matches the layout, style, and functionality as detailed.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/79681567/35acbd81-6868-4189-9f4c-8a3174ee6bc1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
You can work on it. Just be updated about the latest merged PRs.

**Comment by Yash-Ainapure** [comment]
@Satyam1923 , I am working in this issue and completed more than half of the work,
please see #222  for reference video

**Comment by Satyam1923** [comment]
@Yash-Ainapure fine since you are doing it. You can complete it and later on she can  make improvementt if needed.
