### ISSUE TITLE
Adding Recommended Songs or artist section

### ISSUE THREAD

**Issue by ayushnegi007** [Satyam1923/Spring-Music-Player#239]
### Describe the feature

i will add a section were users can see recommended songs or artist 

### Add ScreenShots

![Screenshot (64)](https://github.com/Satyam1923/Spring-Music-Player/assets/106025967/cf81376b-6a7e-462f-8bf4-233e41beae8c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
you want to work on the frontend section or backend.

**Comment by ayushnegi007** [comment]
I would like to work on frontend section

**Comment by minakshikr7** [comment]
Please assign me this issue under @GSS0C24
