### ISSUE TITLE
Visualizer : Synced with song

### ISSUE THREAD

**Issue by Sushanth-Hebri** [Satyam1923/Spring-Music-Player#24]
Hey @Satyam1923,

Your project is amazing! I think we can take the music player to the next level by adding a visualizer. I've had experience working on a full-stack music player project where I implemented a visualizer, and it was a hit.

Your Figma plans look fantastic and provide a great starting point for enhancing the player's visual appeal.

Could you please assign me the task of making the player more visually appealing? I'm excited about the possibilities!

**_Visualizer : Synced with song_**
![Screenshot 2023-09-04 111901](https://github.com/Satyam1923/Spring-Music-Player/assets/117469085/9d929179-b726-4136-ae5d-a64e63dbb043)
![Screenshot 2023-12-24 013145](https://github.com/Satyam1923/Spring-Music-Player/assets/117469085/aab9baf5-11ae-419d-9dee-3afb1dc5e394)

**Comment by Sushanth-Hebri** [comment]
I attached my previous works to consider me for this task ❤️

**Comment by Satyam1923** [comment]
@Sushanth-Hebri As i personally don't prepare visualizer that much. So could please attached an idea with my ui , how and where are you go going to implement visualizer.

**Comment by Sushanth-Hebri** [comment]
ok , sure

**Comment by Sushanth-Hebri** [comment]
visualizer is better to be placed behind the banner (thumbnail) of the song, as user focuses on that only , he can really feel the song.
I have attached two possibilities (made in canva) ,
Let me know your opinion 🚀❤️


![Untitled design (5)](https://github.com/Satyam1923/Spring-Music-Player/assets/117469085/1b9b8349-4e87-4ee0-bd5c-c5949eb6f7dc)
![Untitled design (4)](https://github.com/Satyam1923/Spring-Music-Player/assets/117469085/1c020eac-001b-4063-b858-a9e83f33e1d6)

**Comment by Satyam1923** [comment]
wait i'll share you the latest design that we have came across https://www.figma.com/design/mrTzLDEAtHPOsDl99R3kOY/Spring-Music-Player?node-id=0%3A1&t=ZmNemohz1KILUSBt-1

**Comment by Sushanth-Hebri** [comment]
Ok , i gone through your figma design , 
**attached 2 designs , (changes are possible)**

we can place or integrate visualizer anywhere

![Screenshot 2024-05-10 173029](https://github.com/Satyam1923/Spring-Music-Player/assets/117469085/5e3e0bf1-4617-45dd-8fd2-71bfe7322deb)
![Screenshot 2024-05-10 173018](https://github.com/Satyam1923/Spring-Music-Player/assets/117469085/895e96d5-e08d-4ff7-b0b6-6ecd9cee7c8a)

**Comment by Satyam1923** [comment]
Sorry but I dont't prefer these kind of design

**Comment by Sushanth-Hebri** [comment]
Ok
