### ISSUE TITLE
Feat:Enable the search option for the users

### ISSUE THREAD

**Issue by RahulRudra81** [Satyam1923/Spring-Music-Player#240]
### Describe the feature

I can implement the search feature for the users so that users can search for a particular song using the search bar in the homescreen. There are few changes I have to do with the backend url and how the query is handled in the if else statement then i am good to go. Please add the label of gssoc so the contribution can be counted.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/91683510/63edc1d0-99ad-4451-b7fb-84b586494b8a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
How exactly is it different from the one we are currently using.
