### ISSUE TITLE
Feat:Implement theme(dark or light)  in nav bar

### ISSUE THREAD

**Issue by ksatya2003** [Satyam1923/Spring-Music-Player#241]
### Describe the feature

Implement theme(dark or light)  in nav bar

### Add ScreenShots

https://tse3.mm.bing.net/th?id=OIP.6PVf7FIhNR2d9VkxBitPugHaEK&pid=Api&P=0&h=180

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
Duplicate.

**Comment by ksatya2003** [comment]
is this feature already implemented in this?

**Comment by Satyam1923** [comment]
No but someone already working on it

**Comment by ksatya2003** [comment]
ok
