### ISSUE TITLE
Feat: Home page ui 

### ISSUE THREAD

**Issue by mukilan2815** [Satyam1923/Spring-Music-Player#242]
### Describe the feature

I can make the home page like this and i will add some api and add recently player or suggested songs in home screen

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/71129858/5cc3b0e2-519d-4d05-8aab-a04286427860)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by siddhant-2002** [comment]
i would also like to contribute to this UI I can help youu

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.

**Comment by mukilan2815** [comment]
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/71129858/f2415323-28e3-4c3a-be79-b1889295d10f)

I will design this section to figma design

**Comment by Satyam1923** [comment]
it also being handled.
