### ISSUE TITLE
Implement Authentication and Authorization

### ISSUE THREAD

**Issue by RahulRudra81** [Satyam1923/Spring-Music-Player#243]
### Describe the feature

I would like to work on the authentication and authorization features of the application. Here is my proposed approach:

**Database**:

- I am planning to use MongoDB with Mongoose for database management. I will configure the database connection and provide necessary schemas for user authentication.
- Alternatively, I can use Firebase for authentication and database management if preferred.

**Authentication:**

- Implement user registration and login functionality.
- Use JWT (JSON Web Tokens) for secure authentication.
- Secure password storage using bcrypt hashing.

**Authorization:**

- Implement role-based access control (RBAC) to manage different levels of access within the application.
- Protect routes to ensure only authenticated users can access certain resources.
- Configuration:
- 
- I will use environment variables to manage sensitive information such as database URLs and JWT secrets. You can change the URL or other configurations during the code review or before merging the pull request.

**Plan:**

- Set up MongoDB and integrate it with Mongoose.
- Create user schema and model.
- Implement registration and login routes.
- Use JWT for authentication.
- Secure routes and implement role-based access control.
- Test the implementation thoroughly.

**Questions:**

- Do you have a preference for using Firebase instead of MongoDB/Mongoose?
- Are there any specific requirements or guidelines you would like me to follow for this implementation?

**Thank you for considering my contribution. I look forward to your feedback and suggestions.**

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/91683510/3c0c2a54-21b9-4b32-85ad-09b2656262f9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@RahulRudra81 fine do with firebase.

**Comment by agarwalhimanshugaya** [comment]
what is the update if no one working on this issue please assign to me

**Comment by Satyam1923** [comment]
@RahulRudra81 what are you trying to do?

**Comment by Satyam1923** [comment]
I guess this much is fine for now.
