### ISSUE TITLE
Feat: Adding a "Premium" option

### ISSUE THREAD

**Issue by AkshitGarg24** [Satyam1923/Spring-Music-Player#244]
### Describe the feature

A "Premium" option should be made available on the website. A dedicated webpage should be created to display a comparison between the features of the "FREE" and "PRO" plans.

### Add ScreenShots

The attached video below demonstrates how the premium option webpage is displayed on Spotify.

https://github.com/Satyam1923/Spring-Music-Player/assets/153659573/e6586ee3-2270-4d58-8551-7f47cf1442c8

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@AkshitGarg24 no requirement for my side.
