### ISSUE TITLE
Feat: Implement Search page

### ISSUE THREAD

**Issue by The-Phoenics** [Satyam1923/Spring-Music-Player#249]
### Describe the feature

I would like to work on implementing the new design of `search` page.

### Add ScreenShots

![search-page](https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/a10c9740-a8e8-48c5-99c0-eea4581071f7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@The-Phoenics could now move the search bar from home page to search main page. Along with search button functionality

**Comment by The-Phoenics** [comment]
Hey @Satyam1923,
Since the routing/navigation hasn't been properly set just yet. I suggest we work on the navigation as a separate issue after all the pages have been implement by properly utlizing the `react-router-dom` package and using `useNavigate` hook.
Let me know your thoughts on this.
