### ISSUE TITLE
[Feature] Auto play and shuffle play

### ISSUE THREAD

**Issue by rahulpoonia29** [Satyam1923/Spring-Music-Player#25]
**Is your feature request related to a problem? Please describe.**
The current song is played on loop.

**Describe the solution you'd like**
It would be great if it skips to the next song once completion of the current song and adding a additional feature for playing a song on loop.

**Comment by rahulpoonia29** [comment]
@Satyam1923 I would like to work on this issue under GSsoC'24

**Comment by Satyam1923** [comment]
@rahulpoonia29 as you have raised this issue currently under index.ejs at audio tag we already have autoPlay tag included. 
So i want you to edit script.js and add code to have a loop feature with three click implement 
1. autoplay current song
2. loop  around
3. autoplay off
You can add button for it and take icons reference from hugeicons
also,
add shuffle button along with it
if you can then let me know

**Comment by rahulpoonia29** [comment]
@Satyam1923 Sure, I'll be happy to work on the issue.

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Thank you! 🚀

**Comment by Satyam1923** [comment]
@IP80808080 fine
