### ISSUE TITLE
DOC: Updating the Readme file according to latest changes

### ISSUE THREAD

**Issue by Yash-Ainapure** [Satyam1923/Spring-Music-Player#250]
### What's wrong with the existing documentation

As per the latest changes in the project ,we need to remove this part from the README.md file as it's of no use

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/136250383/8eca28b9-1b9f-48d0-b11c-fc9d2085cc66)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Yash-Ainapure As I have observed now that you have directly utilized the jio savaan api rather than our backend. Could you please tell me why shouldn't we make our backend and where will be implementing the firebase ?

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure As I have observed now that you have directly utilized the jio savaan api rather than our backend. Could you please tell me why shouldn't we make our backend and where will be implementing the firebase ?

- The reason i directly utilized jio savan api:
Before: [the user sends request to backend and then backend sends request to the api and sends that data to user]
Now: [the user directly sends request to api to get the data]
This has improved the speed of getting data directly through api.
(this says that backend isn't necessary here)

Also,
The firebase can be easily implemented on client side(there is no use of backend for it)
I have experience in firebase integration, we will integrate it later.

**Comment by Satyam1923** [comment]
@Yash-Ainapure since you are already working on other issue I need you fix that still keep the back end and now i can observe the sound quality has been reduced due to directly playing from API. What's the problem is now it is playing with 128kps download url see to it that it's fixed to highest quality.

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure since you are already working on other issue I need you fix that still keep the back end and now i can observe the sound quality has been reduced due to directly playing from API. What's the problem is now it is playing with 128kps download url see to it that it's fixed to highest quality. and contact me on discord ASAP.

Ok, I am making a PR for that

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure since you are already working on other issue I need you fix that still keep the back end and now i can observe the sound quality has been reduced due to directly playing from API. What's the problem is now it is playing with 128kps download url see to it that it's fixed to highest quality. and contact me on discord ASAP.

I am not able to find you on Discord, could you please give me your discord username/tag something.
Here's mine :  yashainapure_14602
