### ISSUE TITLE
Feat: Adding Mobile responsiveness to the website

### ISSUE THREAD

**Issue by Yash-Ainapure** [Satyam1923/Spring-Music-Player#251]
### Describe the feature

As you can see the mobile responsiveness of website is too bad and also the App.css where most of the stylings are present is so much messy (see the below screenshot).it contains up to 1200+ lines of messy stylings . I would like to fix/restructure it .
I will refactor the code and make it more readable and pluggable,and alo add full mobile responsiveness to it

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/136250383/5abbf8e4-97b6-4f59-b5c6-5152969c8b65)

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/136250383/43844b99-eac7-43e0-9426-57870bc04068)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Yash-Ainapure for now just fix it. Later we will have to make ui design for mobile.

**Comment by shreyaspathak11** [comment]
can you assign this to me?

**Comment by Yash-Ainapure** [comment]
> can you assign this to me?

I am working on it
