### ISSUE TITLE
the qualtity of song is not good

### ISSUE THREAD

**Issue by Vijayaa21** [Satyam1923/Spring-Music-Player#253]
I aim to integrate the Spotify web API to enhance the quality of songs by enabling song search capabilities and improving their overall sound quality.

**Comment by Satyam1923** [comment]
@Vijayaa21 spotify api is just for controlling the playback of music.

**Comment by Vijayaa21** [comment]
yeah sure I want to do it.

**Comment by Satyam1923** [comment]
fixed.
