### ISSUE TITLE
Feat: Implement All Search page

### ISSUE THREAD

**Issue by The-Phoenics** [Satyam1923/Spring-Music-Player#256]
### Describe the feature

I would like to work on implementing the all search page from the new design.

### Add ScreenShots

![all-search-page](https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/8f192a1a-e5bf-4173-b197-b9ca2981b97d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!

**Comment by Satyam1923** [comment]
@The-Phoenics you can work on it.
