### ISSUE TITLE
Feature: Increase music quality

### ISSUE THREAD

**Issue by Yash-Ainapure** [Satyam1923/Spring-Music-Player#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Previously the sound quality was set to 12kbps and making the sound quality poor , changing it to 96kbps which will drastically improve sound quality.

you can see the sound quality options from the api data here:
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/136250383/68b2d985-7ca2-4550-877b-0a928676c441)

previously it was 12kbps-- will change it to 96kbps,
if required will increase that.

or in FURTHER updates I will make a option for user to select which quality the user wants to listen the song.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Yash-Ainapure for now increase it to 320kbps later on make an issue for setting the music quality.

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure for now increase it to 320kbps later on make an issue for setting the music quality.

Done ✅
