### ISSUE TITLE
[Feature] Adding filters in search

### ISSUE THREAD

**Issue by rahulpoonia29** [Satyam1923/Spring-Music-Player#26]
**Is your feature request related to a problem? Please describe.**
The search only gives a generic list of songs.

**Describe the solution you'd like**
I would like to add a sorting options to the search functionality. The **JIO Savan** API allows for customizing the search results by songs, artists and albums.

**Describe alternatives you've considered**
We can also implement sorting by year for results.

**Additional context**
![Screenshot 2024-05-10 165250](https://github.com/Satyam1923/Spring-Music-Player/assets/140232466/64262b5c-4d61-4b4f-9ece-8b94535ab364)

**Comment by rahulpoonia29** [comment]
@Satyam1923 I would like to work on this issue under GSsoC'24

**Comment by Satyam1923** [comment]
@rahulpoonia29 fine!

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Thank you! 🚀

**Comment by yujit2003** [comment]
I would also like to work in this issue @Satyam1923

**Comment by AmrutaZagade** [comment]
@Satyam1923 I would like to work on this issue under GSsoC'24

**Comment by Swapnil-Bhatnagar** [comment]
Please assign this issue to me sir. I really wants to fix this issue
