### ISSUE TITLE
BUG: Currently, when utilizing the search bar, the cursor (and text typed in the search bar) are aligned towards the center of the search bar.

### ISSUE THREAD

**Issue by Nuke1999** [Satyam1923/Spring-Music-Player#266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Based on other popular music streaming platforms, the cursor and text should be aligned to the left, not the middle. I've included an attachment that shows Spring's current configuration versus a popular streaming platform, the Spotify Web Player to prove my point.

Currently, Spring's search looks like:
![Spring Issue](https://github.com/Satyam1923/Spring-Music-Player/assets/127163179/487f835c-5df6-4d26-a2f3-cab11cf2ccd2)

Whereas Spotify Web Player's search looks like:
![spotify example](https://github.com/Satyam1923/Spring-Music-Player/assets/127163179/a094a42b-d728-4f64-b3a0-8239d50a03ce)

I would like to make it look more like Spotify's search bar, with text and cursor aligned to the left.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Nuke1999 you work on it under level 1 bug.
