### ISSUE TITLE
Feat:  Add History/Last Played Song Section

### ISSUE THREAD

**Issue by chandannekya** [Satyam1923/Spring-Music-Player#269]
### Describe the feature

Currently, our music application lacks a feature that allows users to view their listening history or the last played song. Adding a history or last played song section will enhance user experience by allowing them to easily revisit recently played songs.

### Add ScreenShots

![Screenshot 2024-06-06 120522](https://github.com/Satyam1923/Spring-Music-Player/assets/121476456/4391d112-7c82-4406-94bf-e3ad0b0da960)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chandannekya** [comment]
@Satyam1923  I want to work on this issue please assign me under GSSOC'24

**Comment by Satyam1923** [comment]
@chandannekya how are you going to implement it?

**Comment by chandannekya** [comment]
> @chandannekya how are you going to implement it?
[Backend]
1.Update User Module:
Add an array in the user module to store all played songs.
2.API Endpoint:
Create an API endpoint to fetch the playback history for a user.

[ Frontend Implementation]

3.Create UI Components:
Develop a History component to fetch and display the list of recently played songs.
4.Update Player Component:
Modify the music player component to update the user's played songs array each time a song start playing.

**Comment by Satyam1923** [comment]
@chandannekya you can work on it.
