### ISSUE TITLE
Docker-compose file is needed

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [Satyam1923/Spring-Music-Player#270]
### Describe the feature

We have two different folder and two different dockerfile for frontend and backend but we need to connect both of them so that both are on with the help of one command and we can do this with the help of docker-compose file 

please assign me this issue under gssoc'24

### Add ScreenShots

No screenshot

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@agarwalhimanshugaya fine you can work on it.
