### ISSUE TITLE
There are multiple Unused components 

### ISSUE THREAD

**Issue by vverma022** [Satyam1923/Spring-Music-Player#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are multiple unused components and also the navbar and other parts of the project are not aligned 
<img width="1424" alt="Screenshot 2024-06-06 at 3 56 04 PM" src="https://github.com/Satyam1923/Spring-Music-Player/assets/109036913/7e5ca4b5-c448-4f0b-9ccd-6f1a9ef29128">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vverma022** [comment]
I'd like to work in it and implement the changes for the UI to be better and more responsive

**Comment by Satyam1923** [comment]
dont remove any components.
