### ISSUE TITLE
Feat:Make Home Page mobile Responsive

### ISSUE THREAD

**Issue by Skb08** [Satyam1923/Spring-Music-Player#272]
### Describe the feature

The home page of the Spring project needs to be made responsive to ensure it displays correctly on various devices, including mobile phones, tablets, and desktops. The current layout does not adapt well to different screen sizes, affecting the user experience.

### Add ScreenShots

![spring_mobile_view](https://github.com/Satyam1923/Spring-Music-Player/assets/113046759/925646e7-2431-4508-800c-1832da971226)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
could you tell me design how it should look in mobile?

**Comment by Skb08** [comment]
### Desktop View :
![spring_labtop](https://github.com/Satyam1923/Spring-Music-Player/assets/113046759/81e3a190-42ae-40f6-a51d-895fac85f7c0)

### Tab View :
![spring_tab_1](https://github.com/Satyam1923/Spring-Music-Player/assets/113046759/eacc1243-8e0d-41be-98f8-3b1b40252b35)
![spring_tab_2](https://github.com/Satyam1923/Spring-Music-Player/assets/113046759/615feb6f-e9d3-4329-912d-df0367fc3c4d)

Mobile View :
![spring_mob_1](https://github.com/Satyam1923/Spring-Music-Player/assets/113046759/5cf5aba4-d4ff-4784-92d2-ebd6532766a4)
![spring_mob_2](https://github.com/Satyam1923/Spring-Music-Player/assets/113046759/466d462a-20a5-465d-91f2-f16b959ab445)
![spring_mob_3](https://github.com/Satyam1923/Spring-Music-Player/assets/113046759/0b91aa9d-1218-4852-8eaf-c08c2cb62957)

**Comment by saurabhsingh720** [comment]
@Skb08 
Do it
