### ISSUE TITLE
BUG:Music automatically plays after coming back to homepage from setting.

### ISSUE THREAD

**Issue by Riddhi162** [Satyam1923/Spring-Music-Player#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

So when we click on the settings option and come back from it the music starts playing somehow even if it was paused before which might not be the expexted behaviour. I would like to work on this issue under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Riddhi162 you can work on it.

**Comment by Riddhi162** [comment]
Thanks for assigning!
