### ISSUE TITLE
Feat:Add moving and glowing border effect to the div on hover

### ISSUE THREAD

**Issue by Riddhi162** [Satyam1923/Spring-Music-Player#274]
### Describe the feature

In your website I can add this moving glowinig border effect to make it look more appealing and it will add pop to your website.
Since it has black background this will make it look better also if not on hover I can also keep it without hover.
I can make something like this.

### Add ScreenShots
we can add it to all this div 
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/135015856/0923d7f3-def7-4454-802a-ec8c484b2eee)

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/135015856/15e97c5c-4227-4a5a-8b9c-973d0e8b0e1a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Riddhi162 no not required but thankyou for suggestions.
