### ISSUE TITLE
DOC: Merge the two "Learn.md" files

### ISSUE THREAD

**Issue by Nuke1999** [Satyam1923/Spring-Music-Player#276]
### What's wrong with the existing documentation

Currently, there exists a "LEARN.md" and a "Learn.md" file in the master branch. This is problematic, because unlike Github, Windows is a case-insensitive file system. This is causing my local system to not distinguish between the two, and incorrectly merges the two files into one, causing an unintended modification just from pulling latest. I suggest merging the two files while maintaining all of the relevant information from each file into a consolidated, "LEARN.md" file. I've provided a screenshot to show what I am talking about, in regards to the "modification" detected by git, due to both files being named the same. 

![learn md issue](https://github.com/Satyam1923/Spring-Music-Player/assets/127163179/a8bdfb7f-288a-4d66-8893-d8bdf98e451d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
fine do this asap.
