### ISSUE TITLE
Feat: Adding Github in Social Links

### ISSUE THREAD

**Issue by pani2004** [Satyam1923/Spring-Music-Player#277]
### Describe the feature

I can add a github icon in the footer section

### Add ScreenShots

![Screenshot (51)](https://github.com/Satyam1923/Spring-Music-Player/assets/154724111/7ab372b1-6d4e-4cd2-a976-ee0bc1d3e928)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pani2004** [comment]
@Satyam1923 pls assign me this!!!

**Comment by Satyam1923** [comment]
fine.

**Comment by pani2004** [comment]
@Satyam1923 pls add the level tag

**Comment by pani2004** [comment]
@Satyam1923 there are no points for level 0 tag point starts from level1 tag

**Comment by Satyam1923** [comment]
but I'am instructed to not to give level 1 on small changes as it leads to spam PRs.

**Comment by pani2004** [comment]
Ok @Satyam1923 pls check the PR #285
