### ISSUE TITLE
BUG: Linking the about us and help and support to it's respective content in the footer

### ISSUE THREAD

**Issue by pani2004** [Satyam1923/Spring-Music-Player#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

About us and Help&Support are not linked to it's respective pages. I can do it using react router

https://github.com/Satyam1923/Spring-Music-Player/assets/154724111/806da7aa-828a-4acc-85f5-2bcf03efda06

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pani2004** [comment]
@Satyam1923 pls assign me this!!

**Comment by Satyam1923** [comment]
fine you can work on it.
