### ISSUE TITLE
Dark/Light Mode Switcher

### ISSUE THREAD

**Issue by thevijayshankersharma** [Satyam1923/Spring-Music-Player#28]
**Is your feature request related to a problem? Please describe.**
Users often prefer different visual themes based on their preference or environmental conditions. However, many websites and applications lack the option to switch between dark and light modes, leading to discomfort for users in low-light settings or causing eye strain.

**Describe the solution you'd like**
Implement a dark/light mode switcher that allows users to toggle between different visual themes seamlessly. This feature should provide users with the flexibility to choose between dark and light modes based on their preference or environment.

**Describe alternatives you've considered**
One alternative is manually adjusting the brightness or contrast settings on the device, but this can be cumbersome and doesn't provide the same level of flexibility as a dedicated dark/light mode switcher.

**Additional context**
Integrating a dark/light mode switcher enhances user experience and accessibility, providing a more comfortable viewing experience for users in various lighting conditions.

**Comment by thevijayshankersharma** [comment]
@Satyam1923 I would like to work on this issue under GSsoC'24

**Comment by Devon-1984** [comment]
@Satyam1923  I would also like to work on this issue under GSsoC'24

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Satyam1923** [comment]
@thevijayshankersharma you want to work on current ejs or future react frontend.
I don't want people work to go waste that's is why didnt't raised issue for frontend that much but you want to still implement in ejs you can tell me.

**Comment by thevijayshankersharma** [comment]
@Satyam1923 Yeah I would love to work on current ejs further if you need more changes then let me if I can help in that.

**Comment by MonikaLuhach** [comment]
Hii, I'm happy to work on this issue under GSsco'24 contibution. Could you please assign it to me?

**Comment by Satyam1923** [comment]
@thevijayshankersharma  ya then you work on it .

**Comment by Aryanmittal23** [comment]
please assign me this issue

**Comment by Muskansahuincredible** [comment]
PLEASE ASSIGN ME THIS ISSUE I WILL REALLY WORK HARD ON IT

**Comment by TomLucasakaTGeek** [comment]
Assign this issue to me

**Comment by thevijayshankersharma** [comment]
@Satyam1923, I've completed most of the work and would like your assistance with creating a pull request. I've also sent you a message on Discord, please check it when you can. Thanks!

**Comment by SanaAzeem512** [comment]
@Satyam1923 Please assign me this issue. I would like to work on this issue under GSsoC'24

**Comment by KavyaBS123** [comment]
please assign this issue to me

**Comment by Akshx09** [comment]
I would like to work on this isssue under GSSOC

**Comment by gundellyvamshiyadav** [comment]
@Satyam1923 please assign me this issue.I would like to work on it under GSSOC'24

**Comment by Swapnil-Bhatnagar** [comment]
Please assign this issue to me sir. I really wants to fix this issue

**Comment by Akshatakapare** [comment]
I would like to work on this issue under GSsoC'24. please assign me this issue.

**Comment by Dev-AyushTrivedi** [comment]
i can fix this issue please assign this to me
