### ISSUE TITLE
The Edit the footer 

### ISSUE THREAD

**Issue by vverma022** [Satyam1923/Spring-Music-Player#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footer has sections. Make pages for about us privacy policy etc 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@vverma022 about us is their privacy policy and other you can make?

**Comment by vverma022** [comment]
Definitely

**Comment by vverma022** [comment]
I'll use the existing theme and implement it

**Comment by vverma022** [comment]
I have successfully implemented the terms of service and about us and also made them clickable so that user can be routed to the specific page. To complete the full footer what do I write in the Culture , Help and Support and Blog route. If you could give me some insight  it'll be great.
