### ISSUE TITLE
BUG: Updating the twitter logo

### ISSUE THREAD

**Issue by pani2004** [Satyam1923/Spring-Music-Player#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The twitter icon needs to be updated
![Screenshot (53)](https://github.com/Satyam1923/Spring-Music-Player/assets/154724111/0a0552f4-380b-4df0-a8a8-cb59739fa3d1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pani2004** [comment]
@Satyam1923 Pls assign me this!!

**Comment by Satyam1923** [comment]
fine
