### ISSUE TITLE
BUG: Search Button UI

### ISSUE THREAD

**Issue by Vipullakum007** [Satyam1923/Spring-Music-Player#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Search Button UI is not good +

![Screenshot 2024-06-07 090756](https://github.com/Satyam1923/Spring-Music-Player/assets/127659443/8244e9b8-0dbe-4c92-b562-ca4c417034e4)

 when song is play icon not changed to play icon

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/127659443/f6a94568-3c64-4a7e-b0ec-9c7d8c1cc35f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vipullakum007** [comment]
hey @Satyam1923 , please assign me i have mastery in it.

**Comment by Vipullakum007** [comment]
hey @Satyam1923 , i have 2 issue in this one please check it that

when song is play icon not changed to play icon

![Screenshot 2024-06-07 090937](https://github.com/Satyam1923/Spring-Music-Player/assets/127659443/96bce333-a3cb-4bdb-b955-cdf1d92a5258)

**Comment by Satyam1923** [comment]
hmm you can work on it.
