### ISSUE TITLE
Feat: Generate Random color cards on the audio section as Spotify

### ISSUE THREAD

**Issue by SrinivasDevolper** [Satyam1923/Spring-Music-Player#288]
### Describe the feature

Generate Random color cards on the audio section as Spotify which is user experience

**I am GSSOC24 Contributor
Please assign me, I would like to work on it**

### Add ScreenShots

https://github.com/Satyam1923/Spring-Music-Player/assets/121508628/9575216d-adcd-416b-9469-8f7b4b8444a6

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@SrinivasDevolper see don't use random color i'll give you some 6 colors if song photo is near them you can change it with that color fine.

**Comment by SrinivasDevolper** [comment]
Ok sure, I can add 6 colors, you can share me, and I will do it well

**Comment by Satyam1923** [comment]
![Screenshot 2024-06-07 011535](https://github.com/Satyam1923/Spring-Music-Player/assets/104068640/bd30716e-5e6d-4882-9312-7fcd968ce8bb)
use above colors.
