### ISSUE TITLE
Add dynamic code for dynamic year in footer section.

### ISSUE THREAD

**Issue by tarushi29** [Satyam1923/Spring-Music-Player#290]
### Describe the feature

I want to add dynamic code for year in the footer section.

### Add ScreenShots

![Screenshot 2024-06-07 111033](https://github.com/Satyam1923/Spring-Music-Player/assets/128239884/b6896589-9ff2-4a16-bc00-e117bc9c31bb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@tarushi29 you can work on it.
