### ISSUE TITLE
Feat: Auto Scrolling Of The Top Artist Section

### ISSUE THREAD

**Issue by pani2004** [Satyam1923/Spring-Music-Player#292]
### Describe the feature

I can implement a auto scroll feature for the top artist section

### Add ScreenShots

<img width="633" alt="Screenshot 2024-06-07 155517" src="https://github.com/Satyam1923/Spring-Music-Player/assets/154724111/233edf6a-b611-43c4-b14b-9ac582c6178f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pani2004** [comment]
@Satyam1923 can I work on this?

**Comment by Satyam1923** [comment]
@pani2004 no need.
