### ISSUE TITLE
Feat: We can create seperate liked song pages

### ISSUE THREAD

**Issue by dhruv8433** [Satyam1923/Spring-Music-Player#293]
### Describe the feature

@Satyam1923 

we can create seperate liked music page when user click on that they will redirected to `/liked-song`

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/913d07a0-10a5-481c-ac34-a9171185d987)

something like this

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/281c9e0c-a456-4053-9bff-eaddc57ca29c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@dhruv8433 sure we can create.

**Comment by saurabhsingh720** [comment]
@dhruv8433 
How long u take to do this task??

**Comment by dhruv8433** [comment]
@saurabhsingh720 

I will complete this within 2 days

**Comment by dhruv8433** [comment]
@saurabhsingh720 

i will complete whole page 
can i get level 3 ...?

**Comment by Satyam1923** [comment]
@dhruv8433 check the album page in design make it exact same of like page also. For level i'll label it level 2.

**Comment by dhruv8433** [comment]
@Satyam1923 

Thank you i will try my best

**Comment by dhruv8433** [comment]
can you please share screenshort of album page if you have design

**Comment by Satyam1923** [comment]
@dhruv8433 check in the link provide in readme.

**Comment by dhruv8433** [comment]
@Satyam1923 

i am trying to access album page

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/8250c1a9-d1ab-4de0-8616-f46a2b30db06)

but it redirect me on home

**Comment by dhruv8433** [comment]
can i design it same as spotify?
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/3d7111ce-ec96-4694-97c4-852a05a9345c)

**Comment by Satyam1923** [comment]
uff wait i'll provide screenshot

**Comment by dhruv8433** [comment]
sorry for bothering you
but it doesn't uploded yet

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/379936f7-c64b-4f43-a0ef-943d2e7a1384)
