### ISSUE TITLE
Feat: I want to add terms and policy page. I want to contribute under GSSOC'24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Satyam1923/Spring-Music-Player#294]
### Describe the feature

There is a link in the footer terms and policy. I wish to add a page for that. 

### Add ScreenShots

![Screenshot 2024-06-07 174752](https://github.com/Satyam1923/Spring-Music-Player/assets/123104247/7373f06f-edcb-4053-87f5-56583f24596d)

I want to add the page for this Terms and Policy. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@ParnaRoyChowdhury777 you can work on it.
