### ISSUE TITLE
Favourites playlist

### ISSUE THREAD

**Issue by paulkrishanu4** [Satyam1923/Spring-Music-Player#296]
### Describe the feature

want to create favourite playlist like by storing the data in local storage like this

### Add ScreenShots

https://github.com/Satyam1923/Spring-Music-Player/assets/169196836/93277eef-af9a-4b22-b770-c3295a04fa62

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@paulkrishanu4 you can work on it.
