### ISSUE TITLE
Feat: Create Album ui

### ISSUE THREAD

**Issue by dhruv8433** [Satyam1923/Spring-Music-Player#298]
### Describe the feature

@Satyam1923 

we can create album ui something like this

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/430a97a4-1c59-4590-a6ab-9c0a075b93bc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@dhruv8433 use my design which i have given earlier.

**Comment by dhruv8433** [comment]
Thank you @Satyam1923

**Comment by Satyam1923** [comment]
@dhruv8433 dhruv any updates?

**Comment by dhruv8433** [comment]
@Satyam1923 

Please merge liked song pr
So i can make another for this one
