### ISSUE TITLE
BUG: I want to improve the search icon of 'What do You want to play?' bar in the header. I want to contribute under GSSOC' 24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Satyam1923/Spring-Music-Player#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-07 221550](https://github.com/Satyam1923/Spring-Music-Player/assets/123104247/f994940f-c0fa-4eaa-9f7f-d92385416714)

Here the text and the icon are overlapped. I want to fix this. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
fine
