### ISSUE TITLE
Feat:Improve the UI of the contact us page

### ISSUE THREAD

**Issue by komal-agarwal5** [Satyam1923/Spring-Music-Player#302]
### Describe the feature

I wish to improve the UI of the contact us page and also add also add an illustration beside it

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@komal-agarwal5 can you purpose the design idea.

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5 can you purpose the design idea.

![Screenshot 2024-06-07 234541](https://github.com/Satyam1923/Spring-Music-Player/assets/122633300/6c58c832-3271-443f-82ed-f633a1244b19)

Something like this with a diffrent illustration on right side and more social icons

**Comment by Satyam1923** [comment]
@komal-agarwal5 fine you can work on it.
