### ISSUE TITLE
[Feature Request]: Style added to Scrollbar

### ISSUE THREAD

**Issue by SrinivasDevolper** [Satyam1923/Spring-Music-Player#303]
### Describe the feature

I want to add a style to the scrollbar that looks good and gives a better user experience.

**I am GSSOC24 Contributor
Please assign me, I would like to work on it**

### Add ScreenShots

![scrollbar](https://github.com/Satyam1923/Spring-Music-Player/assets/121508628/672e4ecb-f0fd-483e-8e8e-bfac5b91dead)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@SrinivasDevolper fine.

**Comment by RabadeJanhvi-45** [comment]
I am GSSOC'24 Contributor
Please assign the label.
I would like to work on this label.

**Comment by SrinivasDevolper** [comment]
![scrollbarimg3](https://github.com/Satyam1923/Spring-Music-Player/assets/121508628/c689a6bf-c15c-4a5e-9aa3-eef5d407038d)

![scrollbarimg2](https://github.com/Satyam1923/Spring-Music-Player/assets/121508628/cb0c2a3f-de34-4d5d-ad36-4ee7add9574b)

![scrollbarimg1](https://github.com/Satyam1923/Spring-Music-Player/assets/121508628/8331c1e0-4364-4076-94ac-1831c5c18e21)

which one would you like? If you are not satisfied with these colors, please suggest some colors

**Comment by Satyam1923** [comment]
@SrinivasDevolper first one is good just make small curves at edges of the scrollbar to match with UI.

**Comment by SrinivasDevolper** [comment]
sure, I do it
