### ISSUE TITLE
BUG: Social media links in footer not working

### ISSUE THREAD

**Issue by paridhi1509** [Satyam1923/Spring-Music-Player#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The icons in the footer need to be connected to the respective social media accounts. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@paridhi1509 and those social media account not exists for now.
