### ISSUE TITLE
I wish to make the Help and Support Page mobile responsive. I want to contribute under GSSOC'24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Satyam1923/Spring-Music-Player#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have searched the existing issues with the keyword responsive and found the existing issues were regarding the responsiveness of the home page screenshot. So, I wish to contribute here.

![Screenshot_20240608-024559_Samsung Internet](https://github.com/Satyam1923/Spring-Music-Player/assets/123104247/145ad3de-c823-4110-8252-7bfa1ce3f315)

In the mobile it is coming in this way. I wish to fix this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@ParnaRoyChowdhury777 fine.

**Comment by ParnaRoyChowdhury777** [comment]
> @ParnaRoyChowdhury777 fine.

Thank you Sir for considering my issue. I will work on it very soon.
