### ISSUE TITLE
BUG: Responsive issue for the settings page

### ISSUE THREAD

**Issue by vilasini-v** [Satyam1923/Spring-Music-Player#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The settings page is not entirely responsive, please let me work on it as a contributor for gssoc 2024!
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/115165428/28168b68-cc54-4a53-b240-9343ea676eb1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@vilasini-v fine.

**Comment by vilasini-v** [comment]
please assign it to me
