### ISSUE TITLE
Feat:Adding attractive and colourful hover effect to the icons and texts

### ISSUE THREAD

**Issue by HarshitGupta1511** [Satyam1923/Spring-Music-Player#310]
### Describe the feature

the white hover effect looks old and simple. adding attractive hover effect  will make page much more attractive .
please assign me this issue @sat

### Add ScreenShots

<img width="1396" alt="Screenshot 2024-06-08 at 3 21 14 PM" src="https://github.com/Satyam1923/Spring-Music-Player/assets/120268295/ba5b772d-bdbf-4ee7-9abf-e55d1144cd00">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@HarshitGupta1511 currently there isn't any hover effect what do you want to implement send some reference.

**Comment by HarshitGupta1511** [comment]
I want to add hover effects on the icons present and also to some texts to
make it attractive

**Comment by Satyam1923** [comment]
@HarshitGupta1511 fine you can work on it.

**Comment by priti200** [comment]
Hey @Satyam1923,

I would like to work on this issue if it's not done yet. I can add a hover effects on the icons  to make it eye-catching. 
thankyou!!!!
