### ISSUE TITLE
Feat: Adding action tool tip

### ISSUE THREAD

**Issue by PranotiPD** [Satyam1923/Spring-Music-Player#311]
### Describe the feature

Adding action tool tip for icons on the page

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@PranotiPD point it out.

**Comment by PranotiPD** [comment]
need to screenshot ?

**Comment by Satyam1923** [comment]
yes.
