### ISSUE TITLE
Feat: Using new react player since this one have no next and previous option

### ISSUE THREAD

**Issue by Prithwi32** [Satyam1923/Spring-Music-Player#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 since this one have no next and previous option, introducing new react player to solve this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Prithwi32 you can work on it.

**Comment by Satyam1923** [comment]
https://blog.logrocket.com/building-audio-player-react/ check this
actually implement the next and previous option in controls of music player.

**Comment by Prithwi32** [comment]
> https://blog.logrocket.com/building-audio-player-react/ check this actually implement the next and previous option in controls of music player.

okay thank you @Satyam1923 ..
i will look into it
