### ISSUE TITLE
BUG: Alignment in search bar

### ISSUE THREAD

**Issue by Shreyaa173** [Satyam1923/Spring-Music-Player#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/144673309/0d17d967-6b8a-45ab-90b0-0bfa7edf761b)
not well aligned

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@Shreyaa173 
U can but u have to take care of responsiveness in all modes as well

**Comment by Shreyaa173** [comment]
Ya sure, I'll keep that in mind
