### ISSUE TITLE
Feat: Implement songs section in Search page

### ISSUE THREAD

**Issue by The-Phoenics** [Satyam1923/Spring-Music-Player#317]
### Describe the feature

I would like to work on implementing the songs page in new Search page that has been receently implemented.

### Add ScreenShots

![search-songs-page](https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/ef10ddc2-b47e-4d7e-bcc8-9352daaa0dab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@The-Phoenics you can work on it.

**Comment by Satyam1923** [comment]
@The-Phoenics what is your update ?

**Comment by The-Phoenics** [comment]
Hey @Satyam1923 
I'm going to start this issue tomorrow. Right now, I'm almost done working on #322 which is took quite some time.
