### ISSUE TITLE
BUG: When Searching Completed the songs started autoplaying .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Satyam1923/Spring-Music-Player#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When i Searched for any song and then after clicking on search button then when the searching is over the songs started autoplaying . According to me when searching will over then user will play the song of their choice .
I would like to work on it kindly assign this to me .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
It's not a bug i wanted it to work it like that due to ejs.
