### ISSUE TITLE
Feat: Setup nested routes for Search page

### ISSUE THREAD

**Issue by The-Phoenics** [Satyam1923/Spring-Music-Player#322]
### Describe the feature

Search components has many routed child components. So, the nested routes must be added using `react-router-dom`'s Outlet feature.

### Add ScreenShots

![search](https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/344152f8-42c2-453f-91ff-205ddd56fbb7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@The-Phoenics like how much you have completed this issue because I am thinking of implementing something.
