### ISSUE TITLE
Feat: Light/Dark Mode feature

### ISSUE THREAD

**Issue by Shivam250702** [Satyam1923/Spring-Music-Player#323]
### Describe the feature

I want to implement a light/dark mode feature in this project

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/103785990/ee0fa378-69b5-4001-b9e2-0542a9ff73b5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@Shivam250702  do it asap
