### ISSUE TITLE
BUG: Occur Empty Page

### ISSUE THREAD

**Issue by SrinivasDevolper** [Satyam1923/Spring-Music-Player#328]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

https://github.com/Satyam1923/Spring-Music-Player/assets/121508628/8e148181-7a74-4409-aa66-ff653d4d6408

**I am GSSOC 24 Contributor
Please assign me, I Would like to work on it**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@SrinivasDevolper this happens when we make a call to api with undefined field if you want to check APIs calls from frontend to backend you can contribute.
