### ISSUE TITLE
Feat: Redesign and improve the About Us Page

### ISSUE THREAD

**Issue by komal-agarwal5** [Satyam1923/Spring-Music-Player#330]
### Describe the feature

I wish to redesign the ui of the about us page and make square cards in grid form with special hover effecrs.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/122633300/01d95ba1-eb1e-444f-915b-bdcc9aeb84d8)
Something like this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@komal-agarwal5 fine.
