### ISSUE TITLE
Feature ✨: Add scroll to top button

### ISSUE THREAD

**Issue by Tejashri-Taral** [Satyam1923/Spring-Music-Player#331]
### Describe the feature

 I have noticed a small issue that I believe could enhance the user experience. Currently, there is no scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website. 

### Add ScreenShots

Here, scroll to top button is missing:

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/160386036/227e1b3d-6bcc-4a40-935e-7df12df7385b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Tejashri-Taral but it will always be a single webpage webapp why do need this feature.

**Comment by Gokilp** [comment]
please assign to me

**Comment by Tejashri-Taral** [comment]
@Satyam1923 , Yes..I understand that Spring currently has short content, making a scroll-to-top button seem unnecessary at this stage. However, I believe it would be beneficial to add this feature now to enhance user experience as the content grows in the future. 
(We can implement it in a way that it remains hidden until users scroll down a significant amount) 

I’m open to your perspective and would appreciate knowing your thoughts on this suggestion.
