### ISSUE TITLE
BUG 🐞 : Partially Hidden User Profile on the Website

### ISSUE THREAD

**Issue by Tejashri-Taral** [Satyam1923/Spring-Music-Player#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Description:**
I have identified an issue on the website related to user profiles. Currently, the user profile section is partially hidden, which affects the overall user experience.

Though this issue may seem minor, it impacts the usability and completeness of the website. As a contributor, I believe addressing this issue will enhance the overall performance and user satisfaction.

**Expected Behavior:**
The user profile section should be fully visible and accessible to users without any parts being hidden. This will ensure a seamless experience for visitors navigating the website.

****Screenshot(Mandatory):****

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/160386036/278150a4-85c4-4f36-ba22-34611278a24f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Tejashri-Taral you can work on this issue.
