### ISSUE TITLE
Feat: Add "Website Visitor" Widget in Footer

### ISSUE THREAD

**Issue by rohitinu6** [Satyam1923/Spring-Music-Player#334]
### Describe the feature

The current website does not display the number of visitors it has received, which could be useful for tracking engagement and performance metrics.

I would like to add a "Website Visitor" widget in the footer of the website that shows the number of visitors so far. This widget will update in real-time or upon page refresh to provide an accurate count of the total visitors.

This feature will enhance user engagement by providing visible visitor statistics and can be a useful metric for site administrators to track traffic.

### Add ScreenShots

Preview of proposed Website Visitor widget:
![Screenshot 2024-06-12 143634](https://github.com/Satyam1923/Spring-Music-Player/assets/113301503/fe5bd516-60d4-44f7-b46a-d01381aef6f8)

**Please assign this issue to me under the gssoc label**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@rohitinu6 nice you can work on it but list some good designs.

**Comment by rohitinu6** [comment]
Sure sir @Satyam1923

**Comment by deepak00944** [comment]
@rohitinu6  can i work on it?? 😂

**Comment by Yash-Ainapure** [comment]
@Satyam1923 ,
I would like to work on this if the current assigned one is not active i think

**Comment by deepak00944** [comment]
@rohitinu6 would you like to pass this opportunity ??

**Comment by Satyam1923** [comment]
@rohitinu6 any updates?

**Comment by rohitinu6** [comment]
@Satyam1923 working on it, will make a pr by this week.

**Comment by Satyam1923** [comment]
@rohitinu6 any updates.?
