### ISSUE TITLE
Feat: Unable to find after submission

### ISSUE THREAD

**Issue by Garima-149** [Satyam1923/Spring-Music-Player#335]
### Describe the feature

In below provided screenshot,after clicking on submit button ,there is not such activity that user get to know that it has been submitted.I want to add some checks to ensure user that the button has been clicked successfully. @Satyam1923 I want to work on issue.

### Add ScreenShots

![Screenshot (52)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/5d6028d5-0d53-4cd5-8562-b320ebe92c8c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Garima-149 nice suggestion but try to contribute in different section of the project which is really required.

**Comment by Yash-Ainapure** [comment]
@Satyam1923 , I would like to work on this by giving a small animation to the button.
