### ISSUE TITLE
Feat:Adding more css to background

### ISSUE THREAD

**Issue by Garima-149** [Satyam1923/Spring-Music-Player#336]
### Describe the feature

Right now,the black solid background is not looking good for such  mood refreshing application.So,I want to add more aesthetic background to page. @Satyam1923 Willing to work upon this issue.

### Add ScreenShots

![Screenshot (53)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/0adc3b46-d2af-40b4-9bbe-e0514a3712cc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Garima-149 fine

**Comment by Garima-149** [comment]
@Satyam1923 Should I make changes again and make another PR after reviewing it from you?

**Comment by Akshit462005** [comment]
Please assign this issue to me. I am a Technical Executive at the IEEE CUIET Organization.  
I would like to work on this issue. Providing you with the best results. I have already worked on projects like this and would like to contribute.

**Comment by Garima-149** [comment]
![Screenshot (66)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/9a7c74cf-430b-49a7-9cd0-234eb65d5104)

@Satyam1923  Please check this.If it is ok or need changes?
