### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by sanskriti-lal** [Satyam1923/Spring-Music-Player#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="1438" alt="Screenshot 2024-06-13 at 12 35 22 AM" src="https://github.com/Satyam1923/Spring-Music-Player/assets/165655543/1367cf55-5ac3-443e-ad9e-9e8a874867bb">
<img width="1431" alt="Screenshot 2024-06-13 at 12 35 33 AM" src="https://github.com/Satyam1923/Spring-Music-Player/assets/165655543/6adf9150-54c4-4ded-a6a0-ba443ddc74e9">
The alignment is improper, making the text overlap at certain areas. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@sanskriti-lal but do it ASAP>

**Comment by sanskriti-lal** [comment]
Okay cool. Also can you please assign it to me.
