### ISSUE TITLE
BUG:like button not working

### ISSUE THREAD

**Issue by P-lavanya16** [Satyam1923/Spring-Music-Player#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i want to fix the like button if tap on that its should get like

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@P-lavanya16 you need to store the liked song data in Firebase. Are you familiar with Firebase?

**Comment by P-lavanya16** [comment]
No🫠

**Comment by Satyam1923** [comment]
Nice then go and learn.
