### ISSUE TITLE
Feat: Adding Dark Mode 

### ISSUE THREAD

**Issue by maverickcodex18** [Satyam1923/Spring-Music-Player#34]
### Describe the feature

Adding Dark Mode will increase the User Enhancement and Interaction .

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/79051168/fa0852b6-f520-40ac-ae91-8aae386e5255)
Sample Dark Mode, Will make more improvement in it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@maverickcodex18  First and foremost, you should check if the issue has already been raised before raising it.
