### ISSUE TITLE
BUG:music play button not working

### ISSUE THREAD

**Issue by Varsani2520** [Satyam1923/Spring-Music-Player#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when user click on play button then music is not play 
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/137641079/068d9d33-59ef-4dc0-ac82-63ddd8d4f555)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
i can do it ,assign me

**Comment by Varsani2520** [comment]
also add the label

**Comment by Satyam1923** [comment]
@Varsani2520 fine that keep the track of 10 last played song per user in database and display them along with last played song in music player if you don that I'll assign it to level 3.

**Comment by Varsani2520** [comment]
@Satyam1923 

i need firebase config file so i can work on proper login 
can you please provide `.env` file for firebase key

**Comment by Satyam1923** [comment]
@Varsani2520 I don't have .env file for it just msg me on discord I'll provide the firebase config.

**Comment by Varsani2520** [comment]
ok

**Comment by Satyam1923** [comment]
@Varsani2520 based on whatever logged in user choose or plays for search page.

**Comment by Varsani2520** [comment]
ok @Satyam1923
