### ISSUE TITLE
Feat: Automatic Comment on Pull Request Raised

### ISSUE THREAD

**Issue by thevijayshankersharma** [Satyam1923/Spring-Music-Player#349]
### Describe the feature

Often, when pull requests (PRs) are raised, reviewers may lack crucial context about the changes proposed. This can lead to delays in the review process and misunderstandings between contributors and reviewers.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@thevijayshankersharma you can work on it.

**Comment by thevijayshankersharma** [comment]
@Satyam1923 Hello there is already a workflow for this issue in your repo.
There are many things which are missing in workflow like greeting on issue or PR closed, greeting on PR got merge. If you need any of these tell me. I would like to do it.

**Comment by thevijayshankersharma** [comment]
@Satyam1923 ??

**Comment by vaishnavi-jais** [comment]
I’m excited to tackle this challenge by implementing a system to ensure that every PR comes with all the necessary background and details, making the review process more efficient and collaborative. Could you please assign me this task for GSoC '24? I’m ready to enhance our workflow and bridge the communication gap between contributors and reviewers!

Looking forward to your support!
