### ISSUE TITLE
Feat: Using SpaceBar Button to play/stop music

### ISSUE THREAD

**Issue by maverickcodex18** [Satyam1923/Spring-Music-Player#35]
### Describe the feature

Like in Spotify and other music players , Space Button is used for controlling player, which increases USer Engagement and Interaction.

### Add ScreenShots

I can work on this issue , kindly assign this task to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@maverickcodex18  You can contribute with a different issue, but starting a new issue may not be worth it for just a event listener.

**Comment by Satyam1923** [comment]
Fine go with this issue make the necessary changes in public/js/script.js

**Comment by G0HAN3** [comment]
Hello @Satyam1923  , could you please assign this issue to me? I believe my skills are well-suited to address it. Thank you!

**Comment by ArjunPurohit14** [comment]
I have implemented this issue (#35).
Using the spacebar now you can pause and play the music


https://github.com/Satyam1923/Spring-Music-Player/assets/117063200/a84d2a70-657d-4476-bbc4-bd5c9c7936b4


kindly assign this issue to me.

**Comment by ArjunPurohit14** [comment]
@Satyam1923  assign me this issue so i can push the code.(#35)

**Comment by Satyam1923** [comment]
@ArjunPurohit14 fine you can work on it. Since @maverickcodex18 PR lacks behind.

**Comment by ArjunPurohit14** [comment]
@Satyam1923  maybe your application is not working
