### ISSUE TITLE
BUG: spell error

### ISSUE THREAD

**Issue by AkhilaSunesh** [Satyam1923/Spring-Music-Player#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/140897461/b2b0597f-eed2-46cc-969f-199c825319c5)
There are spelling errors in the webpage.
Kindly assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@AkhilaSunesh Superub dude nice contribution.

**Comment by AkhilaSunesh** [comment]
> @AkhilaSunesh Superub dude nice contribution.

I do understand that it is a minor fault. But spelling mistakes affects the professionalism of the webpage. Viewers do notice it.

**Comment by Satyam1923** [comment]
fine I'll fix it.
