### ISSUE TITLE
Feat: Add visibility feature in password box

### ISSUE THREAD

**Issue by AkhilaSunesh** [Satyam1923/Spring-Music-Player#354]
### Describe the feature

Add facility to view password

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/140897461/23fffe23-cff7-46b6-bc2c-f84ff7b53d8e)
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/140897461/214cbe1c-9848-4822-bd9b-17a8957d2db5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@AkhilaSunesh fine you can work on this issue.

**Comment by Akshit462005** [comment]
Please assign this issue to me. I am a Technical Executive at the IEEE CUIET Organization.  
I would like to work on this issue. Providing you with the best results. I have already worked on projects like this and would like to contribute.

**Comment by Satyam1923** [comment]
@Akshit462005 don't comment on someone's else issues make your own and work under it.
