### ISSUE TITLE
Feat:Add hover cards for "about us" page

### ISSUE THREAD

**Issue by AkhilaSunesh** [Satyam1923/Spring-Music-Player#355]
### Describe the feature

Add hover cards to improve the UI

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/140897461/c25e5045-722c-4c0d-aebe-a877b662fbe6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nihal4777** [comment]
@AkhilaSunesh Do you have any design or reference about how you want to implement about us page?

**Comment by AkhilaSunesh** [comment]
https://github.com/Satyam1923/Spring-Music-Player/assets/140897461/ac57dc2d-94f5-49e2-a7d0-ec4f74006c65

There will be a smooth transition
