### ISSUE TITLE
Feat: adding hover effect to links in footer

### ISSUE THREAD

**Issue by dnyandeepchute** [Satyam1923/Spring-Music-Player#364]
### Describe the feature

adding hover effect to links in footer

### Add ScreenShots

![Screenshot 2024-06-15 104707](https://github.com/Satyam1923/Spring-Music-Player/assets/158272735/6c1c43a8-a628-4467-809a-5d234c55be6b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dnyandeepchute** [comment]
please assign this to me, thank you.

**Comment by Satyam1923** [comment]
@dnyandeepchute you can work on it.

**Comment by Akshit462005** [comment]
Please assign this issue to me. I am a Technical Executive at the IEEE CUIET Organization.  
I would like to work on this issue. Providing you with the best results. I have already worked on projects like this and would like to contribute.
