### ISSUE TITLE
Feat:container box and text is overriding

### ISSUE THREAD

**Issue by Garima-149** [Satyam1923/Spring-Music-Player#366]
### Describe the feature

In the provided screenshot,The spring text and container box is overriding.This is distorting UI of landing page . @Satyam1923 I would like to work on this issue.PLease assign me this,thankyou.

### Add ScreenShots

![Screenshot (56)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/1f6786ca-4283-4437-9b88-99ab90592ae1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Garima-149 fine .

**Comment by Garima-149** [comment]
@Satyam1923 
![Screenshot (58)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/6f9fcfc0-a415-42f8-a0d4-9de106d222ad)
![Screenshot (59)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/4aba42c8-3a01-416d-9e06-ca725979bfaf)

I have done the change but when I tried to open the server.Although,server is opening but  I am unable to see tha app,frontend or backend anything.Please help me with this.

**Comment by Satyam1923** [comment]
> @Satyam1923 
> ![Screenshot (58)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/6f9fcfc0-a415-42f8-a0d4-9de106d222ad)
> ![Screenshot (59)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/4aba42c8-3a01-416d-9e06-ca725979bfaf)
> 
> I have done the change but when I tried to open the server.Although,server is opening but  I am unable to see tha app,frontend or backend anything.Please help me with this.

@Garima-149 make a new project in firebase and copy its firebase config in firebase.js

**Comment by Garima-149** [comment]
Actually I haven't tried firebase yet.So,I don't know ,how to deal with it.

**Comment by Satyam1923** [comment]
> Actually I haven't tried firebase yet.So,I don't know ,how to deal with it.

Fine just msg me on discord I'll tell you the steps and config.

**Comment by Garima-149** [comment]
![Screenshot (60)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/ca10d6cc-989b-4656-bc8c-5599b5c1f8c1)
@Satyam1923  Now,the text is not overriding.Please check it.Should I raise pr?

**Comment by Satyam1923** [comment]
Could fix the weeknd and plays text also.

**Comment by Garima-149** [comment]
> Could fix the weeknd and plays text also.

At which side of page?

**Comment by Satyam1923** [comment]
Above genres and top artists.

**Comment by Garima-149** [comment]
![Screenshot (61)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/6a013ce5-0fb4-4014-b206-4b7ca39be38d)
@Satyam1923  Check it once.Also,please tell should I raise PR or need changes?

**Comment by Satyam1923** [comment]
@Garima-149 isn't it going above footer.

**Comment by Garima-149** [comment]
![Screenshot (62)](https://github.co/Satyam1923/Spring-Music-Player/assets/143211271/44a42389-4024-4acd-968f-d63486ed97bc)
@Satyam1923 Now please check

**Comment by Satyam1923** [comment]
@Garima-149 now check top artists row it's clashing with recent played.

**Comment by Garima-149** [comment]
![Screenshot (63)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/9155e536-cab1-4f01-9dc1-474fd38adebc)
@Satyam1923 Now ,is it fine?

**Comment by Satyam1923** [comment]
fine add more spacing.

**Comment by Garima-149** [comment]
> fine add more spacing.

everywhere? or just above Top Artists side?

**Comment by Satyam1923** [comment]
Between every elements

**Comment by Garima-149** [comment]
![Screenshot (64)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/48cf0eb2-73bb-43e7-a2c8-df64ec404c98)
@Satyam1923  This much space is fine?

**Comment by Satyam1923** [comment]
ya fine.

**Comment by Garima-149** [comment]
@Satyam1923 Should I add that code which I inserted in its fetch.js file?or not while raising PR.

**Comment by Satyam1923** [comment]
@Garima-149 what does it contain anyway.

**Comment by Garima-149** [comment]
![Screenshot (65)](https://github.com/Satyam1923/Spring-Music-Player/assets/143211271/c3173998-56ff-4a0e-86f0-b505d84bb86d)
Should I add this code or remove it while making PR?

**Comment by Satyam1923** [comment]
No remove this code.
