### ISSUE TITLE
Add Navbar to About Us and Login Pages

### ISSUE THREAD

**Issue by srivastav2006** [Satyam1923/Spring-Music-Player#369]
### Describe the feature

Currently, the "About Us" and "Login" pages do not have a navbar, making it difficult for users to navigate to other sections of the site from these pages. Adding a navbar to these pages will enhance the user experience by providing easy access to other parts of the website.
Expected Behavior:
Both the "About Us" and "Login" pages should have a navbar similar to the rest of the site or a new navbar , allowing users to easily navigate to other pages such as Home, Contact, etc.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/143505484/352146fa-56e1-4966-b5d7-b33c3597736f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@srivastav2006 fine you can work on it.

**Comment by Akshit462005** [comment]
I kindly request to be assigned to this issue. As a Technical Executive at the IEEE CUIET Organization, I am well-positioned to address this matter. I am committed to delivering optimal results and have prior experience with similar projects, which I believe will enable me to make a meaningful contribution.

reference for prior work / projects :-|
https://www.linkedin.com/in/akshit-verma-596a0824b/
