### ISSUE TITLE
Feat: Add option in issue form records

### ISSUE THREAD

**Issue by dakshsinghrathore** [Satyam1923/Spring-Music-Player#37]
### Describe the feature

Currently, the lagging issue forms for all buttons could be resolved by including an option for contributors to indicate that they have searched existing issues. This addition would help prevent unintentional creation of duplicate issues.

### Add ScreenShots

Something like this ⬇️ 

![Screenshot_2024-05-11_111753](https://github.com/Satyam1923/Spring-Music-Player/assets/115932772/903bd9f8-232e-4809-bf46-973979627a84)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@dakshsinghrathore this issue is assigned to you.
