### ISSUE TITLE
Add remember me check box in login page

### ISSUE THREAD

**Issue by srivastav2006** [Satyam1923/Spring-Music-Player#371]
### Describe the feature

I would like to request the addition of a "Remember Me" checkbox to the login form. This feature will enhance the user experience by allowing users to stay logged in across sessions without having to re-enter their credentials every time they visit the site.

Benefits:

Improved User Convenience: Users won't need to log in repeatedly, making it easier for frequent users.
Time-Saving: Reduces the time spent on the login process.
Enhanced User Retention: Users are more likely to return to a website where they don’t have to log in repeatedly.

### Add ScreenShots

![Screenshot_2024-06-15-18-56-02-365_com android chrome-edit](https://github.com/Satyam1923/Spring-Music-Player/assets/143505484/9be794a4-9796-4c27-be5c-9de987d8e36a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@srivastav2006 you can work on it.
