### ISSUE TITLE
Improving UI of home page

### ISSUE THREAD

**Issue by vaishnavip27** [Satyam1923/Spring-Music-Player#372]
The UI of the home page looks very messed up and needs to improve as all the component's are colliding with each other making the UI look more confusing and messed up

I want to place all the component in the right place and keep minimum space between them so they don't collide with each other and looks clean

Adding the screenshot of the home page below
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/143169451/ec9770b8-0da0-440e-8861-9743e529f2e8)

**Comment by vaishnavip27** [comment]
Hey @Satyam1923 please assign me this issue.

**Comment by Satyam1923** [comment]
@vaishnavip27 fine you can work on it.

**Comment by Subhajit098** [comment]
Hey @vaishnavip27 can you share a screenshot of how are you going to organize the components ?

**Comment by Satyam1923** [comment]
@vaishnavip27 and currently UI I have fixed elements according to  1080p 100% fractional scaling but it's cause issues for 125% fractional scaling, So do tell about approach how you are gonna fix it.
