### ISSUE TITLE
Feature: Add hover effect in footer section on About Us, Culture, Blogs, Terms and Policy,  Help and Support

### ISSUE THREAD

**Issue by navin-3959** [Satyam1923/Spring-Music-Player#373]
### Describe the feature

I will add hover effect on elements  of footer  About Us, Culture, Blogs, Terms and Policy,  Help and Support 
this will increase attractiveness in footer section 

### Add ScreenShots

![Screenshot 2024-06-16 181243](https://github.com/Satyam1923/Spring-Music-Player/assets/143059454/77e5c172-0036-4828-8180-8e689091472b)

 on 
About Us, Culture, Blogs, Terms and Policy,  Help and Support

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by navin-3959** [comment]
please assign me this i will do it properly according to page UI

**Comment by navin-3959** [comment]
Hlo satyam I am not talking about linkdin and social media hover effect i am talking about above it are option those don't have hover effect

**Comment by Satyam1923** [comment]
Ya I have already someone for that issue.

**Comment by navin-3959** [comment]
Ohk
