### ISSUE TITLE
Feature :  Improvement of UI in login page needed

### ISSUE THREAD

**Issue by navin-3959** [Satyam1923/Spring-Music-Player#374]
### Describe the feature

UI of login page should be good looking and attractive 
will add all the functionality needed and a good background image and design it need

### Add ScreenShots

![Screenshot 2024-06-16 182137](https://github.com/Satyam1923/Spring-Music-Player/assets/143059454/41eb32d5-f622-43bc-80de-db62225a6131)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by navin-3959** [comment]
please assign me this will work on it properly

**Comment by Satyam1923** [comment]
@navin-3959 fine you can work on it just show design or something.
