### ISSUE TITLE
Display Top Artists with Names and Songs

### ISSUE THREAD

**Issue by RahulRudra81** [Satyam1923/Spring-Music-Player#376]
### Describe the feature

**Description:**

- On the home page of the Spotify clone project, there is a section for top artists. Currently, it only shows a dummy "Weekend" name. I would like to enhance this section by displaying the names of a few top artists. When an artist's name is tapped, it should display their songs.

**Proposed Solution:**
- Replace the dummy "Weekend" name with actual names of top artists.Example artists: Drake, Ariana Grande, Ed Sheeran, Billie Eilish, The Weeknd.
- Implement functionality to fetch and display songs of an artist when their name is tapped.
- This will involve creating a new view or section to display the list of songs for the selected artist.

**Questions:**

- Do you have a preferred data source or API for fetching the artist names and their songs?
- Are there any specific UI/UX guidelines you would like me to follow for this implementation?

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/91683510/4e3743ad-605b-459f-a27e-6f5d5e8e8098)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@RahulRudra81 for artists and their songs you can check backend API response. As for top ranking what do you prefer billboard api but there's a limit to it's calls per for free version.

**Comment by RahulRudra81** [comment]
I'm thinking about creating a JSON file with the names of 10 artists. When you tap on an artist, I want to be able to make a GET request to search for the artist's songs. I think this might be a level 3 task, as I also want to make sure that you can play the songs once they're fetched.

**Comment by Satyam1923** [comment]
@RahulRudra81 but  how we are gonna update new artists? As for level I'll decide based on your work.

**Comment by RahulRudra81** [comment]
Right now, I was thinking of putting that in manually, but at the same time, I am working on getting the details of top artists dynamically. Should I proceed with manual input if I couldn't find a way to automate it? - @Satyam1923

**Comment by Satyam1923** [comment]
@RahulRudra81 firstly check this API if you could implement ? otherwise proceed with manual entry.

**Comment by RahulRudra81** [comment]
Ok will update you about it. @Satyam1923

**Comment by Satyam1923** [comment]
@RahulRudra81 if it feel hard then I can create a backend for you. Just makes calls from backend?

**Comment by RahulRudra81** [comment]
@Satyam1923  No its fine i have something in mind i will try if it doesn't work i will come to you

**Comment by Satyam1923** [comment]
@RahulRudra81 fine I that API can provide data but the only problem it have request limit.

**Comment by Satyam1923** [comment]
![Screenshot 2024-06-16 233424](https://github.com/Satyam1923/Spring-Music-Player/assets/104068640/c25df6c1-f936-4779-934b-c75d7e7e99e5)
this will do for you?

**Comment by RahulRudra81** [comment]
@Satyam1923  han can do with it

**Comment by Satyam1923** [comment]
@RahulRudra81 need access to firebase?

**Comment by RahulRudra81** [comment]
@Satyam1923 i will make with the same schema you sent me and do in my account only

**Comment by Satyam1923** [comment]
@RahulRudra81 Fine.
