### ISSUE TITLE
 Enhancement:  Addition of Hide /Show Functionality in the login/sign-up page done.

### ISSUE THREAD

**Issue by agrwal697** [Satyam1923/Spring-Music-Player#383]
### Describe the feature

I think if the Login page had of the website by adding the hide/show function after the password field in the Sign-up form by using javascript also , it would have better UI and also  It enhances the UX. Kindly Assign me this issue under GSSOC'24, I would like to work on it.

Please Assign me this issue with the label and level of GSSOC.

### Add ScreenShots

before:
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/128716726/9ca81a99-5d85-46a6-8331-8c7e76020d1b)

After:
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/128716726/263d106d-7c5b-4c61-8d42-97eaf3c2d30e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] #408
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nihal4777** [comment]
Duplicate issue #354
