### ISSUE TITLE
Feat:  Login page can be more attractive.

### ISSUE THREAD

**Issue by ayushrskiaa** [Satyam1923/Spring-Music-Player#386]
### Describe the feature

The login page is not as attractive as it should be.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/130389607/6d184994-0e92-4ca2-be52-d549b74c2b12)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayushrskiaa** [comment]
@Satyam1923 please assign it to me I can make it better.
Thank you

**Comment by Satyam1923** [comment]
@ayushrskiaa someone already working on it.
