### ISSUE TITLE
Feat: Register page is not looking good

### ISSUE THREAD

**Issue by ayushrskiaa** [Satyam1923/Spring-Music-Player#388]
### Describe the feature

The registration page is not as appealing as it ought to be.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/130389607/efce8de9-0ea2-47d8-b38d-b1a20fbaddf3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayushrskiaa** [comment]
@Satyam1923  please assign this to me under GSSoC. I will make it more attractive.
Thank you

**Comment by Satyam1923** [comment]
Someone already working on it.
