### ISSUE TITLE
BUG:There is no hovering effect on some elements of the home page

### ISSUE THREAD

**Issue by ayushrskiaa** [Satyam1923/Spring-Music-Player#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/130389607/f8e9020e-4e0d-4c7a-ba26-58409fd0d8b8)

Hovering effect is not working for some elements on the home page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayushrskiaa** [comment]
please assign it to me under GSSoC'24.
Thank you

**Comment by Satyam1923** [comment]
@ayushrskiaa fine.

**Comment by shashbh18** [comment]
I would love to work on it.Please assign this issue to me.
