### ISSUE TITLE
Feat: Automate greetings process 🤖 

### ISSUE THREAD

**Issue by dakshsinghrathore** [Satyam1923/Spring-Music-Player#39]
### Describe the feature

As the contributor count rises on the repo, it becomes increasingly challenging for maintainers to personally greet and encourage each contributor for their valuable input. Equally important is the reminder for them to review the project's contribution guidelines.

### Greeting message under ISSUE ⬇️ 

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/115932772/b4b35631-2cfe-450e-82ed-6ee7e0e81964)

### Greeting message under ISSUE ⬇️ 

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/115932772/51f37b5e-0f36-4320-9252-95e362ef46d8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@Satyam1923 Kindly assign me this issue under GSSOC24, have made the changes will raise the PR soon.

**Comment by poojaverma9578** [comment]
I want to contribute in this project as a GSSOC 24 contributor.please assign me this
