### ISSUE TITLE
BUG:Elements are not alligned properly on the home page

### ISSUE THREAD

**Issue by ayushrskiaa** [Satyam1923/Spring-Music-Player#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/130389607/f96fd45d-9333-494a-bebe-baaed700a9a6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayushrskiaa** [comment]
Please assign it to me so that I can fix this issue.

Thank you

**Comment by Satyam1923** [comment]
someone already working on it.
