### ISSUE TITLE
Hovering effect in login button

### ISSUE THREAD

**Issue by Shashanktriathi1703** [Satyam1923/Spring-Music-Player#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

* When the user goes to the login button, it is unresponsive, which creates a negative experience for the user. This feature needs improvement. When the user moves to the login button, it should be responsive with added hover effects and engaging animations.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shashanktriathi1703** [comment]
Allow me to work on this issue under GSSOC' 2024 @Satyam1923

**Comment by Satyam1923** [comment]
@Shashanktriathi1703 someone is already working on enhancing login page but if doesn't provide a good output I'll think about assign you for this till then could please wait.
