### ISSUE TITLE
[Feature]: song `Like`

### ISSUE THREAD

**Issue by sivaprasath2004** [Satyam1923/Spring-Music-Player#404]
### Describe the feature

- In this project I will implement the feature `like` song feature .
- It can be Very Effective User Experience.
- please assign me.

### Add ScreenShots

[Screencast from 2024-06-18 15-02-21.webm](https://github.com/Satyam1923/Spring-Music-Player/assets/121082414/b72d4286-3dcd-4420-8e0f-44ccf90dd60f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@sivaprasath2004 for  liked song we need to store to 10 liked song in Firestore user document will you be able to do that>?

**Comment by sivaprasath2004** [comment]
Hello @Satyam1923 , i will share the Feature exactly like that if like button clicked then store to the firestore and `Navigation` bar like section clicked that will be show..

**Comment by me-nilakshi** [comment]
Hey @Satyam1923! Please assign this issue to me. I've a prior experience in firebase. I'll be able to do this.
