### ISSUE TITLE
Implement Recently Played feature

### ISSUE THREAD

**Issue by RahulRudra81** [Satyam1923/Spring-Music-Player#405]
### Describe the feature

**Description:**

- The current music player component does not save the history of played songs. This enhancement involves implementing functionality to store the last 20 songs played in the local storage and displaying them in the recently played section.

**Requirements:**

- Save the details of each song played in local storage.
- Maintain a maximum of 20 songs in the history. If the number of songs exceeds 20, remove the oldest entry.
- Display the recently played songs in the Recently Played section.
- Ensure that song history persists across page refreshes and sessions.

It would look something like this but I will try to make the UI more properly.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/91683510/bb428dc9-757e-4cb2-9f0e-6e370fcadd50)

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
@RahulRudra81 Can you implement this with firebase and not using the local storage ?

**Comment by RahulRudra81** [comment]
I am thinking for those who are logged in we can give the feature to save in firebase so for every login they can see their previous history .for users who are not logged in their storage is in local storage. But i will suggest for local storage only because sending data to backend and fetching it will be for no reason. Local storage is a better option as there will be no fetching from backend and it makes the user experience better. Other than that if you want i can save in firebase only but this can only be done for login user because i have to map the history for different users. Because definitely different users will have different history.

**Comment by Satyam1923** [comment]
@RahulRudra81 if we utilize local storage the it will be browser depended not dynamic so I wanted it to be supportive where ever we login our account and we don't need backend to do this i guess only frontend is enough

**Comment by Satyam1923** [comment]
@RahulRudra81 But I guess two people have already raise this issue.

**Comment by RahulRudra81** [comment]
@Satyam1923 I have checked nobody recently working on it ... Anyways if I save data in firebase how will i map like which recent belong to which user. 

What we can do is who are logged in their recents are stored in firebase making it independent from browser for them. But if you are not logged in just in local storage if their browsers supports they can see recent songs else not.
What do you say?

**Comment by Satyam1923** [comment]
@RahulRudra81 per user new collection for recent played songs. Ya fine for second point.

**Comment by RahulRudra81** [comment]
ok will
