### ISSUE TITLE
BUG: fixing css in mobile view 

### ISSUE THREAD

**Issue by dhairyagothi** [Satyam1923/Spring-Music-Player#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_20240618_195750](https://github.com/Satyam1923/Spring-Music-Player/assets/142989448/5d77850b-4615-441c-add5-73dc056e10e6)

CSS in mobile view is not good i would like to fix it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
Go ahead !

**Comment by Subhajit098** [comment]
@dhairyagothi   Make sure you that you explain the orientation and style by which you are thinking to rearrange the components for mobile view.

**Comment by Subhajit098** [comment]
Hey @dhairyagothi , wanted to know the update regarding this . Could you let me know how much more time it will take ?

**Comment by rohit-yadavv** [comment]
@dhairyagothi, can you please share the status as i also want to work on the issue

**Comment by dhairyagothi** [comment]
working on it there is some issue while running file in local host

**Comment by dhairyagothi** [comment]
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/142989448/e034f8ea-8f6c-47cb-9bce-4774df879b10)

it is not running on local host

**Comment by rohit-yadavv** [comment]
@dhairyagothi  i think you have not done setup for firebase if you are not able to do it let me do it

**Comment by dhairyagothi** [comment]
> @dhairyagothi  i think you have not done setup for firebase if you are not able to do it let me do it 

Ya tell me how to do that
