### ISSUE TITLE
BUG: Improvement in the overall look and feel of login and singup page

### ISSUE THREAD

**Issue by mohitmuktikant** [Satyam1923/Spring-Music-Player#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The **login** and **sigup** pages doesnot look that great and need much improvement in styling and look

![ss12](https://github.com/Satyam1923/Spring-Music-Player/assets/101824646/c583fa46-0918-4944-ad34-339489fa8cea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@mohitmuktikant 
Can u give any idea how after improvement it looks?

**Comment by mohitmuktikant** [comment]
Moreover like this 
![Screenshot 2024-06-22 at 10 56 15 AM](https://github.com/Satyam1923/Spring-Music-Player/assets/101824646/c88c96e0-4e2c-42f8-9e67-7677c7ac4536)

![Screenshot 2024-06-22 at 10 58 41 AM](https://github.com/Satyam1923/Spring-Music-Player/assets/101824646/85bc0214-1d5a-4a12-9f38-4919b2f5fe1e)
