### ISSUE TITLE
Feat:Adding Subscribe to news letter

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Satyam1923/Spring-Music-Player#409]
### Describe the feature

Adding subscribe to news letter in the footer

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/143107589/2f84e6e7-8f91-4a6b-8fbc-d620e2f6b7cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nihal4777** [comment]
@Satyam1923

**Comment by Satyam1923** [comment]
@Nihal4777 no need for this .
