### ISSUE TITLE
BUG: Fix Responsive  

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Satyam1923/Spring-Music-Player#413]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/142687709/5aeabd85-1136-4cf5-9167-0fc43b385d14)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Khushi-Pushkar could you show or design the webpage for mobile ??

**Comment by Khushi-Pushkar** [comment]
![Screenshot 2024-06-20 185736](https://github.com/Satyam1923/Spring-Music-Player/assets/142687709/faf52d4c-81a2-4d1b-b157-23474c515a48)
I have developed a website dedicated to fitness and gym services , so  you can review it across different devices / dimensions

**Comment by saurabhsingh720** [comment]
@Khushi-Pushkar 
How long u take to complete your task??

**Comment by Khushi-Pushkar** [comment]
2-3 days

**Comment by saurabhsingh720** [comment]
@Khushi-Pushkar 
Do it and make sure that it is fully responsive.
And also make sure that don't remove anything from the current project.

**Comment by Khushi-Pushkar** [comment]
@Satyam1923 @saurabhsingh720 I am having trouble running website locally. I followed the steps in the README file carefully, but when I run the npm run dev command, it takes a very long time. Also, when I click the localhost link, I see a blank black page.I cannot get the website to work on the live server and would appreciate your help to resolve this issue.
![Screenshot 2024-06-22 192207](https://github.com/Satyam1923/Spring-Music-Player/assets/142687709/921b239b-acb0-45d2-8cac-54f8042c0a33)
![Screenshot 2024-06-22 192313](https://github.com/Satyam1923/Spring-Music-Player/assets/142687709/336a2f7e-8197-4af2-a025-05f0e50d4b44)

**Comment by Subhajit098** [comment]
is anything showing in the console. Check that first

**Comment by Khushi-Pushkar** [comment]
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/142687709/66203d9b-2613-4ab8-a204-e5800b4cf067)

**Comment by Satyam1923** [comment]
@Khushi-Pushkar make a dummy Firebase project and use it's config in firebase.js in frotend auth folder.
