### ISSUE TITLE
Feat:Components for Login, Sigin page

### ISSUE THREAD

**Issue by Venkatknight2295** [Satyam1923/Spring-Music-Player#42]
### Describe the feature

ADDING the nav bar and adding the suggested songs @Satyam1923 @

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/118790430/8639341b-28bd-4d05-a320-af1e10215313)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by Satyam1923** [comment]
@Venkatknight2295 if you want to work on it then you have to prepare different react components for it.

**Comment by Venkatknight2295** [comment]
@Satyam1923 sure what components you want me to build

**Comment by Satyam1923** [comment]
@Venkatknight2295 check figma design

**Comment by Venkatknight2295** [comment]
ok i will do the signin and create an account page does it work??

**Comment by Venkatknight2295** [comment]
Thank you

**Comment by Anushaedubilli** [comment]
Hii @Satyam1923 
I am interested to do this project can you please assign this task to me.
