### ISSUE TITLE
Feat: Custom cursor

### ISSUE THREAD

**Issue by chaanakyaaM** [Satyam1923/Spring-Music-Player#420]
### Describe the feature

The website is cool, but it can be more attractive and professional by adding custom integrative cursor.

I would like to add that custom cursor.

### Add ScreenShots

![Screenshot (258)](https://github.com/Satyam1923/Spring-Music-Player/assets/131477601/a28a90db-942f-4ad6-ad98-ada262fbd787)

Just like this, which has a trail effect.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
Can you explain a little bit

**Comment by chaanakyaaM** [comment]
Uploading Cursor Trail Effect - Personal - Microsoft​ Edge 2024-06-23 08-49-08.mp4…

**Comment by chaanakyaaM** [comment]
In this way

https://github.com/Satyam1923/Spring-Music-Player/assets/131477601/f421451d-7b67-40be-83b4-2154e12187e9

**Comment by mehrun171** [comment]
@Subhajit098 Please assign me sir

**Comment by Subhajit098** [comment]
too fancy @chaanakyaaM

**Comment by chaanakyaaM** [comment]
But @Subhajit098  this feature makes your website more attractive.

**Comment by chaanakyaaM** [comment]
ok, shall i make the website SEO friendly by adding appropriate meta tags including properties, description and keywords?
(it can be done in react also)
