### ISSUE TITLE
Feat: Addition of feedback form in nav bar

### ISSUE THREAD

**Issue by CoderGirl2844** [Satyam1923/Spring-Music-Player#421]
### Describe the feature

Addition of feedback form will help us improvise the website

### Add ScreenShots

![Screenshot 2024-06-23 011814](https://github.com/Satyam1923/Spring-Music-Player/assets/155231566/084b9ee1-5023-477c-8470-84c133f8ba01)
I will add rate us button beside login button

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by minakshikr7** [comment]
I would like to work on this issue. Please assign this task to me under @GSSoC24

**Comment by CoderGirl2844** [comment]
@minakshikr7 I am working on this issue

**Comment by CoderGirl2844** [comment]
@Satyam1923 assign me this issue under GSSOC'24

**Comment by minakshikr7** [comment]
@Satyam1923 Please assign me this issue under @GSS0C24
