### ISSUE TITLE
BUG: the burger icon toggle menu doesn't work 

### ISSUE THREAD

**Issue by RahulK4102** [Satyam1923/Spring-Music-Player#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/119075798/b1b38013-3a71-4fc9-9e3f-a8f8fb7a941e)
the burger icon toggle does not work

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@RahulK4102 can you explain this more briefly.

**Comment by RahulK4102** [comment]
yeah sure on clicking on that burger icon it should hide or show the side menu options like home , search

**Comment by shashbh18** [comment]
I would love to work on it.Please assign this issue to me.
