### ISSUE TITLE
Feat: Make `Home` responsive 

### ISSUE THREAD

**Issue by dhruv8433** [Satyam1923/Spring-Music-Player#426]
### Describe the feature

@Satyam1923 

check this out,

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/913d475f-d07e-4f3d-a1b1-ea2510673ca9)

we can make home page responsive something like this

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/a6249690-688e-4c3c-a854-5aad5ab4ae34)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
issue #406

**Comment by minakshikr7** [comment]
I would like to work on this issue. Please assign this task to me under @GSSoC24
