### ISSUE TITLE
BUG: validate contact page

### ISSUE THREAD

**Issue by Saimanjari777** [Satyam1923/Spring-Music-Player#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The contact page is not validated
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/130165687/afd9033d-f2b0-4ab5-9f59-56fdfad17ce2)
Please assign this issue to me @Satyam1923 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
Are you going to validate email using a regex expression ?

**Comment by Saimanjari777** [comment]
@Subhajit098 I want to validate without regex expression using required and changing input type format but if you want me to use regex then I will do so.

**Comment by Subhajit098** [comment]
@Saimanjari777 Ok implement it in your way
