### ISSUE TITLE
BUG: Back button missing

### ISSUE THREAD

**Issue by Saimanjari777** [Satyam1923/Spring-Music-Player#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The back button is missing in all the pages.
I would like to add it according to the theme of the website.
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/130165687/3ff71498-b4d7-45a5-92fd-e5b9afeab108)

Please assign this issue to me @Satyam1923 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
Go ahead !

**Comment by shashbh18** [comment]
I would love to work on it.Please assign this issue to me.

**Comment by Subhajit098** [comment]
@Saimanjari777 can you complete this in 1-2 days ?
