### ISSUE TITLE
Feat:Adding the login and making the UI look better 

### ISSUE THREAD

**Issue by Venkatknight2295** [Satyam1923/Spring-Music-Player#43]
### Describe the feature

Adding the login page @Satyam1923 @

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/118790430/3ee9a8cb-f3bd-482b-ae6f-07766e29bc78)
no login page 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
This issue already being operated.

**Comment by Aman0413** [comment]
I will improve this using tailwind css.

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.
