### ISSUE TITLE
BUG: The login page css is disturbed

### ISSUE THREAD

**Issue by Aman91667** [Satyam1923/Spring-Music-Player#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the login page is not managed properly. I want to reshape this page
![Screenshot_24-6-2024_125315_spring-music-player vercel app](https://github.com/Satyam1923/Spring-Music-Player/assets/142434400/8b7d1848-2fad-4c37-90f9-f4682ead26f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aman91667** [comment]
@Satyam1923, I want to work on this bug.

**Comment by Satyam1923** [comment]
@Aman91667 do you want to change the design of it also.

**Comment by Aman91667** [comment]
yes

**Comment by Aman91667** [comment]
i am anable to complite please unassign me
