### ISSUE TITLE
Feat: Adding functionality to the genres button

### ISSUE THREAD

**Issue by anwesha2002** [Satyam1923/Spring-Music-Player#431]
### Describe the feature

There is no functionality to the genres button. those are only for show. I want to add a filter upon selection a genre.

### Add ScreenShots

![Screenshot 2024-06-25 045822](https://github.com/Satyam1923/Spring-Music-Player/assets/116761608/15440d30-2eca-4d66-b2d7-431cb9eaabb0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
@anwesha2002 How are you going to classify the songs based on their genres ?
