### ISSUE TITLE
BUG: X axis overflow

### ISSUE THREAD

**Issue by anwesha2002** [Satyam1923/Spring-Music-Player#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The x- axis overflow in the website in UI that is not as intended

https://github.com/Satyam1923/Spring-Music-Player/assets/116761608/662c9e0e-e94a-47e0-80ee-eb4edbae29b8

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
This issue is not so concerning right now . If needed , we will think of assigning you
