### ISSUE TITLE
Feat: Adding artist page

### ISSUE THREAD

**Issue by anwesha2002** [Satyam1923/Spring-Music-Player#433]
### Describe the feature

currently the artist page is showing coming soon . I want to add a fully working artist page

### Add ScreenShots

![Screenshot 2024-06-25 050223](https://github.com/Satyam1923/Spring-Music-Player/assets/116761608/58a766ff-1e79-4aec-8918-fc8c3a5744db)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
What are you going to implement ? Give some info @anwesha2002

**Comment by anwesha2002** [comment]
@Subhajit098 in the API there are options for getting artist's song. so by calling that api and retrieving data and showing it to the frontend I will make this entire artist page

**Comment by Subhajit098** [comment]
Ok go ahead
