### ISSUE TITLE
BUG: Improve Login Page UI 

### ISSUE THREAD

**Issue by rohit-yadavv** [Satyam1923/Spring-Music-Player#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/126584837/44ecd916-1ddd-46b2-b141-61f755e90edd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
Can you give a overview/demo of the login page ?

**Comment by rohit-yadavv** [comment]
@Subhajit098 will align form properly and will also make it responsive for all types of screen

**Comment by rohit-yadavv** [comment]
@Subhajit098  please assign it to me

**Comment by Subhajit098** [comment]
#439

**Comment by rohit-yadavv** [comment]
__
