### ISSUE TITLE
Feat: UI of recently played tiles

### ISSUE THREAD

**Issue by rohit-yadavv** [Satyam1923/Spring-Music-Player#436]
### Describe the feature

want to improve ui of recently played tiles

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/126584837/17a727a4-e5b4-44cb-836d-500304bc8325)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
Provide some overview of the changes you are going to make @rohit-yadavv

**Comment by rohit-yadavv** [comment]
@Subhajit098  like pictures are not placed properly as there is no padding between pic and tile

**Comment by rohit-yadavv** [comment]
@Subhajit098 please mention level to issue
