### ISSUE TITLE
BUG: Not Responsive for small screens

### ISSUE THREAD

**Issue by rohit-yadavv** [Satyam1923/Spring-Music-Player#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/126584837/e21aa96f-4841-46ad-805d-fd45998351d2)

i want to work on this issue will make website responsive for all types of screens from mobile -  laptop

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
Issue #406

**Comment by rohit-yadavv** [comment]
Can I work on this

**Comment by Subhajit098** [comment]
@rohit-yadavv Keep checking the status of #406 . If it isn't completed on time, it could be assigned to you.
