### ISSUE TITLE
No proper UI of email page.

### ISSUE THREAD

**Issue by Sowmyatiwari** [Satyam1923/Spring-Music-Player#439]
### Describe the feature

The UI of  email page is not looking good. there is a huge gap between the email text and the placeholder of email . I want to change the ui of email page.  

### Add ScreenShots

![emailgssoc](https://github.com/Satyam1923/Spring-Music-Player/assets/133684872/0281961a-9abe-4a03-b43a-044cbb772a95)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Sowmyatiwari fix it asap.

**Comment by Sowmyatiwari** [comment]
yes , sir working on it .

**Comment by Sowmyatiwari** [comment]
thank you sir , working on it .

**Comment by Sowmyatiwari** [comment]
hello @Satyam1923 , I am trying to run the server , but its not running , the blank page is opened after I am trying to run it on local server , I have made the changes in the code , but I am unable to see it due to this issue. please help me with this , so I can merge the project asap.
![spring](https://github.com/Satyam1923/Spring-Music-Player/assets/133684872/b15b5626-d466-4ece-8392-8906767a8fbe)

**Comment by Sowmyatiwari** [comment]
@Satyam1923 please respond .

**Comment by Satyam1923** [comment]
@Sowmyatiwari make a dummy firebase project use it's config in firebase.js

**Comment by Sowmyatiwari** [comment]
okay sir

**Comment by pani2004** [comment]
@Satyam1923 is the issue still open?

**Comment by Sowmyatiwari** [comment]
@pani2004 I am working on it .
