### ISSUE TITLE
Feat: Adding Register button at home page

### ISSUE THREAD

**Issue by mehrun171** [Satyam1923/Spring-Music-Player#440]
### Describe the feature

There is no Register option at home page...login is available but when we go to login then the register button is available...so to make it more user friendly lets add register button at home page itself

Assign me this issue @Satyam1923 

### Add ScreenShots

![Screenshot 2024-06-26 230253](https://github.com/Satyam1923/Spring-Music-Player/assets/116735695/09f9cf1b-90b3-461f-96b6-51ea07fce275)
![Screenshot 2024-06-26 230455](https://github.com/Satyam1923/Spring-Music-Player/assets/116735695/8c773033-7b24-4817-9273-7e0f703fb6ef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
This is not needed @mehrun171

**Comment by minakshikr7** [comment]
I would like to work on this issue. Please assign this task to me under @GSSoC24
