### ISSUE TITLE
BUG: Unused buttons at homepage tab

### ISSUE THREAD

**Issue by mehrun171** [Satyam1923/Spring-Music-Player#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have a two non-interactive unused buttons at the home page tab (Added a screenshot check it)
i would like to remove it and if needed replace them with any necessary buttons as per ur requirement

![Screenshot 2024-06-26 230805](https://github.com/Satyam1923/Spring-Music-Player/assets/116735695/8e682529-910c-4615-9629-eb30228bcd77)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@mehrun171 those are not unnecessary those are just nonfunctional for now.,

**Comment by mehrun171** [comment]
Can I make them functional?
Mehrun Shamshi

**Comment by mehrun171** [comment]
Can I make them functional??? @Satyam1923

**Comment by Subhajit098** [comment]
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/77979245/3faf92a9-5c7b-4025-a543-f6ecb22d2df0)


@mehrun171 Can you try to improve the hamburger menu icon, just like upon clicking  it will open the below button section ?

**Comment by mehrun171** [comment]
Ok i will work on it...please assign me the task
