### ISSUE TITLE
Feat: Light/Dark theme toggle button

### ISSUE THREAD

**Issue by mehrun171** [Satyam1923/Spring-Music-Player#442]
### Describe the feature

i would like to add a dark/light theme toggle button which can enable user to have theme of their own to use as per their usability

### Add ScreenShots

![Screenshot 2024-06-26 230455](https://github.com/Satyam1923/Spring-Music-Player/assets/116735695/e1ad3995-eb87-4316-90ba-9c915a859c38)
Currently has only dark theme...so add a toggle button for Light/Dark theme

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
Light theme will not be a good idea to implement

**Comment by Subhajit098** [comment]
Light theme will not be a good idea to implement

**Comment by mehrun171** [comment]
But generally these days all websites have theme toggle option na
