### ISSUE TITLE
Feature 🌟: Add "Licensing Page" Reflecting "MIT Licence" 

### ISSUE THREAD

**Issue by aslams2020** [Satyam1923/Spring-Music-Player#443]
### Describe the feature

Hey @Satyam1923 ,
Here is the feature request i want to implement - 

To provide clear information about the licensing of the website's content and code, I propose to **add a dedicated "Licensing Page"** that reflects the use of the **MIT License.** 
This page will help users understand the terms under which they can use, modify, and distribute the website's resources.

**What will i do -**
1. Develop a new page titled "Licensing" accessible from the main navigation menu or footer.
2. Include a brief introduction explaining the importance of licensing.
3. Provide the full text of the MIT License.

### Add ScreenShots

Here's How it will look like.

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/131389695/db27aaa5-fea7-428a-a1de-0f70b59e7440)

( I will add this page link and text in the footer section of home page as "Licensing" - )

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/131389695/1963fde4-9a39-4be7-a5f7-2e7473375522)

@Satyam1923 , Could you please assign me this issue under GSSoC'24? 
I'd like to work on this.
thankyou!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@aslams2020 fine.

**Comment by aslams2020** [comment]
hey @Satyam1923 ,
Could you please help me with this - I am unable to see live preview of the project, i followed the readme.md file instruction commands for frontend and backend. After that i'm seeing the preview as a black screen only.
please take a look - 

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/131389695/f20fb98a-9121-4dc1-9769-35c13c7078b1)


this is the live preview - 

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/131389695/f2f5baf8-6fd7-4d43-b207-a166fbb02f02)

please tell me if i left something.

**Comment by aslams2020** [comment]
@Satyam1923 Help me with this pls

**Comment by Satyam1923** [comment]
@aslams2020 make a dummy firebase project and use it's config.
