### ISSUE TITLE
BUG: Login page elements do not look organised

### ISSUE THREAD

**Issue by Rajul-29** [Satyam1923/Spring-Music-Player#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login page elements positioning can be changed so it looks more organized
link: https://spring-music-player.vercel.app/login

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Rajul-29** [comment]
Hey @Satyam1923!
I would like to work on this issue.

**Comment by Subhajit098** [comment]
Issue #435

**Comment by minakshikr7** [comment]
I would like to work on this issue. Please assign this task to me under @GSSoC24

**Comment by rohit-yadavv** [comment]
@Subhajit098 please allow me to create this issue. if it is not getting fixed as issue is 4 days old and still no improvement
