### ISSUE TITLE
Feat: Update About Us Page Responsive design

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Satyam1923/Spring-Music-Player#446]
### Describe the feature

I want to improve the design of the about us page in the responsive mobile mode. I want to contribute under GSSOC' 24.

### Add ScreenShots

Now : 

![Screenshot 2024-06-28 183504](https://github.com/Satyam1923/Spring-Music-Player/assets/123104247/2fab0764-62fe-4b7e-8384-d0138be263cd)

What I wish to make : 

![Screenshot 2024-06-28 183454](https://github.com/Satyam1923/Spring-Music-Player/assets/123104247/1dffbd0a-4e06-4717-846c-3f4c302d1bc0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@ParnaRoyChowdhury777 go ahead

**Comment by saurabhsingh720** [comment]
@ParnaRoyChowdhury777 
Make sure that no any other responsiveness get not changed

**Comment by ParnaRoyChowdhury777** [comment]
> @ParnaRoyChowdhury777 
> Make sure that no any other responsiveness get not changed

Sure...
