### ISSUE TITLE
Feat: Design Artist Page

### ISSUE THREAD

**Issue by dhruv8433** [Satyam1923/Spring-Music-Player#448]
### Describe the feature

@Satyam1923 

we can design `/artist/:id` page for particular artist page

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/f5970d84-8d2e-4971-b515-d54f37edab52)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@dhruv8433 
Elaborate

**Comment by dhruv8433** [comment]
@saurabhsingh720 


like in home page when we click on artist we got songs from that particular artist
same here, we can design new route `/artist/:id` for that

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/76e69273-e673-479b-bd41-09958df226b4)

**Comment by saurabhsingh720** [comment]
@dhruv8433 
How long u take to complete the task?

**Comment by dhruv8433** [comment]
@saurabhsingh720 

Within 2 days

**Comment by saurabhsingh720** [comment]
@dhruv8433  go ahead
