### ISSUE TITLE
BUG:Like not working .

### ISSUE THREAD

**Issue by Subhams-GIT** [Satyam1923/Spring-Music-Player#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The like is not working its a svg not a button .
Liked songs should be there in like category.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
How will you store the liked songs of different users ?

**Comment by Subhams-GIT** [comment]
We can use mongodb for that

**Comment by Subhajit098** [comment]
What ? Elaborate it.

**Comment by Subhams-GIT** [comment]
In the firebase db field can be added to store liked songs by users in the users field like how the songs played are stored .
