### ISSUE TITLE
Feat: Able to create own playlists and able to save other people playlists

### ISSUE THREAD

**Issue by Chelseasingla1** [Satyam1923/Spring-Music-Player#45]
### Describe the feature

I would like to add a feature where one can create its own playlists and save other peope playlists too.
I would like to work on this issue under GSSoC'24.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/129886894/3aef4b1e-8ac0-4c72-b3e3-e889aeffcc45)
maybe by adding a plus or add button here 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by Satyam1923** [comment]
@Chelseasingla1 how are you going to implement this feature since firebase backend is not ready yet. Please explain it.

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 how are you going to implement this feature since firebase backend is not ready yet. Please explain it.

@Satyam1923 currently we can store it in local storage and for entering lists one can use forms, where user can enter name of playlists. We can store in json format for time being.

**Comment by Satyam1923** [comment]
@Chelseasingla1 I don't think this is relevant.

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 I don't think this is relevant.

@Satyam1923 Then i can first connect it to firebase and then do the storage purpose if you want to i have worked on firebase before or maybe we can use PostgreSQL for storage purposes.

**Comment by Priyanka-Ray-Choudhury** [comment]
Hi @Chelseasingla1, I'm ready to take on the task of creating  own playlists and able to save other people playlists section. Please assign it to me with the GSSOC tag. Thanks!

**Comment by Satyam1923** [comment]
@Chelseasingla1 you can work on this issue but with firebase.

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 you can work on this issue but with firebase.

@Satyam1923  okay sure

**Comment by saurabhsingh720** [comment]
@Chelseasingla1  u can do this task , but u have to do this as soon as possible. Failing to do leads to assigning to others.

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 u can do this task , but u have to do this as soon as possible. Failing to do leads to assigning to others.

@saurabhsingh720 Yes thanks for assigning
