### ISSUE TITLE
BUG:  Add real time liked song

### ISSUE THREAD

**Issue by Varsani2520** [Satyam1923/Spring-Music-Player#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Satyam1923 

we can add liked song real time to display in `/liked-song` route

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/137641079/c622991b-1cb8-4976-a29e-7d5e6fcb2bf9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
Elaborate @Varsani2520

**Comment by Varsani2520** [comment]
@Subhajit098 ,when user click on like icon then that song item store in database and `liked-song` route display user liked song from database specific

**Comment by Varsani2520** [comment]
@Satyam1923 ,please assign me
