### ISSUE TITLE
FIX: Search bar UI

### ISSUE THREAD

**Issue by rohit-yadavv** [Satyam1923/Spring-Music-Player#452]
### Describe the feature

search bar is too big and even forward and back button ui if not optimal

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/126584837/85738d16-8039-40c5-ac52-e467e2de513c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@rohit-yadavv you can work on it.
