### ISSUE TITLE
Fix: Fix labels size

### ISSUE THREAD

**Issue by rohit-yadavv** [Satyam1923/Spring-Music-Player#453]
### Describe the feature

Label size is too big not optimal

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/126584837/dfeeb208-1317-4f49-8426-2331704ba18d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@rohit-yadavv you can work on it.
