### ISSUE TITLE
BUG: Login button not working

### ISSUE THREAD

**Issue by rohit-yadavv** [Satyam1923/Spring-Music-Player#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Nothing is happening when clicked on Login button 

 
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/126584837/268e6fc0-f09c-40a8-a250-e8dd55e45781)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@rohit-yadavv working .
