### ISSUE TITLE
Feat: Add Contributors Page to Display Project Contributors

### ISSUE THREAD

**Issue by pani2004** [Satyam1923/Spring-Music-Player#461]
### Describe the feature

The contributors page will display the details of the contributors who have contributed to this project

### Add ScreenShots

![04 07 2024_14 29 42_REC](https://github.com/Satyam1923/Spring-Music-Player/assets/154724111/8b4eab33-4df4-4b09-8485-84f58b3b1d2d)
Will add it in the footer 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pani2004** [comment]
@Satyam1923 Can I work on this?

**Comment by Satyam1923** [comment]
@pani2004 fine.
