### ISSUE TITLE
Feat: login page is not good 

### ISSUE THREAD

**Issue by siddhant-2002** [Satyam1923/Spring-Music-Player#462]
### Describe the feature

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/112260375/8562604e-46df-40fc-a032-b9fef0b15eb0)

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/112260375/95ea6f82-66d2-4504-9c9a-2b6ce60f825a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by minakshikr7** [comment]
Please assign me this issue under @GSS0C24

**Comment by siddhant-2002** [comment]
Hey any updates

**Comment by saurabhsingh720** [comment]
@siddhant-2002 
Show your design how it looks.

**Comment by siddhant-2002** [comment]
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/112260375/727a4a36-21b3-4416-94cf-435a061193d9)

**Comment by saurabhsingh720** [comment]
@siddhant-2002 
Your design is good.
U have to make sure that the responsiveness in mobile mode cannot change.

**Comment by siddhant-2002** [comment]
Yes ofcourse it will be responsive

**Comment by siddhant-2002** [comment]
Hey @saurabhsingh720 assign  issue to me as soon as possible so I will start to work on it

**Comment by saurabhsingh720** [comment]
@siddhant-2002 go ahead
