### ISSUE TITLE
BUG: song after the first song don't play on clicking.

### ISSUE THREAD

**Issue by sakshii00** [Satyam1923/Spring-Music-Player#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When searching, only the first song played and the subsequent songs when clicked can't be played.

I'd like to work on this issue under GSSOC'24. Please assign it to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@sakshii00 where did you check this thing on your own machine or current demo web.

**Comment by sakshii00** [comment]
I checked on my machine, using the steps provided.

**Comment by sakshii00** [comment]
I just checked the demo, it is working there, I'm sorry for the trouble.
