### ISSUE TITLE
BUG: Home page music player doesn't function home page loads

### ISSUE THREAD

**Issue by The-Phoenics** [Satyam1923/Spring-Music-Player#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The music player on home page works only if a song is selected from `Top Songs` section. The `Reminder` song is hard coded for now, so the music player doesn't function on first time the home page loads.

**Expected behaviour*: As the home page loads the first song from the`Top Songs`  section should be updated on music player and should be playable

![dummy-musicplayer](https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/28932693-a458-4a02-9c34-d35494b586e0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@The-Phoenics as the page loads load play the song from recent played list from firebase?

**Comment by The-Phoenics** [comment]
> @The-Phoenics as the page loads load play the song from recent played list from firebase?

Yes, and if user is not logged in we can load the first song from top songs list? But how can I get the user's last played song from api?

**Comment by Satyam1923** [comment]
You won't get from the api you need to access firebase firestore for it.
