### ISSUE TITLE
🌟 Feature: Add a Scroll "Progress Indicator Bar"

### ISSUE THREAD

**Issue by Tejashri-Taral** [Satyam1923/Spring-Music-Player#475]
### Describe the feature

Hey @Satyam1923  ,

I want to add a "Scroll Down Progress Bar"

This feature adds a scroll down progress bar to the website, which visually indicates the user's progress as they scroll down the page.
The progress bar enhances user experience by providing a clear visual cue of their location on the page and how much content remains to be viewed.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/160386036/28ea3046-b1a4-4eac-b952-f6edd7e0b04f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
Try to keep the "progress bar" thin @Tejashri-Taral
