### ISSUE TITLE
Adding more song genres

### ISSUE THREAD

**Issue by Aditijainnn** [Satyam1923/Spring-Music-Player#476]
### Describe the feature

Adding more genres of music in in genre section like
1) Metal: Known for its heavy guitar riffs, powerful drumming, and often aggressive vocals.
2)Folk: Traditional music that tells stories and reflects cultural heritage, often with acoustic instruments.
3)Jazz: Known for improvisation, complex harmonies, and a strong emphasis on instrumental performance
4)Folk: Traditional music that tells stories and reflects cultural heritage, often with acoustic instruments.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/144632601/97b5ed0a-6588-4dba-934c-4dacd7b62f67)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Aditijainnn these don't work you know that right try to think something how to get  personalize songs based on genre.
