### ISSUE TITLE
BUG: Navbar alignment 

### ISSUE THREAD

**Issue by theeayushkumar** [Satyam1923/Spring-Music-Player#477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Navbar alignment not looking good
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/128235540/75ee94db-504d-402b-96f7-ac6579809f79)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryan-joh** [comment]
@Satyam1923 please assign this to me i can handle this

**Comment by vaishnavi-jais** [comment]
Hi 

I’ve noticed that the alignment of the navigation bar doesn’t look quite right and could benefit from some adjustments. I’d like to work on fixing the alignment issue to improve the overall layout and user experience.

Could you please assign me to this task or provide guidance on how to get started? I’m eager to contribute to resolving this issue as part of my GSoC project and would appreciate the opportunity to help out.

Thank you for your consideration!
