### ISSUE TITLE
Feat: Adding Hover effect on the Thumb Button

### ISSUE THREAD

**Issue by Kcode15** [Satyam1923/Spring-Music-Player#478]
### Describe the feature

Adding Hovering effect on the thumb button which is displayed on the Song will make the site more interactive

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/129003839/61ff3672-b82c-44fc-8dc1-da06e8c2c7c3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@Kcode15 
Go ahead
