### ISSUE TITLE
BUG: Improve the design of login page

### ISSUE THREAD

**Issue by JagjeetChauhan** [Satyam1923/Spring-Music-Player#481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login page design is very poor, it needs complete change.
![image](https://github.com/user-attachments/assets/228f31c5-32eb-4276-9cb7-1d50297e9fea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
#462
