### ISSUE TITLE
[Feature Request] : ✨ Add a Page Scroll Progress Bar at the Top of Your Startup Webpage

### ISSUE THREAD

**Issue by TheNikhilRaj** [Satyam1923/Spring-Music-Player#484]
### Describe the feature

Explain feature request
Hey @Satyam1923  ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no Page Scroll Progress Bar at the Top of Your Startup Webpage , which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

### Add ScreenShots

![343870881-7f17e9d3-41c5-4fb0-a558-caf334552764](https://github.com/user-attachments/assets/9e54a99c-8157-4574-a391-41d30a011072)

Could you please assign me this issue under gssoc'24 ?

GSSOC'24
@Satyam1923 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
Issue #475
