### ISSUE TITLE
Feat: Adding Chatbot to website

### ISSUE THREAD

**Issue by Ojas-Arora** [Satyam1923/Spring-Music-Player#485]
### Describe the feature

@Satyam1923  I want to add chatbot to website. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-07-12 164605](https://github.com/user-attachments/assets/513a4ec1-553d-4b58-9111-d8f71937c69b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
@Ojas-Arora  Can you explain a bit of what and how are you going to implement this feature before we could assign you this

**Comment by Ojas-Arora** [comment]
@Subhajit098 I will take the help of tidio for making the chatbot.

**Comment by Ojas-Arora** [comment]
@Subhajit098 I can also make using another method. Can I start working on this?
