### ISSUE TITLE
Feat: Hover effect in genres

### ISSUE THREAD

**Issue by Priyal208** [Satyam1923/Spring-Music-Player#486]
### Describe the feature

The genres section looks very plain and static , i can add hover effect which will make it pop up so that it looks more appealing and atttractive. I will add glowing borders on hover and glow effect based on color which will make it stand out

### Add ScreenShots

![Screenshot 2024-07-16 155920](https://github.com/user-attachments/assets/ebbf7a28-9d7a-4483-bc14-c0951f71ca75)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@Priyal208 so it
