### ISSUE TITLE
Feat:register form design

### ISSUE THREAD

**Issue by siddhant-2002** [Satyam1923/Spring-Music-Player#488]
### Describe the feature

register form is not looking good 
previously I have fixed login form but I haven't seen register form so I want to change its design

i want to make it like this 

![Screenshot 2024-07-13 130229](https://github.com/user-attachments/assets/eee2f91d-6e72-4bb2-b83a-724c2cbaced7)

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ac390ff9-d60a-4e7c-93e0-99d29319f0bd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@siddhant-2002  go ahead
