### ISSUE TITLE
Feat:Add animation when liked button is clicked in the current playing song section

### ISSUE THREAD

**Issue by Riddhi162** [Satyam1923/Spring-Music-Player#492]
### Describe the feature

The like button when clicked doesnt show any animation or anything which doesnt throw any indication whether the song is liked or not this can be improved by giving it some animation.Kindly assign me this under GSSOC'24.

### Add ScreenShots

https://github.com/user-attachments/assets/055ae752-3f28-41a5-b340-b1c28326f296

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@Riddhi162 go ahead
