### ISSUE TITLE
Feat: Add Dark and Light mode theme option. 

### ISSUE THREAD

**Issue by kou95shik** [Satyam1923/Spring-Music-Player#497]
### Describe the feature

I will add the feature in nav bar that can switch dark mode to light mode and vice versa.

### Add ScreenShots

Will add after work.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@kou95shik go ahead and complete the task asap.

**Comment by vaishnavi-jais** [comment]
Hi 

I’m planning to add a feature to the navigation bar that allows users to switch between dark mode and light mode seamlessly. This enhancement will improve user experience by providing a quick and easy way to toggle themes based on user preference.

I’m eager to contribute this feature and would appreciate the opportunity to work on it as part of my GSoC project. Could you please assign me this task or provide guidance on how to proceed? I’m excited to help enhance the app with this functionality.

Thank you for your support!
