### ISSUE TITLE
Feat: Search page - Autoplay next song after song ends

### ISSUE THREAD

**Issue by The-Phoenics** [Satyam1923/Spring-Music-Player#499]
### Describe the feature

Currenlty the music player stops when the song played from song search list ends, it would be better to have the next song form the list autoplay.

### Add ScreenShots

![songs](https://github.com/user-attachments/assets/7c5701e5-186b-4f7c-9540-47654f17fdf4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by The-Phoenics** [comment]
Hey @Satyam1923 @saurabhsingh720 
Can you please assign me this issue for GSSoC'24.

**Comment by saurabhsingh720** [comment]
@The-Phoenics go ahead 
 complete it asap

**Comment by The-Phoenics** [comment]
@saurabhsingh720 Can you merge this one first?
https://github.com/Satyam1923/Spring-Music-Player/pull/493
