### ISSUE TITLE
Like button : we can add like button that displays the number of likes for the song

### ISSUE THREAD

**Issue by sahithi000** [Satyam1923/Spring-Music-Player#50]
### Describe the feature

@Satyam1923 can you please assign this task for me under GSSOC24

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/105491821/bc924948-3f7b-4e1e-8b37-cd32a85c17ee
![Like_button](https://github.com/Satyam1923/Spring-Music-Player/assets/105491821/c4bf5f09-0047-499a-8cd3-1b693011b715)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @Varnika2526, I'd like to work on adding a like button feature that displays the number of likes for the song. Could you please assign this task to me with the GSSOC tag? Thanks!

**Comment by saurabhsingh720** [comment]
@sahithi000  do this task sooner.

**Comment by sahithi000** [comment]
@saurabhsingh720 sure will do this

**Comment by sahithi000** [comment]
@saurabhsingh720  is this all or something else missing 
![Screenshot (102)](https://github.com/Satyam1923/Spring-Music-Player/assets/105491821/af5648da-f834-47a1-ba73-ed265b5cae19)

**Comment by saurabhsingh720** [comment]
@sahithi000 just type the name of song and search it, then u will get interface

**Comment by sahithi000** [comment]
@saurabhsingh720 This is all i am able to render - is there something missing
![Uploading Screenshot (104).png…]()

**Comment by saurabhsingh720** [comment]
@sahithi000 Go for it and add this feature
