### ISSUE TITLE
BUG: Sidebar Not Fixed on Home and Liked Pages

### ISSUE THREAD

**Issue by saurabhbakolia** [Satyam1923/Spring-Music-Player#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The sidebar on the home page and the liked page are not fixed. The sidebar size is inconsistent between the two pages, larger on the home page and slightly smaller on the liked page. This impacts the user experience as the sidebar should remain fixed and consistently sized while scrolling through the content.
![spring_music_player_ux_fix](https://github.com/user-attachments/assets/65141bb0-59fc-4c29-8680-b5bf1c8bf1d0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ananyajain2004** [comment]
I can resolve this issue , plz assign me under Gssoc'24 .

**Comment by vaishnavi-jais** [comment]
Hi 

I’ve noticed that the sidebar on the home page and the liked page has inconsistent sizing. The sidebar appears larger on the home page and slightly smaller on the liked page, which affects the user experience. For a more cohesive and seamless user interface, the sidebar should be fixed and consistently sized across all pages.

I’d like to work on resolving this issue to ensure a uniform and fixed sidebar size while scrolling through content. Could you please assign me to this task or provide guidance on how to get started? I’m eager to contribute to this improvement as part of my GSoC project.

Thank you for your support!

**Comment by vaishnavi-jais** [comment]
I’m ready to tackle this issue and ensure the sidebar is consistently fixed and seamlessly sized across all pages. Can you assign me this task for GSoC '24? I’m eager to dive in and bring a touch of uniformity to our app's user interface.

Looking forward to your response!
