### ISSUE TITLE
Want to Make it Responsive for Mobile screen 

### ISSUE THREAD

**Issue by Utsavladia** [Satyam1923/Spring-Music-Player#503]
### Describe the feature

It should be responsive for the mobile screen too 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/7c25687e-cae0-4997-9948-f0176a68e3ca)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Utsavladia** [comment]
@saurabhsingh720 
sure..
I would take 1 or maximum 2 days for it

**Comment by Utsavladia** [comment]
@saurabhsingh720 
sure..
I would take 1 or maximum 2 days for it

**Comment by saurabhsingh720** [comment]
@Utsavladia do it and provide your PR

**Comment by Utsavladia** [comment]
@saurabhsingh720 
kindly review this

**Comment by vaishnavi-jais** [comment]
've noticed that our current feature isn't quite hitting the mark on mobile screens—it’s like trying to fit a square peg into a round hole! To ensure our app looks and functions beautifully on all devices, I’m eager to make it fully responsive for mobile users.

I’m ready to dive into this and bring a sleek, adaptable design to our mobile experience. Can you please assign me this task for GSoC '24? I’m excited to optimize our app for a seamless mobile experience!

Thanks a lot for considering this!

**Comment by Utsavladia** [comment]
@vaishnavi-jais 
I have already created a PR for this issue and its pending to get reviewed..
you can try finding other issues which is open

**Comment by Utsavladia** [comment]
@saurabhsingh720  @Satyam1923 
Kindly merge this PR before GSSOC ends 😌
