### ISSUE TITLE
Fix the Sidebar and Music player position to have professional look

### ISSUE THREAD

**Issue by Utsavladia** [Satyam1923/Spring-Music-Player#504]
### Describe the feature

It should be fixed on both sides to have a good scroll and browsing view of musics

### Add ScreenShots

![image](https://github.com/user-attachments/assets/3fa7b096-db14-4c4a-a7f2-db70b9709c43)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@Utsavladia please provide a demo video to show your issue.

**Comment by Utsavladia** [comment]
@saurabhsingh720 
Only the Middle part will be scrolled....
left navbar and right music player will be fixed.
as we can see in this twitter website


https://github.com/user-attachments/assets/36d20681-5acf-43dd-8f20-f34c28ecf441
