### ISSUE TITLE
Feat: Load with last played song

### ISSUE THREAD

**Issue by The-Phoenics** [Satyam1923/Spring-Music-Player#505]
### Describe the feature

Currently the music player loads with the song in the top song list (feature added in this [PR](https://github.com/Satyam1923/Spring-Music-Player/pull/479)). If a user is logged in the music player should be loaded with the last song that user played.

### Add ScreenShots

![347808632-49055f30-8322-4a15-b7bc-fad414d609c9](https://github.com/user-attachments/assets/14d2a841-4530-4689-88d5-76ffb9ea6029)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhsingh720** [comment]
@The-Phoenics go ahead
