### ISSUE TITLE
BUG: Navigating to the likes section music stops and changes

### ISSUE THREAD

**Issue by haseebzaki-07** [Satyam1923/Spring-Music-Player#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Navigating to the liked music sections pauses the ongoing played music. It should not change or pause the music instead keep playing the music

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit098** [comment]
How are you gonna implement it ?

**Comment by haseebzaki-07** [comment]
It can be done by keeping the music playing section static across pages like we implement sidebars and appbars.

**Comment by saurabhsingh720** [comment]
@haseebzaki-07 go ahead

**Comment by vaishnavi-jais** [comment]
I’ve noticed that navigating to the liked music sections in the app currently causes the ongoing music to pause. Ideally, the music should continue playing uninterrupted while users browse their liked tracks.

I’m very interested in working on this issue and would like to contribute a fix. Could you please assign me to this task or provide guidance on how to get started? I’m eager to help improve the user experience and ensure seamless music playback.

**Comment by haseebzaki-07** [comment]
Hey @saurabhsingh720 please review this pr
