### ISSUE TITLE
BUG: Breaking UI

### ISSUE THREAD

**Issue by The-Phoenics** [Satyam1923/Spring-Music-Player#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Satyam1923,
With the recent port into React the UI is breaking nearly between 770 - 1030 viewport width. 

Problem Screenshot:
![issue](https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/7b0997d0-53db-42d4-9ec5-04653ca374ab)

I would like to work on this for GSSoC'2024. Can you please assign this to me?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@The-Phoenics you can work on this issue .

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @Varnika2526, I'm up for fixing the "BUG: Breaking UI" issue. Could you assign it to me with the GSSOC tag? Thanks!

**Comment by The-Phoenics** [comment]
#59
