### ISSUE TITLE
ADDING A HOME PAGE 

### ISSUE THREAD

**Issue by PacemakerX** [Satyam1923/Spring-Music-Player#52]
### Describe the feature

I want to add a brand new and enthusiastic home page , to the website which will portray the feel of the website, upon a button click the , the user will be redirected to the the playback page, where they can play any song of their choice.

### Add ScreenShots

The spotify homepage, suggests some albums, and playlist and latest i hits. i want to contribute something like this 

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/124906349/cd66321e-06e3-4c0a-9f7e-c0d7137b67c9)

Another  example 
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/124906349/0c031a15-7274-44aa-b6fe-7f8e59b40293)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PacemakerX** [comment]
@Satyam1923  I would like you to kindly review my issue an , guide me forward

**Comment by Satyam1923** [comment]
@PacemakerX Designing is already begin  operated.
