### ISSUE TITLE
BUG: The app is getting break in responsiveness

### ISSUE THREAD

**Issue by mohit-bhandari45** [Satyam1923/Spring-Music-Player#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Description:- The app is breaking on checking on mobile view.

Screenshots:-
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/151373021/68f7698b-115b-4da4-ac37-8ee506e571f6)

I want to work on this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@mohit-bhandari45 fine fix it for mobile responsiveness

**Comment by Priyanka-Ray-Choudhury** [comment]
Hi @Varnika2526, could you assign me the BUG task related to the app's responsiveness? I'll take care of it with the GSSOC tag.
