### ISSUE TITLE
BUG: Unsupported keyboard key for playing the next song

### ISSUE THREAD

**Issue by Varnika2526** [Satyam1923/Spring-Music-Player#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Next Button ">>" for playing the next song does not support next key click on the keyboard.
Adding a Javascript code can make it easy for the users to play the next song
Kindly assign me this issue. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Varnika2526 Currently for playing React music component is begin used and it have limited functionality. If you can come up with a new alternative option which is better than this component feel free to contribute.

**Comment by Priyanka-Ray-Choudhury** [comment]
Hi @Varnika2526, could you assign me the task of fixing the unsupported keyboard key bug for playing the next song? Please tag it with GSSOC. Thanks!

**Comment by AmrutaJayanti** [comment]
@Varnika2526 Can you please assign me this task

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.

**Comment by Satyam1923** [comment]
@Varnika2526 any updates varnika

**Comment by Varnika2526** [comment]
@Satyam1923 I had modified the Pause/Play feature that works well by pressing "space" key on keyboard
I am attaching a clip for the same kindly review it

https://github.com/Satyam1923/Spring-Music-Player/assets/106170225/7c828c59-953a-4f7d-a94e-7d7dc2383816
