### ISSUE TITLE
[Feature] : Add Search Feature & song

### ISSUE THREAD

**Issue by sivaprasath2004** [Satyam1923/Spring-Music-Player#55]
### Describe the feature

- If the `search ` only can input i will proper search the song and sort list the song.
- if i want ready to this feature add the new feature.

## Expected Feature 

[Screencast from 2024-05-12 08-10-53.webm](https://github.com/Satyam1923/Spring-Music-Player/assets/121082414/36d4fe8f-446c-438f-bb21-1d187ee4a34f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rahulpoonia29** [comment]
@Satyam1923 I would like to work on this issue under GSsoC'

**Comment by Nandini-49** [comment]
@Satyam1923 Dear Sir, I would like to contribute to this issue as well. I think implementing this search through the omnibox using fuzzy searching techniques could help a lot, as well as proper database indexing of songs with lyrics, through the use of lyricsfind or musixmatch api could be helpful in solving this issue. 
This would allow users to find the songs using the lyrics, or even with wrong or mistyped name, incomplete lyrics, or somewhat matching lyrics. It will give the searchlist based on the closest recommendations of the search info.
This should greatly enhance the user experience, and hence, I would like to contribute to this issue and hopefully make this a better product down the line.

**Comment by Satyam1923** [comment]
@sivaprasath2004 You can work on this issue

**Comment by sivaprasath2004** [comment]
@Satyam1923 yes i do
