### ISSUE TITLE
Adding support for environment variables 

### ISSUE THREAD

**Issue by rahulpoonia29** [Satyam1923/Spring-Music-Player#57]
### Describe the feature

As the project grows, it would be nice idea to use env variables for all sensitive data.

### Add ScreenShots

![Screenshot_20240512-101410](https://github.com/Satyam1923/Spring-Music-Player/assets/140232466/f36c8777-b8f1-4d98-807e-1c06b5f863d5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rahulpoonia29** [comment]
@Satyam1923 I would like to work on this issue under GSsoC'

**Comment by Satyam1923** [comment]
@rahulpoonia29 you can take up this issue.
