### ISSUE TITLE
Change of Frontend Documentation in Readme file

### ISSUE THREAD

**Issue by Sibam-Paul** [Satyam1923/Spring-Music-Player#58]
### What's wrong with the existing documentation

In place of Frontend it is written Backend

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/158052549/ca4fd20e-2495-4389-b01e-13c1fcd93763)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

_Please assign me this issue so that I can work on it under Gssoc'24_

**Comment by Satyam1923** [comment]
@Sibam-Paul lol fine change.

**Comment by Sibam-Paul** [comment]
Doing the correction now

**Comment by Sibam-Paul** [comment]
@Satyam1923 please see the necessary changes made in the pull #64
