### ISSUE TITLE
adding mediaquery jsx component along with tailwind css screens

### ISSUE THREAD

**Issue by powerstone666** [Satyam1923/Spring-Music-Player#60]
### Describe the feature

I'll be adding a media query component that will take input prop as screen size so that in the future if we want to build components such as a navbar for various screens using media query we can give conditions and it will display only when the screen is above or below that size.

I'll also be adding a screens extension in the tailwind.js config file  along with themes so that while writing code in tailwind CSS it will be easy to write CSS for specific screen sizes

### Add ScreenShots

![Screenshot (159)](https://github.com/Satyam1923/Spring-Music-Player/assets/142788077/0f985327-9e05-4d86-a030-1140b65710b3)
like in the above image we can easily give conditions on what screen we should display so in future it will be great feature for contributors

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by powerstone666** [comment]
hyy assign this to me.......

**Comment by Satyam1923** [comment]
@powerstone666 this already being handled.

**Comment by powerstone666** [comment]
but there is no mediaquery component or screens in tailwind.css

**Comment by Satyam1923** [comment]
Yes as this is not our final design. You can take a look at the new design and raise the issue accordingly.

**Comment by powerstone666** [comment]
can i get that new design

**Comment by powerstone666** [comment]
so from final design we need to build it from scratch ya u have already builded components based on that
