### ISSUE TITLE
Change of Url in Frontend/src/app.jsx

### ISSUE THREAD

**Issue by Sibam-Paul** [Satyam1923/Spring-Music-Player#62]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

**Should be this** 
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/158052549/b5b3d30f-7c76-4ef1-9ae4-11376a1c4e02)

**In the place of**
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/158052549/f6ead941-5ec0-48ba-8592-c35c5b72e9ee)

_Please assign me this issue I wanna change it. under GSSOC'24_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Sibam-Paul the master branch is used for development on vercel and it needs some back end to fetch from so vercel url is used.
