### ISSUE TITLE
Feat: Developing the dashboard according to the figma design of home screen

### ISSUE THREAD

**Issue by Shrirangop** [Satyam1923/Spring-Music-Player#66]
### Describe the feature

--The dashboard will consist of a sidebar with search bar. 
-- Top playlist component
-- Music player component
--component for top 10
-- Button to go to profile page
--Artist component

I can develop the above page completely. I will make arrangements for frontend backend integration wherever necessary by calling necessary api's. Please assign me this issue.

### Add ScreenShots

![music](https://github.com/Satyam1923/Spring-Music-Player/assets/127132610/8eab93d7-40c1-4662-b049-c04b4a10e6d1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Shrirangop you can work on this issue.

**Comment by Manaswini123456** [comment]
@Satyam1923  Kindly assign this issue to me. As a full stack developer, I have the comprehensive knowledge and expertise required to handle it effectively.
