### ISSUE TITLE
Feat: Showing recent or newly released songs

### ISSUE THREAD

**Issue by Chelseasingla1** [Satyam1923/Spring-Music-Player#72]
### Describe the feature

I would like to add a feature where it would be visible which new songs are there.

### Add ScreenShots

Showing something like this:
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/129886894/f39eace4-9097-4d54-bb4a-0843e4b82f16)

New songs list

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chelseasingla1** [comment]
Please assign me this issue under GSSoC'24

**Comment by Satyam1923** [comment]
@Chelseasingla1 checkout new design! then describe your changes.

**Comment by jitendrac9610** [comment]
I will use API key for new update and show the artist option in the form of cards....
@Satyam1923 please assign this task to me...
