### ISSUE TITLE
Feat:Home page UI and navabr

### ISSUE THREAD

**Issue by AakankshaSarode** [Satyam1923/Spring-Music-Player#73]
### Describe the feature

there is not home page when user visit first time website user might think it take time to laod website if there is no home page is present

### Add ScreenShots

![Screenshot 2024-05-12 200845](https://github.com/Satyam1923/Spring-Music-Player/assets/142107143/5da0409a-10b3-4b08-a108-dfefbec11069)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AakankshaSarode** [comment]
@Satyam1923  please assign me this issue under GSSOC'24 .I want to work on this issue

**Comment by tanu-agarwal0101** [comment]
@Satyam1923  please assign me to work on the frontend of home page according to the figma design under gssoc'24

**Comment by Swapnil-Bhatnagar** [comment]
Please assign this issue to me. I want to work upon this!

**Comment by hritika2409** [comment]
@Satyam1923 Please assign me this task i can help you with this

**Comment by Satyam1923** [comment]
@AakankshaSarode check the new design the what all changes you want to do.

**Comment by saurabhsingh720** [comment]
@AakankshaSarode  do this task asap.

**Comment by ShivamPant1321** [comment]
@Satyam1923 I would really like to contribute to this issue. Kindly assign this to me under my GSSoC'24.

**Comment by Vinaysohaliya** [comment]
I would like to work on this issue. Please assign it to me under GSSOC'24.

**Comment by Yuvraj960** [comment]
@Satyam1923 Please assign this issue to me under GSSoC24.

**Comment by rahulkumarmutcherla** [comment]
I would like to work on this issue under gssoc.
Please assign me this issue

**Comment by K-21** [comment]
i would like to work on this issue under GSSOC'24

**Comment by Satyam1923** [comment]
Inactive issue.
