### ISSUE TITLE
Introducing a album feature where specific albums containing the songs and tunes to the movies or web series can be added.

### ISSUE THREAD

**Issue by Deepanshdevelop0** [Satyam1923/Spring-Music-Player#75]
Introducing a album feature where specific albums containing the songs and tunes to the movies or web series can be added.

Also adding the albums section to the home page.

**Comment by Deepanshdevelop0** [comment]
Kindly assign this feature to me under Gssoc'24 label.

**Comment by Satyam1923** [comment]
@Deepanshdevelop0 can you check the design first and then tell if you wan to implement changes for album.
