### ISSUE TITLE
Feat: Adding a Contact-Us page for user interaction and enhanced experience.

### ISSUE THREAD

**Issue by PriyamvadaShah** [Satyam1923/Spring-Music-Player#77]
### Describe the feature

1. Creating a contact-us page with relevant header with navbar with a good logo fitting the theme.
2. Adding relevant fields for details of the user.
3. Creating aesthetics and hover effects that fit the idea of the website i.e. musical.
4. Making it responsive in every device.
5. A relevant footer with appropriate detailing.

Kindly assign it to me under GSSoC'24

### Add ScreenShots

![Screenshot 2024-05-13 013738](https://github.com/Satyam1923/Spring-Music-Player/assets/118747750/dcaad1fb-15bd-4722-8ab4-c30001375571)

A music inclined website with similar layout along with a header and footer.

![Screenshot 2024-05-13 013913](https://github.com/Satyam1923/Spring-Music-Player/assets/118747750/51b133f2-9e92-40c6-881c-a539f289c526)

Adding a logo to enhance the branding and feel.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@PriyamvadaShah Since we didn't design our contact us page would like to work on designing .

**Comment by PriyamvadaShah** [comment]
@Satyam1923 So should I design it or your team/you will be doing it?

**Comment by Satyam1923** [comment]
@PriyamvadaShah if you to want to design I can assign you.

**Comment by Kazasunitha** [comment]
I have good experience in developing webpages so that I can solve this issue and do the contact page. Hope you assign it to me and label it as GCCoS24.

**Comment by PriyamvadaShah** [comment]
> @PriyamvadaShah if you to want to design I can assign you.

Ok I will turn in the designs soon.
