### ISSUE TITLE
Feat: Enhancing full Sidebar and searchbar with icons to Align with Website Theme.

### ISSUE THREAD

**Issue by dhruv389** [Satyam1923/Spring-Music-Player#78]
### Describe the feature

The feature involves enhancing the design of the search bar to better align with the overall theme of the website. Currently, the search bar does not meet the visual standards of the website theme and lacks aesthetic appeal. By implementing changes to the design, including adjustments to colors, typography, and layout, we aim to create a more visually appealing and cohesive search bar that seamlessly integrates with the website's theme.

-------------------------------------------------------------------------------------------
**Please assign me this issue**
-------------------------------------------------------------------------------------------

### Add ScreenShots

I want to change Search bar and search button with icon:
---
![Screenshot 2024-05-13 024901](https://github.com/Satyam1923/Spring-Music-Player/assets/117587892/9bcb82b0-37cb-4b40-9eea-f467b1bfb65a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@dhruv389 checkout new design if you want to make react elements for that design for can but not in this issue.

**Comment by dhruv389** [comment]
i want to make Side bar , and i will give it glassmorphism effect and all sections with icons accroding your figma design.
---
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/117587892/d7e8f96c-24c3-4f75-a783-fd37633b3888)

**Comment by Satyam1923** [comment]
@dhruv389 you can work for this issue.

**Comment by dhruv389** [comment]
hello @Satyam1923 ,

i  made this design . and i am woking on it ..

is it okay  ??
---
![Screenshot 2024-05-15 181121](https://github.com/Satyam1923/Spring-Music-Player/assets/117587892/c40b9227-8317-4fee-90fc-250f7908c593)

**Comment by dhruv389** [comment]
but you have to change the lable : Level2 to  Level3. There's a lot of changes left to do.and i am working on it.

**Comment by dhruv389** [comment]
hello @riyasachdeva04 , @saurabhsingh720 ,@Satyam1923 .
i want to create 4 different pull requests for this tasks.
