### ISSUE TITLE
Feat:  Implementing Custom Scrollbar for Improved UI in Song Lists

### ISSUE THREAD

**Issue by dhruv389** [Satyam1923/Spring-Music-Player#79]
### Describe the feature

The feature involves implementing a custom scrollbar to enhance the user interface (UI) of song lists. Currently, the default scrollbar may not align with the aesthetic or design standards of the website, detracting from the overall user experience. By introducing a custom scrollbar, we aim to create a more visually appealing and cohesive UI for scrolling through song lists, improving usability and user engagement.

### Add ScreenShots

![Screenshot 2024-05-13 025417](https://github.com/Satyam1923/Spring-Music-Player/assets/117587892/a308749b-485c-4be8-a742-e94d97ea921a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@dhruv389 you can take up this issue.

**Comment by Akshatakapare** [comment]
I want to work on this,please assign me this issue
