### ISSUE TITLE
Feat:  Updating Font Style, Color, and Size to Match Website Theme

### ISSUE THREAD

**Issue by dhruv389** [Satyam1923/Spring-Music-Player#80]
### Describe the feature

The feature involves updating the font style, color, and size across the website to ensure consistency and alignment with the overall theme. Currently, the font attributes may not fully reflect the desired look and feel of the website theme, leading to inconsistency and a lack of visual coherence. By implementing changes to the font style, color, and size, we aim to create a more unified and aesthetically pleasing design that enhances the user experience.

### Add ScreenShots

I will attach screenshots after changes
---

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@dhruv389 checkout our design ! then suggest changes accordingly

**Comment by dhruv389** [comment]
you mean  figma design ???

**Comment by Satyam1923** [comment]
ya

**Comment by dhruv389** [comment]
I know some the text types  accroding this website  figma design.
After changes in font style , The font of whole website looks like this  ,same as figma design:
---
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/117587892/98152a1b-3553-4660-a4a9-93d36734af59)

**Comment by atharvmalve** [comment]
hello @dhruv389, do you want to improve the figma design or implement the design in the app??

**Comment by dhruv389** [comment]
@atharvmalve  ,implement the design in the app.

**Comment by Satyam1923** [comment]
@dhruv389 you can work for it.
