### ISSUE TITLE
Lyrics and sleep timer

### ISSUE THREAD

**Issue by Priya-49** [Satyam1923/Spring-Music-Player#82]
### Describe the feature

Lyrics for the current song being played and sleep timer which allows the user to set a timer to automatically stop playback after a certain period, ideal for falling asleep to music.

### Add ScreenShots

![Screenshot (209)](https://github.com/Satyam1923/Spring-Music-Player/assets/118010930/5b72e698-2316-438e-846d-fe146002c963)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Priya-49 if you want to work on these issue please tell the changes you'll be implementing.

**Comment by Priya-49** [comment]
I would like to add two buttons one for the lyrics which on clicked displays the lyrics inplace of the image and other for sleep timer for setting the exact time after which the songs pause.

**Comment by Satyam1923** [comment]
Could you please take a look at new designs and tell where we could have lyrics integration.

**Comment by saurabhsingh720** [comment]
@Priya-49  u can add this fuctionality as soon as possible.

**Comment by Priya-49** [comment]
I would like to make the changes in the following way...(lyrics would be displayed on clicking the card)
![Screenshot 2024-05-14 115023](https://github.com/Satyam1923/Spring-Music-Player/assets/118010930/dac00dc2-8a9c-461c-80c7-8811f3cf644c)
![Screenshot 2024-05-14 115611](https://github.com/Satyam1923/Spring-Music-Player/assets/118010930/c7d5015e-c946-432f-9b7d-f43855a8d811)

**Comment by saurabhsingh720** [comment]
@Priya-49  Go for it

**Comment by Priya-49** [comment]
I have added lyrics feature to the existing design...please have look. And I incresed the width since audio player and shuffle button went out of the box. I will send the pull request if this is ok. 
![Screenshot (204)](https://github.com/Satyam1923/Spring-Music-Player/assets/118010930/e61dddc0-8238-49f5-9e6f-77116fbbc0fe)
Unfortunately the lyrics were not available to few song.
