### ISSUE TITLE
Feat: Improve the UI

### ISSUE THREAD

**Issue by suraj-9849** [Satyam1923/Spring-Music-Player#83]
### Describe the feature

I would like to improve the UI of the website 
This looks like the basic ui I will enhance the UI by using the best animations library like framermotion,Locomotive JS and GSAP animations and give the best user experience.

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/146669517/4043c810-642d-4592-8bd8-2ed189902766)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@suraj-9849 firstly check the design work on other expect then move to animations.
