### ISSUE TITLE
Feat: Adding the background Image to look good

### ISSUE THREAD

**Issue by SadafKausar2025** [Satyam1923/Spring-Music-Player#86]
### Describe the feature

the background image will give a good look at the projects 

i have collected some of the background images. you can also suggest to me

### Add ScreenShots

![background](https://github.com/Satyam1923/Spring-Music-Player/assets/137484958/0153fc66-a3fb-4b69-bc05-bcc7fb8d21f4)

![wood-background](https://github.com/Satyam1923/Spring-Music-Player/assets/137484958/51a3c708-5f1e-4865-8db5-cad0c5311f8f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SadafKausar2025** [comment]
![guitar](https://github.com/Satyam1923/Spring-Music-Player/assets/137484958/4649e18c-7601-41f3-8843-b65f03dcf6c1)

**Comment by SadafKausar2025** [comment]
this looks good can i apply it?

![WhatsApp Image 2024-05-13 at 19 33 28_5aaece5c](https://github.com/Satyam1923/Spring-Music-Player/assets/137484958/06c9ffa8-2716-432f-a79e-7afee6e6753e)

**Comment by Satyam1923** [comment]
We already have a design.
