### ISSUE TITLE
Search symbol is missing 

### ISSUE THREAD

**Issue by Ajita369** [Satyam1923/Spring-Music-Player#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There should be a search symbol or search written on the search box . 
![image](https://github.com/Satyam1923/Spring-Music-Player/assets/162597493/7e85eb03-247f-43a2-bed5-42fd1564bef6)
Please assign this issue to me under GSSOC'24.
Thank you.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@Ajita369 you can work on this issue.
