### ISSUE TITLE
Feat: Home Component

### ISSUE THREAD

**Issue by The-Phoenics** [Satyam1923/Spring-Music-Player#88]
### Describe the feature

Hey @Satyam1923, I check the figma design file and I think I'll be able to implement it and would like to start with the Home Page (React Component) first.
I would like to work on this for GSSoC'24. Can you please assign this to me?

### Add ScreenShots

![design](https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/b031986f-b846-486c-8617-06eeb57662c6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@The-Phoenics you can work on it!

**Comment by The-Phoenics** [comment]
https://github.com/Satyam1923/Spring-Music-Player/pull/126
