### ISSUE TITLE
[Fix] Unecessary Calls from backend

### ISSUE THREAD

**Issue by Satyam1923** [Satyam1923/Spring-Music-Player#9]
Currently, we have to make another call in script.js from the p function to fetch data from the backend endpoint (base-url/search1), even though we've already rendered the EJS with data from the /search endpoint. Could you please address this issue?

**Comment by itz-mohit-014** [comment]
Hello, I am a contributor of GSSOC24, I have all the skill sets used in this project and I am capable of fixing this issue if you allow me to fix it.
Thank You.

**Comment by Satyam1923** [comment]
Go ahead !

**Comment by TomLucasakaTGeek** [comment]
Hey @Satyam1923 can you assign this issue to me.

**Comment by poojaverma9578** [comment]
Hello,I want to contribute in this project,please assign me this

**Comment by Satyam1923** [comment]
@itz-mohit-014 any progress.

**Comment by TomLucasakaTGeek** [comment]
Assign it to me sir @Satyam1923 I will fix it immediately

**Comment by Satyam1923** [comment]
Issue already being resolved after merging new react migration.

**Comment by itz-mohit-014** [comment]
> @itz-mohit-014 any progress.

Sorry for the inconvenience, I was busy with my exams that's why I was not able to be active here for the last 2-3 days. 
I will come back after 15 May with full of productivity after the exams and start contributing here.
