### ISSUE TITLE
Feat: Dark and light mode 

### ISSUE THREAD

**Issue by NitinChakrawarti** [Satyam1923/Spring-Music-Player#92]
### Describe the feature

Currently website doesn't have light and dark mode feature which make user experience horrible at night time and also text in website is not showing after loading. 

@Satyam1923  I can make create a button for above described functionality.

### Add ScreenShots

![Screenshot 2024-05-13 200031](https://github.com/Satyam1923/Spring-Music-Player/assets/149225785/f80e4d25-9fd7-4641-871f-44f8ab6a79cd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@NitinChakrawarti first check the design! before raising issue.

**Comment by NitinChakrawarti** [comment]
![Screenshot_20240513_204414_Chrome](https://github.com/Satyam1923/Spring-Music-Player/assets/149225785/9655ebd1-fee8-44d7-b33c-10cb55aeaac1)

There is no theme switch button in website.
