### ISSUE TITLE
Add the placeholder and search icon BUG:

### ISSUE THREAD

**Issue by uraj1** [Satyam1923/Spring-Music-Player#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We can add the search icon and also add the placeholder in the search textbox
![Screenshot (3)](https://github.com/Satyam1923/Spring-Music-Player/assets/139366493/2bb2cb1f-02e9-44f7-91f8-28d14f530c8c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
Can't you see the same issue has already been raided.
