### ISSUE TITLE
Feat: Create Search Page Component

### ISSUE THREAD

**Issue by CoderSwarup** [Satyam1923/Spring-Music-Player#94]
### Describe the feature

i see the figma design i can see their an search result page and i think i can make this design 
please assign this feature , i want to work on this 

### Add ScreenShots

![image](https://github.com/Satyam1923/Spring-Music-Player/assets/128630311/6af30aaa-a7cd-42d1-9790-21d0da69428b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Satyam1923** [comment]
@CoderSwarup you can work on this issue. Please take you time but complete under a week.

**Comment by drick-infinity** [comment]
assign this issue to me under gssoc'24 As I learnedMERN full stack development I create better ui for this

**Comment by drick-infinity** [comment]
I made same design as mnetion in figma

**Comment by Satyam1923** [comment]
Irrelevant now.
