### ISSUE TITLE
Feat:Allow users to mark songs as favorites for quick access and also implement user aunthentication

### ISSUE THREAD

**Issue by ksatya2003** [Satyam1923/Spring-Music-Player#99]
### Describe the feature

For storing user preferences such as favorite songs, playlists, etc., if needed.

### Add ScreenShots

Sample  image link:  https://i.pinimg.com/originals/5c/63/8d/5c638d35b9b92257cd19fd06f6c90298.jpg
this like we adding like symbol to store favourite lists

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ksatya2003** [comment]
Thank you

**Comment by saurabhsingh720** [comment]
@ksatya2003  do it as soon as possible

**Comment by ksatya2003** [comment]
Thank you very much @saurabhsingh720

**Comment by ksatya2003** [comment]
@saurabhsingh720 when will i submit this assignment

**Comment by saurabhsingh720** [comment]
@ksatya2003 complete it within 2-3 days

**Comment by ksatya2003** [comment]
ok sir
